#!/usr/bin/env bash
# Build the "Philosopher in a Box" pitch deck.
#
# Pipeline:
#   1. Refresh slide-11 and team data from the live DB by running
#      live_snapshot.py. If the script exits non-zero (DB unreachable,
#      env not set, query returned nothing) the build aborts here — we
#      do not ship the deck with stale or fabricated numbers.
#   2. Run pdflatex twice so refs / TOC resolve.
#   3. Grep the log for unrecoverable errors and exit non-zero on any.
#   4. Verify the resulting deck.pdf is under 5 MB.
#
# Pass --allow-snapshot-fallback to ship a placeholder snapshot when no
# DATABASE_URL is configured. This is for local-dev / CI smoke runs
# only; production builds must run with a live DB and the flag absent.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"

allow_fallback=0
for arg in "$@"; do
  case "$arg" in
    --allow-snapshot-fallback) allow_fallback=1 ;;
    *)
      echo "build_deck.sh: unknown argument '${arg}'" >&2
      exit 2
      ;;
  esac
done

if ! command -v pdflatex >/dev/null 2>&1; then
  echo "build_deck.sh: pdflatex not found on PATH" >&2
  exit 2
fi

python_bin="${PYTHON:-python3}"
if ! command -v "$python_bin" >/dev/null 2>&1; then
  echo "build_deck.sh: ${python_bin} not found on PATH" >&2
  exit 2
fi

echo ">>> refreshing slide-11 snapshot from the live DB"
if ! "$python_bin" live_snapshot.py; then
  if [[ "$allow_fallback" -eq 1 ]]; then
    echo "build_deck.sh: snapshot failed; writing placeholder because --allow-snapshot-fallback was passed" >&2
    cat >slide11_data.tex <<'TEX'
% Placeholder generated by build_deck.sh --allow-snapshot-fallback.
% This is for local-dev and CI smoke runs only. Production builds must
% run with a live DATABASE_URL.
\begin{tabular}{@{}>{\raggedright\arraybackslash}p{0.45\textwidth}@{\hspace{0.05\textwidth}}>{\raggedright\arraybackslash}p{0.4\textwidth}@{}}
  \sffamily\bfseries\color{amber}Algorithms active & --- \\[0.18in]
  \sffamily\bfseries\color{amber}Principles in corpus & --- \\[0.18in]
  \sffamily\bfseries\color{amber}Memos published & --- \\[0.18in]
  \sffamily\bfseries\color{amber}Invocations recorded & --- \\[0.18in]
  \sffamily\bfseries\color{amber}Invocations resolved & --- \\[0.18in]
  \sffamily\bfseries\color{amber}Calibration & --- \\
\end{tabular}

\vspace{0.15in}
{\sffamily\fontsize{9pt}{11pt}\selectfont\color{amberdim}%
 Placeholder snapshot. Production builds run \texttt{live\_snapshot.py}
 against the live DB.}
TEX
    cat >team_data.tex <<'TEX'
% Placeholder generated by build_deck.sh --allow-snapshot-fallback.
\slidesub{Team data is generated from the live founder roster at build
time. This placeholder is shown only when no DATABASE\_URL is
configured.}
TEX
  else
    echo "build_deck.sh: snapshot failed; aborting build. Pass --allow-snapshot-fallback for local-dev runs." >&2
    exit 1
  fi
fi

base="deck"
log="${base}.log"
pdf="${base}.pdf"

echo ">>> compiling ${base}.tex (pass 1/2)"
pdflatex -interaction=nonstopmode -halt-on-error "${base}.tex" >/dev/null
echo ">>> compiling ${base}.tex (pass 2/2)"
pdflatex -interaction=nonstopmode -halt-on-error "${base}.tex" >/dev/null

if grep -E -i '^! |LaTeX Error|Emergency stop' "$log" >/dev/null; then
  echo "build_deck.sh: errors found in ${log}" >&2
  grep -E -i '^! |LaTeX Error|Emergency stop' "$log" >&2 || true
  exit 1
fi

if [[ ! -f "$pdf" ]]; then
  echo "build_deck.sh: ${pdf} not produced" >&2
  exit 1
fi

bytes=$(wc -c <"$pdf" | tr -d ' ')
if (( bytes >= 5 * 1024 * 1024 )); then
  echo "build_deck.sh: ${pdf} is ${bytes} bytes, over the 5 MB limit" >&2
  exit 1
fi

echo "build_deck.sh: built ${pdf} (${bytes} bytes)"
