"""
Meta-Analytical Layer for Noosphere.

This module performs real-time methodological analysis of substantive discourse.
The firm's brain stores only METHODOLOGICAL knowledge, but most podcast discussion
is SUBSTANTIVE (about what's true in the world). The Meta-Analytical Layer sits on
top of the classifier and transforms substantive discourse into methodological
insights — asking "what method is being used here? Is it reliable? What would make
it more rigorous?"

This module is the bridge between substance and method. When founders discuss a
substantive topic, the meta-analytical layer generates the methodological
observations that the brain actually stores.
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime, date
from enum import Enum
from typing import Any, Optional, Tuple
from collections import Counter

from anthropic import Anthropic, APIError
from pydantic import BaseModel, Field

from noosphere.classifier import (
    ClassifiedClaim,
    DiscourseType,
    MethodAttributionType,
)
from noosphere.models import (
    Claim,
    Principle,
    Discipline,
    ConvictionLevel,
)

from noosphere.observability import get_logger

logger = get_logger(__name__)


# ── Enums ────────────────────────────────────────────────────────────────────

class MethodologicalObservationType(str, Enum):
    """Categories of methodological observations."""

    METHOD_USAGE = "method_usage"
    """Which method was used in this discourse (e.g., 'analogical reasoning',
    'empirical analysis', 'first-principles decomposition')."""

    METHOD_QUALITY = "method_quality"
    """How well a method was applied. Is it being used rigorously or carelessly?"""

    METHOD_GAP = "method_gap"
    """What method should have been used but wasn't. Identifies blind spots."""

    METHOD_PATTERN = "method_pattern"
    """Recurring methodological habits across multiple episodes (e.g., 'the firm
    defaults to analogical reasoning for technology predictions')."""

    METHOD_RECOMMENDATION = "method_recommendation"
    """Suggested improvement to reasoning process."""


class SourceType(str, Enum):
    """Origin of the methodological observation."""

    INFERRED_FROM_DISCOURSE = "inferred_from_discourse"
    """Generated by analyzing substantive claims in an episode."""

    CALIBRATION_FEEDBACK = "calibration_feedback"
    """Generated from historical accuracy data about a method."""

    PATTERN_DETECTED = "pattern_detected"
    """Detected across multiple episodes via pattern analysis."""

    MANUAL = "manual"
    """Manually added by a user or analyst."""


# ── Pydantic Models ──────────────────────────────────────────────────────────

class MethodologicalObservation(BaseModel):
    """
    A methodological insight extracted from substantive discourse.

    These observations are phrased as claims about METHOD, not about substance.
    They represent the firm's evolving understanding of its own reasoning patterns
    and the reliability of different approaches.
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    """Unique identifier."""

    observation: str
    """The methodological insight, phrased as a claim about method, not substance.
    Example: 'Analogical reasoning was used to reach this conclusion about
    network effects. The analogy holds in dimensions X and Y but breaks in Z.'"""

    observation_type: MethodologicalObservationType
    """Category: method_usage, method_quality, method_gap, method_pattern,
    or method_recommendation."""

    source_type: SourceType
    """Origin of this observation."""

    source_claims: list[str] = Field(default_factory=list)
    """IDs of substantive claims that prompted this observation."""

    episode_id: str
    """Which episode this observation originates from."""

    confidence: float = Field(ge=0.0, le=1.0)
    """0-1 confidence in this observation."""

    disciplines: list[Discipline] = Field(default_factory=list)
    """Knowledge domains relevant to this observation."""

    created_at: datetime = Field(default_factory=datetime.now)
    """When this observation was generated."""


# ── Prompts ──────────────────────────────────────────────────────────────────

DISCOURSE_ANALYSIS_PROMPT = """You are a methodological analyst for an epistemological research firm. Your task is to analyze a segment of substantive discourse and generate methodological observations.

You will be given:
1. A context about the discussion topic
2. A list of substantive claims made by the founders

Your job is to identify and describe:
- REASONING METHODS used in this segment (what intellectual tools were deployed?)
- QUALITY OF REASONING (are these methods being applied rigorously or carelessly?)
- REASONING GAPS (what methods should have been used but weren't?)
- IMPLICIT ASSUMPTIONS (what unstated premises are these claims resting on?)

OUTPUT FORMAT:
Generate a JSON array of observations. Each observation should be:
{
  "observation": "A single methodological claim phrased in neutral language. Example: 'The speakers used analogical reasoning to reach conclusions about market dynamics. The analogy holds in dimensions X and Y but may not hold in dimension Z because...'",
  "observation_type": "method_usage" | "method_quality" | "method_gap" | "method_recommendation",
  "confidence": 0.0-1.0,
  "reasoning": "Brief explanation of why this observation was made (1-2 sentences)"
}

CRITICAL: All observations must be phrased as METHODOLOGICAL claims, not as substantive claims.
Do NOT say "The conclusion about X is wrong" — that's substantive.
DO say "This conclusion was reached via analogy. The analogy assumes Y but Y is not examined."

Keep observations actionable: they should help the firm improve its reasoning process."""

REASONING_CHAIN_PROMPT = """You are evaluating the LOGIC of a reasoning chain. Your task is to analyze how substantive claims connect to each other and identify the structure of the argument.

You will be given:
1. A sequence of substantive claims that form a reasoning chain
2. Context about the domain

Your job is to describe:
- The LOGICAL STRUCTURE of the argument (deductive? inductive? abductive?)
- GAPS in the chain (where are the jumps?)
- IMPLICIT PREMISES (what unstated assumptions make the argument work?)
- BRITTLENESS (what would need to be true for the argument to fail?)
- SAMPLE SIZE PROBLEMS (if using inductive reasoning, is the sample sufficient?)

OUTPUT FORMAT:
Generate a JSON array of observations:
{
  "observation": "A methodological claim about the structure or quality of the reasoning chain. Example: 'The reasoning moved from premise P1 to conclusion C via analogical reasoning. The analogy holds on dimensions X and Y but breaks on dimension Z.'",
  "observation_type": "method_usage" | "method_quality" | "method_gap" | "method_recommendation",
  "confidence": 0.0-1.0,
  "reasoning": "Brief explanation (1-2 sentences)"
}

CRITICAL: Analyze the LOGIC, not the TRUTH of the conclusion. Say nothing about whether the conclusion is correct."""

METHOD_PATTERN_PROMPT = """You are identifying recurring methodological patterns across multiple episodes.

You will be given:
1. A set of methodological observations from multiple episodes
2. The observation types and methods involved

Your job is to identify:
- DOMINANT METHODS: Which reasoning methods are used most frequently? In what contexts?
- BLIND SPOTS: What methods are never or rarely used? What domains lack certain approaches?
- METHODOLOGICAL BIASES: Does the firm systematically prefer certain methods? Are there patterns?
- DRIFT: Has the firm's methodological approach changed over time?

OUTPUT FORMAT:
Generate a JSON array of pattern observations:
{
  "observation": "A high-level claim about recurring methodological patterns. Example: 'Across 20 discussions of technology predictions, 78% used analogical reasoning (drawing parallels to historical technologies). First-principles analysis was used in only 12% of cases.'",
  "observation_type": "method_pattern",
  "confidence": 0.0-1.0,
  "frequency": "X% of discussions" or "recurring in N episodes",
  "reasoning": "Brief analysis (1-2 sentences)"
}"""

FEEDBACK_PROMPT = """You are generating methodological feedback on a specific substantive claim.

You are given:
1. A substantive claim made by the firm
2. The reasoning method that produced it
3. Optional: historical accuracy data for this method in this domain

Your task is to provide METHODOLOGICAL feedback that helps the firm improve its reasoning.

IMPORTANT: Frame your feedback as methodological guidance, not as criticism of the conclusion itself.

OUTPUT FORMAT:
Respond with a string containing methodological guidance. Structure it as:

"This conclusion was reached via [METHOD]. Key methodological considerations:
- [Point 1 about the method's reliability]
- [Point 2 about assumptions in the method]
- [Point 3 about improvements to the process]
- [If accuracy data is available: historical accuracy information]"

Example:
"This prediction was reached via analogical reasoning (comparing to similar historical cases).
Analogical reasoning has a [68%] historical accuracy rate in technology predictions for this firm.
Methodological improvements: Has a counter-prediction been generated? What would falsify this
analogy? What base rate of successful analogies applies to this domain?"

Never criticize the conclusion itself. Only address the METHODOLOGY."""


# ── MetaAnalyzer ────────────────────────────────────────────────────────────

class MetaAnalyzer:
    """
    Performs real-time methodological analysis of substantive discourse.

    This is the bridge between the classifier (which identifies WHAT KIND of
    discourse is happening) and the brain (which stores only METHODOLOGICAL
    knowledge). The MetaAnalyzer transforms substantive claims into methodological
    observations that can be stored and learned from.
    """

    def __init__(
        self,
        client: Optional[Anthropic] = None,
        conclusions_registry: Optional[dict] = None
    ):
        """
        Initialize the meta-analyzer.

        Args:
            client: Optional Anthropic client. If None, creates a new one.
            conclusions_registry: Optional dict mapping method names to accuracy data.
        """
        self.client = client or Anthropic()
        self.conclusions_registry = conclusions_registry or {}
        logger.info("Initialized MetaAnalyzer")

    def analyze_discourse_segment(
        self,
        claims: list[ClassifiedClaim],
        context: str = ""
    ) -> list[MethodologicalObservation]:
        """
        Generate methodological observations from a batch of classified claims.

        Takes a segment of substantive discourse and generates methodological
        observations about the reasoning methods used, their quality, and gaps.

        Args:
            claims: List of ClassifiedClaim objects from a discourse segment
            context: Optional context about the topic being discussed

        Returns:
            List of MethodologicalObservation objects
        """
        # Filter to only substantive and mixed claims
        substantive_claims = [
            c for c in claims
            if c.discourse_type in (DiscourseType.SUBSTANTIVE, DiscourseType.MIXED)
        ]

        if not substantive_claims:
            logger.info("No substantive claims to analyze in segment")
            return []

        # Build prompt with claims
        claims_text = "\n".join(
            f"{i+1}. {c.text}"
            for i, c in enumerate(substantive_claims)
        )

        prompt = f"""{DISCOURSE_ANALYSIS_PROMPT}

Topic context: {context or "(no context)"}

Substantive claims:
{claims_text}

Generate methodological observations about these claims."""

        try:
            response = self.client.messages.create(
                model="claude-3-5-sonnet-20241022",
                max_tokens=1500,
                messages=[{"role": "user", "content": prompt}]
            )

            result_text = response.content[0].text.strip()

            # Extract JSON array from response
            observations = self._parse_observations_response(
                result_text,
                [c.claim_id for c in substantive_claims],
                claims[0].claim_id.split("_")[0]  # Use first claim's episode_id
                if substantive_claims else ""
            )

            logger.info(
                f"Generated {len(observations)} methodological observations "
                f"from {len(substantive_claims)} claims"
            )
            return observations

        except APIError as e:
            logger.error(f"Error analyzing discourse segment: {e}")
            return []

    def analyze_reasoning_chain(
        self,
        substantive_claims: list[ClassifiedClaim],
        context: str = ""
    ) -> list[MethodologicalObservation]:
        """
        Analyze the logic of a sequence of substantive claims.

        Takes a chain of claims that form an argument and evaluates the logical
        structure: is it deductive? inductive? Where are the gaps? What are the
        implicit premises?

        Args:
            substantive_claims: Ordered list of claims forming a reasoning chain
            context: Optional context about the domain

        Returns:
            List of MethodologicalObservation objects analyzing the chain logic
        """
        if not substantive_claims:
            return []

        # Build prompt with ordered claims
        claims_text = "\n".join(
            f"{i+1}. {c.text}"
            for i, c in enumerate(substantive_claims)
        )

        prompt = f"""{REASONING_CHAIN_PROMPT}

Domain context: {context or "(no context)"}

Reasoning chain (in order):
{claims_text}

Analyze the logical structure of this reasoning chain."""

        try:
            response = self.client.messages.create(
                model="claude-3-5-sonnet-20241022",
                max_tokens=1500,
                messages=[{"role": "user", "content": prompt}]
            )

            result_text = response.content[0].text.strip()

            observations = self._parse_observations_response(
                result_text,
                [c.claim_id for c in substantive_claims],
                substantive_claims[0].claim_id.split("_")[0]
                if substantive_claims else ""
            )

            logger.info(
                f"Generated {len(observations)} observations from reasoning chain analysis"
            )
            return observations

        except APIError as e:
            logger.error(f"Error analyzing reasoning chain: {e}")
            return []

    def detect_method_patterns(
        self,
        all_observations: list[MethodologicalObservation],
        window_episodes: int = 5
    ) -> list[MethodologicalObservation]:
        """
        Analyze accumulated observations to detect recurring methodological patterns.

        Looks across multiple episodes to identify:
        - Which reasoning methods dominate in which domains
        - What methods are rarely used (blind spots)
        - Patterns of change over time
        - Systematic biases in methodology

        Args:
            all_observations: All MethodologicalObservation objects accumulated
            window_episodes: How many recent episodes to analyze

        Returns:
            List of MethodologicalObservation objects describing patterns
        """
        if not all_observations:
            logger.info("No observations to analyze for patterns")
            return []

        # Count observation types and methods mentioned
        observation_counts: Counter = Counter()
        method_mentions: Counter = Counter()

        for obs in all_observations:
            observation_counts[obs.observation_type.value] += 1

            # Extract method names from observation text
            text_lower = obs.observation.lower()
            for method_name in [
                "analogical reasoning",
                "inductive reasoning",
                "deductive reasoning",
                "empirical analysis",
                "first-principles",
                "base rate",
                "authority",
                "pattern matching",
                "thought experiment",
            ]:
                if method_name in text_lower:
                    method_mentions[method_name] += 1

        if not method_mentions:
            logger.info("No specific method mentions found in observations")
            return []

        # Build pattern analysis prompt
        pattern_summary = "\n".join(
            f"- {method}: {count} mentions"
            for method, count in method_mentions.most_common()
        )

        observation_summary = "\n".join(
            f"- {obs_type}: {count} observations"
            for obs_type, count in observation_counts.most_common()
        )

        prompt = f"""{METHOD_PATTERN_PROMPT}

OBSERVATION SUMMARY (across {len(all_observations)} observations):
{observation_summary}

METHOD MENTIONS:
{pattern_summary}

Generate pattern observations about recurring methodological habits."""

        try:
            response = self.client.messages.create(
                model="claude-3-5-sonnet-20241022",
                max_tokens=1000,
                messages=[{"role": "user", "content": prompt}]
            )

            result_text = response.content[0].text.strip()

            # Parse pattern observations
            try:
                observations_data = json.loads(result_text)
                if not isinstance(observations_data, list):
                    observations_data = [observations_data]
            except json.JSONDecodeError:
                logger.warning("Could not parse pattern observations as JSON")
                return []

            pattern_observations = []
            for obs_data in observations_data:
                try:
                    pattern_observations.append(
                        MethodologicalObservation(
                            id=str(uuid.uuid4()),
                            observation=obs_data.get("observation", ""),
                            observation_type=MethodologicalObservationType.METHOD_PATTERN,
                            source_type=SourceType.PATTERN_DETECTED,
                            source_claims=[],
                            episode_id="multi_episode_pattern",
                            confidence=obs_data.get("confidence", 0.7),
                            disciplines=[],
                        )
                    )
                except Exception as e:
                    logger.warning(f"Error creating pattern observation: {e}")
                    continue

            logger.info(f"Generated {len(pattern_observations)} pattern observations")
            return pattern_observations

        except APIError as e:
            logger.error(f"Error detecting method patterns: {e}")
            return []

    def generate_methodological_feedback(
        self,
        substantive_claim_text: str,
        method_used: MethodAttributionType,
        historical_accuracy: Optional[float] = None
    ) -> str:
        """
        Generate methodological feedback on a specific substantive claim.

        Given a claim and the method used to produce it, generates feedback
        about the methodology: its reliability, implicit assumptions, and
        suggested improvements.

        Args:
            substantive_claim_text: The substantive claim
            method_used: The MethodAttributionType that produced it
            historical_accuracy: Optional 0-1 value for this method's accuracy

        Returns:
            String containing methodological feedback
        """
        accuracy_context = ""
        if historical_accuracy is not None:
            accuracy_pct = int(historical_accuracy * 100)
            accuracy_context = f"\nHistorical accuracy of {method_used.value} " \
                             f"in this domain: {accuracy_pct}%"

        prompt = f"""{FEEDBACK_PROMPT}

Claim: {substantive_claim_text}
Method used: {method_used.value}
{accuracy_context}

Provide methodological feedback."""

        try:
            response = self.client.messages.create(
                model="claude-3-5-sonnet-20241022",
                max_tokens=500,
                messages=[{"role": "user", "content": prompt}]
            )

            feedback = response.content[0].text.strip()
            logger.info("Generated methodological feedback")
            return feedback

        except APIError as e:
            logger.error(f"Error generating feedback: {e}")
            return f"Unable to generate feedback: {e}"

    def bridge_to_brain(
        self,
        observations: list[MethodologicalObservation]
    ) -> list[dict]:
        """
        Convert MethodologicalObservations into a format suitable for the brain.

        Transforms observations into structured data that can be promoted to
        full Principles in the ontology graph. The output includes fields for
        disciplines, conviction level, and evidence trail.

        Args:
            observations: List of MethodologicalObservation objects

        Returns:
            List of dicts with keys: text, disciplines, conviction_level, evidence
        """
        brain_ready = []

        for obs in observations:
            principle_dict = {
                "text": obs.observation,
                "disciplines": obs.disciplines or [Discipline.EPISTEMOLOGY],
                "conviction_level": self._confidence_to_conviction(obs.confidence),
                "conviction_score": obs.confidence,
                "evidence": {
                    "source_type": obs.source_type.value,
                    "source_claims": obs.source_claims,
                    "episode_id": obs.episode_id,
                    "created_at": obs.created_at.isoformat(),
                },
                "tags": [obs.observation_type.value],
            }
            brain_ready.append(principle_dict)

        logger.info(f"Prepared {len(brain_ready)} observations for brain ingestion")
        return brain_ready

    # ── Helpers ──────────────────────────────────────────────────────────────

    def _parse_observations_response(
        self,
        response_text: str,
        source_claim_ids: list[str],
        episode_id: str
    ) -> list[MethodologicalObservation]:
        """
        Parse JSON response into MethodologicalObservation objects.

        Args:
            response_text: Raw response from Claude
            source_claim_ids: List of claim IDs that prompted these observations
            episode_id: Which episode the observations come from

        Returns:
            List of MethodologicalObservation objects
        """
        try:
            observations_data = json.loads(response_text)
            if not isinstance(observations_data, list):
                observations_data = [observations_data]
        except json.JSONDecodeError:
            logger.warning("Could not parse observations as JSON")
            return []

        observations = []
        for obs_data in observations_data:
            try:
                observation_type_str = obs_data.get(
                    "observation_type",
                    "method_usage"
                )
                observation_type = MethodologicalObservationType(observation_type_str)

                obs = MethodologicalObservation(
                    id=str(uuid.uuid4()),
                    observation=obs_data.get("observation", ""),
                    observation_type=observation_type,
                    source_type=SourceType.INFERRED_FROM_DISCOURSE,
                    source_claims=source_claim_ids,
                    episode_id=episode_id,
                    confidence=float(obs_data.get("confidence", 0.7)),
                    disciplines=[Discipline.EPISTEMOLOGY],
                )
                observations.append(obs)
            except (KeyError, ValueError) as e:
                logger.warning(f"Error parsing observation: {e}")
                continue

        return observations

    @staticmethod
    def _confidence_to_conviction(confidence: float) -> ConvictionLevel:
        """
        Convert a confidence score (0-1) to a ConvictionLevel.

        Args:
            confidence: 0-1 confidence value

        Returns:
            ConvictionLevel enum value
        """
        if confidence >= 0.9:
            return ConvictionLevel.AXIOM
        elif confidence >= 0.75:
            return ConvictionLevel.STRONG
        elif confidence >= 0.6:
            return ConvictionLevel.MODERATE
        elif confidence >= 0.4:
            return ConvictionLevel.EXPLORATORY
        else:
            return ConvictionLevel.CONTESTED


# ── DiscourseMonitor ────────────────────────────────────────────────────────

class DiscourseMonitor:
    """
    Main integration point for processing entire episodes.

    Orchestrates the full pipeline:
    1. Classifies all claims in an episode
    2. Routes claims to appropriate destinations (brain, conclusions registry)
    3. Decomposes mixed claims
    4. Performs meta-analysis on substantive discourse
    5. Promotes strongest observations to principles
    6. Generates episode methodology report
    """

    def __init__(
        self,
        classifier,
        meta_analyzer: MetaAnalyzer,
        conclusions_registry: dict,
        ontology_graph
    ):
        """
        Initialize the discourse monitor.

        Args:
            classifier: DiscourseClassifier instance
            meta_analyzer: MetaAnalyzer instance
            conclusions_registry: Dict for storing substantive conclusions
            ontology_graph: OntologyGraph instance (the brain)
        """
        self.classifier = classifier
        self.meta_analyzer = meta_analyzer
        self.conclusions_registry = conclusions_registry
        self.ontology_graph = ontology_graph
        logger.info("Initialized DiscourseMonitor")

    def process_episode_claims(
        self,
        claims: list[Claim],
        episode_id: str,
        episode_date: date
    ) -> dict:
        """
        Process all claims from an episode: classify, route, analyze, store.

        This is the main integration point. For each episode, it:
        1. Classifies each claim
        2. Routes METHODOLOGICAL and META_METHODOLOGICAL to the brain
        3. Routes SUBSTANTIVE to conclusions registry (with method attribution)
        4. Decomposes MIXED claims
        5. Runs meta-analysis to extract methodological observations
        6. Promotes strongest observations to principles
        7. Returns a summary report

        Args:
            claims: List of Claim objects from the episode
            episode_id: Episode identifier
            episode_date: Episode date

        Returns:
            Dict with summary: claim_counts_by_type, new_principles_found,
            new_conclusions_registered, methodological_observations_generated
        """
        logger.info(f"Processing {len(claims)} claims from episode {episode_id}")

        # Phase 1: Classify all claims
        classified_claims = []
        for claim in claims:
            classified = self.classifier.classify(
                claim.text,
                context=claim.segment_context,
                claim_id=claim.id
            )
            classified_claims.append(classified)

        # Phase 2: Route and decompose
        methodological_claims = []
        substantive_claims = []
        mixed_claims = []
        conclusions_to_register = []

        for classified in classified_claims:
            if classified.discourse_type == DiscourseType.METHODOLOGICAL:
                methodological_claims.append(classified)
                # Route to brain
                self._route_methodological_to_brain(classified, episode_id)

            elif classified.discourse_type == DiscourseType.META_METHODOLOGICAL:
                # Route to brain as well
                self._route_methodological_to_brain(classified, episode_id)

            elif classified.discourse_type == DiscourseType.SUBSTANTIVE:
                substantive_claims.append(classified)
                # Register as conclusion
                conclusions_to_register.append(classified)

            elif classified.discourse_type == DiscourseType.MIXED:
                mixed_claims.append(classified)
                # Decompose and route components
                self._decompose_and_route_mixed(classified, episode_id)
                # Also analyze substantive component
                if classified.substantive_content:
                    substantive_claims.append(classified)

        # Phase 3: Meta-analysis on substantive discourse
        all_substantive = substantive_claims + mixed_claims
        methodological_observations = (
            self.meta_analyzer.analyze_discourse_segment(
                all_substantive,
                context=f"Episode {episode_id}"
            )
        )

        # Phase 4: Route strong observations to brain as principles
        promoted_count = 0
        for obs in methodological_observations:
            if obs.confidence >= 0.75:  # Only promote strong observations
                self._promote_observation_to_principle(obs)
                promoted_count += 1

        # Build summary report
        summary = {
            "episode_id": episode_id,
            "episode_date": episode_date.isoformat(),
            "claims_processed": len(claims),
            "claims_by_type": {
                "methodological": len(methodological_claims),
                "substantive": len(substantive_claims),
                "mixed": len(mixed_claims),
                "meta_methodological": sum(
                    1 for c in classified_claims
                    if c.discourse_type == DiscourseType.META_METHODOLOGICAL
                ),
                "non_propositional": sum(
                    1 for c in classified_claims
                    if c.discourse_type == DiscourseType.NON_PROPOSITIONAL
                ),
            },
            "conclusions_registered": len(conclusions_to_register),
            "methodological_observations_generated": len(methodological_observations),
            "observations_promoted_to_principles": promoted_count,
        }

        logger.info(
            f"Episode {episode_id} processing complete: "
            f"{summary['claims_by_type']['methodological']} methodological, "
            f"{summary['claims_by_type']['substantive']} substantive, "
            f"{len(methodological_observations)} observations generated"
        )

        return summary

    def episode_methodology_report(self, episode_id: str) -> dict:
        """
        Generate a report on an episode's methodological character.

        After processing an episode, produces a detailed report on:
        - Ratio of methodological to substantive discourse
        - Methods used in substantive reasoning
        - Methodological gaps identified
        - New methodological observations
        - Recommendations for future discussions

        Args:
            episode_id: Episode identifier

        Returns:
            Dict with methodology report
        """
        # This would require storing observations per episode
        # For now, return a template structure
        report = {
            "episode_id": episode_id,
            "methodology_character": {
                "substantive_ratio": 0.0,
                "methodological_ratio": 0.0,
            },
            "methods_used": {},
            "methodological_gaps": [],
            "new_observations": [],
            "recommendations": [],
        }

        logger.info(f"Generated methodology report for episode {episode_id}")
        return report

    # ── Routing Helpers ──────────────────────────────────────────────────────

    def _route_methodological_to_brain(
        self,
        claim: ClassifiedClaim,
        episode_id: str
    ) -> None:
        """Route a methodological claim to the ontology graph."""
        try:
            principle = Principle(
                text=claim.text,
                description=claim.decomposition_notes,
                disciplines=[Discipline.EPISTEMOLOGY],
                conviction=ConvictionLevel.EXPLORATORY,
                conviction_score=claim.confidence,
            )
            self.ontology_graph.add_principle(principle)
            logger.debug(f"Routed methodological claim to brain: {claim.text[:50]}")
        except Exception as e:
            logger.warning(f"Error routing methodological claim: {e}")

    def _decompose_and_route_mixed(
        self,
        claim: ClassifiedClaim,
        episode_id: str
    ) -> None:
        """Decompose a mixed claim and route its components."""
        # Methodological component goes to brain
        if claim.methodological_content:
            try:
                principle = Principle(
                    text=f"Method: {claim.methodological_content}",
                    disciplines=[Discipline.EPISTEMOLOGY],
                    conviction=ConvictionLevel.EXPLORATORY,
                    conviction_score=claim.confidence * 0.9,  # Slightly lower
                )
                self.ontology_graph.add_principle(principle)
            except Exception as e:
                logger.warning(f"Error routing methodological component: {e}")

    def _promote_observation_to_principle(
        self,
        observation: MethodologicalObservation
    ) -> None:
        """Promote a high-confidence observation to a principle."""
        try:
            principle = Principle(
                text=observation.observation,
                disciplines=observation.disciplines or [Discipline.EPISTEMOLOGY],
                conviction=DiscourseMonitor._confidence_to_conviction(
                    observation.confidence
                ),
                conviction_score=observation.confidence,
                supporting_claims=observation.source_claims,
                tags=[observation.observation_type.value],
                first_appeared=date.today(),
            )
            self.ontology_graph.add_principle(principle)
            logger.info(
                f"Promoted observation to principle: {observation.observation[:50]}"
            )
        except Exception as e:
            logger.warning(f"Error promoting observation to principle: {e}")

    @staticmethod
    def _confidence_to_conviction(confidence: float) -> ConvictionLevel:
        """
        Convert a confidence score (0-1) to a ConvictionLevel.

        Args:
            confidence: 0-1 confidence value

        Returns:
            ConvictionLevel enum value
        """
        if confidence >= 0.9:
            return ConvictionLevel.AXIOM
        elif confidence >= 0.75:
            return ConvictionLevel.STRONG
        elif confidence >= 0.6:
            return ConvictionLevel.MODERATE
        elif confidence >= 0.4:
            return ConvictionLevel.EXPLORATORY
        else:
            return ConvictionLevel.CONTESTED


# ═══════════════════════════════════════════════════════════════════════════
# Five-criterion meta-method gates (The Meta Method) — firm conclusions
# ═══════════════════════════════════════════════════════════════════════════


from dataclasses import dataclass as _meta_dataclass
from typing import Literal as _MetaLiteral

import numpy as _meta_np

MetaDomain = _MetaLiteral[
    "empirical_science",
    "historical_claim",
    "normative_philosophy",
    "predictive_forecast",
    "methodological_rule",
]

DOMAIN_CONFIDENCE_CEILING: dict[str, float] = {
    "empirical_science": 0.85,
    "historical_claim": 0.75,
    "normative_philosophy": 0.70,
    "predictive_forecast": 0.65,
    "methodological_rule": 0.80,
}


@_meta_dataclass
class ClaimClusterMeta:
    claim_ids: list[str]
    texts: list[str]
    centroid_embedding: Optional[list[float]] = None
    claimed_confidence: float = 0.5
    domain: MetaDomain = "normative_philosophy"
    adversarial_fingerprint: str = ""
    adversarial_store: Any | None = None


@_meta_dataclass
class CriterionResult:
    score: float
    reasoning: str


def criterion_progressivity(cluster: ClaimClusterMeta) -> CriterionResult:
    if len(cluster.texts) < 2:
        return CriterionResult(0.4, "Too few claims to assess progressivity.")
    lens = [len(t) for t in cluster.texts]
    var = float(_meta_np.var(_meta_np.asarray(lens, dtype=float)))
    score = float(_meta_np.clip(0.35 + min(1.0, var / 500.0), 0.0, 1.0))
    return CriterionResult(score, "Lexical variance proxy for progressivity.")


def criterion_severity(cluster: ClaimClusterMeta) -> CriterionResult:
    from noosphere.config import get_settings

    s = get_settings()
    if (
        s.adversarial_enforce
        and cluster.adversarial_fingerprint
        and cluster.adversarial_store is not None
    ):
        from noosphere.adversarial import adversarial_severity_criterion

        score, reason = adversarial_severity_criterion(
            cluster.adversarial_store,
            cluster.adversarial_fingerprint,
            int(s.adversarial_k),
        )
        return CriterionResult(score, reason)
    joined = " ".join(cluster.texts).lower()
    hedge = sum(1 for w in ("maybe", "perhaps", "sort of", "kind of") if w in joined)
    score = float(_meta_np.clip(0.75 - 0.08 * hedge, 0.0, 1.0))
    return CriterionResult(score, f"Hedge-density indicator (count={hedge}).")


def criterion_coherence(cluster: ClaimClusterMeta) -> CriterionResult:
    if not cluster.centroid_embedding or len(cluster.texts) < 2:
        return CriterionResult(0.55, "No centroid; neutral coherence.")
    return CriterionResult(0.72, "Centroid present; placeholder cohesion score.")


def criterion_compressibility(cluster: ClaimClusterMeta) -> CriterionResult:
    u = len(set(" ".join(cluster.texts).lower().split()))
    tot = max(1, sum(len(t.split()) for t in cluster.texts))
    ratio = u / tot
    score = float(_meta_np.clip(ratio * 1.4, 0.0, 1.0))
    return CriterionResult(score, f"Unique-token ratio={ratio:.3f}.")


def criterion_domain_sensitivity(cluster: ClaimClusterMeta) -> CriterionResult:
    cap = DOMAIN_CONFIDENCE_CEILING.get(cluster.domain, 0.7)
    if cluster.claimed_confidence > cap + 1e-6:
        return CriterionResult(
            0.0,
            f"Claimed confidence {cluster.claimed_confidence:.2f} exceeds ceiling {cap:.2f} for {cluster.domain}.",
        )
    headroom = max(0.0, cap - cluster.claimed_confidence)
    score = float(_meta_np.clip(0.5 + headroom, 0.0, 1.0))
    return CriterionResult(score, f"Within domain ceiling {cap:.2f}.")


META_THRESHOLDS: dict[str, float] = {
    "progressivity": 0.45,
    "severity": 0.55,
    "coherence": 0.50,
    "compressibility": 0.40,
    "domain_sensitivity": 0.50,
}


@_meta_dataclass
class MetaGateOutcome:
    passed_all: bool
    scores: dict[str, float]
    reasons: dict[str, str]
    route_open_question: bool
    failed_criteria: list[str]


def evaluate_five_meta_criteria(cluster: ClaimClusterMeta) -> MetaGateOutcome:
    checks = {
        "progressivity": criterion_progressivity,
        "severity": criterion_severity,
        "coherence": criterion_coherence,
        "compressibility": criterion_compressibility,
        "domain_sensitivity": criterion_domain_sensitivity,
    }
    scores: dict[str, float] = {}
    reasons: dict[str, str] = {}
    failed: list[str] = []
    for name, fn in checks.items():
        r = fn(cluster)
        scores[name] = r.score
        reasons[name] = r.reasoning
        if r.score < META_THRESHOLDS[name]:
            failed.append(name)
    pr = scores["progressivity"] < META_THRESHOLDS["progressivity"]
    sev = scores["severity"] < META_THRESHOLDS["severity"]
    route_oq = pr or sev or bool(failed)
    passed_all = not failed
    return MetaGateOutcome(
        passed_all=passed_all,
        scores=scores,
        reasons=reasons,
        route_open_question=route_oq,
        failed_criteria=failed,
    )
