# AUTOGENERATED FROM packages/shared-schemas/citation_verdict.schema.json.
# DO NOT EDIT BY HAND. Regenerate with
#   python packages/shared-schemas/scripts/generate_pydantic.py
# generated by datamodel-codegen:
#   filename:  citation_verdict.schema.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, confloat, constr


class CitationKind(Enum):
    opinion = "opinion"
    forecast = "forecast"
    conclusion_source = "conclusion_source"


class Relation(Enum):
    supports = "supports"
    contradicts = "contradicts"
    qualifies = "qualifies"
    mentions = "mentions"


class RelationHolds(Enum):
    entails = "entails"
    contradicts = "contradicts"
    neutral = "neutral"
    ambiguous = "ambiguous"


class CitationVerdict(BaseModel):
    """
    Citation-chain verdict ledger row. The Python NLI judge in noosphere/literature/citation_chain.py is canonical for the verdict label; this schema is the wire-shape the codex reads back into VerdictPill rendering and stores in the CitationVerdict table.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    citation_kind: CitationKind
    citation_id: constr(min_length=1)
    source_id: constr(min_length=1)
    relation: Relation
    relation_holds: RelationHolds
    confidence: confloat(ge=0.0, le=1.0)
    excerpt_used: str
    stated_claim: str
    cascade_weight: confloat(ge=0.0, le=1.0)
    model_version: str
    computed_at: datetime
    overridden_by: Optional[str] = None
    override_reason: Optional[str] = None
