# AUTOGENERATED FROM packages/shared-schemas/citation_verdict.schema.json.
# DO NOT EDIT BY HAND. Regenerate with
#   python packages/shared-schemas/scripts/generate_pydantic.py
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class CitationKind(str, Enum):
    opinion = "opinion"
    forecast = "forecast"
    conclusion_source = "conclusion_source"


class CitationRelation(str, Enum):
    supports = "supports"
    contradicts = "contradicts"
    qualifies = "qualifies"
    mentions = "mentions"


class VerdictLabel(str, Enum):
    entails = "entails"
    contradicts = "contradicts"
    neutral = "neutral"
    ambiguous = "ambiguous"


class CitationVerdict(BaseModel):
    """Citation-chain NLI verdict, wire-form."""

    model_config = ConfigDict(extra="forbid")

    citation_kind: CitationKind
    citation_id: str
    source_id: str
    relation: CitationRelation
    relation_holds: VerdictLabel
    confidence: float = Field(ge=0.0, le=1.0)
    excerpt_used: str
    stated_claim: str
    cascade_weight: float = Field(ge=0.0, le=1.0)
    model_version: str
    computed_at: datetime
    overridden_by: Optional[str] = None
    override_reason: Optional[str] = None
