# AUTOGENERATED FROM packages/shared-schemas/conclusion.schema.json.
# DO NOT EDIT BY HAND. Regenerate with
#   python packages/shared-schemas/scripts/generate_pydantic.py
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class ConclusionKind(str, Enum):
    firm = "firm"
    tentative = "tentative"
    exploratory = "exploratory"
    retracted = "retracted"


class ConfidenceTier(str, Enum):
    high = "high"
    moderate = "moderate"
    low = "low"
    speculative = "speculative"


class Freshness(str, Enum):
    fresh = "fresh"
    aging = "aging"
    stale = "stale"


class Conclusion(BaseModel):
    """Cross-language payload shape for a Conclusion record."""

    model_config = ConfigDict(extra="forbid")

    id: str
    text: str
    reasoning: str = ""
    rationale: str = ""
    kind: ConclusionKind = ConclusionKind.firm
    confidence_tier: ConfidenceTier = ConfidenceTier.moderate
    principles_used: List[str] = Field(default_factory=list)
    claims_used: List[str] = Field(default_factory=list)
    supporting_principle_ids: List[str] = Field(default_factory=list)
    evidence_chain_claim_ids: List[str] = Field(default_factory=list)
    dissent_claim_ids: List[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0)
    disciplines: List[str] = Field(default_factory=list)
    freshness: Freshness = Freshness.fresh
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    superseded_at: Optional[datetime] = None
    last_validated_at: Optional[datetime] = None
