# AUTOGENERATED FROM packages/shared-schemas/conclusion.schema.json.
# DO NOT EDIT BY HAND. Regenerate with
#   python packages/shared-schemas/scripts/generate_pydantic.py
# generated by datamodel-codegen:
#   filename:  conclusion.schema.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, confloat, constr


class Kind(Enum):
    firm = "firm"
    tentative = "tentative"
    exploratory = "exploratory"
    retracted = "retracted"


class ConfidenceTier(Enum):
    high = "high"
    moderate = "moderate"
    low = "low"
    speculative = "speculative"


class Freshness(Enum):
    fresh = "fresh"
    aging = "aging"
    stale = "stale"


class Conclusion(BaseModel):
    """
    Cross-language payload shape for a Conclusion record. Database-backed (Prisma owns the canonical TS row type via `Prisma.Conclusion`); this schema describes the JSON wire-form shipped between noosphere and codex (e.g. CLI exports, store sync) and is what runtime validators check on either side. Field names are snake_case to match the Pydantic side; the TS adapters translate to/from camelCase at the Prisma boundary.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: constr(min_length=1)
    text: str
    reasoning: Optional[str] = ""
    rationale: Optional[str] = ""
    kind: Optional[Kind] = "firm"
    confidence_tier: Optional[ConfidenceTier] = "moderate"
    principles_used: Optional[List[str]] = []
    claims_used: Optional[List[str]] = []
    supporting_principle_ids: Optional[List[str]] = []
    evidence_chain_claim_ids: Optional[List[str]] = []
    dissent_claim_ids: Optional[List[str]] = []
    confidence: confloat(ge=0.0, le=1.0)
    disciplines: Optional[List[str]] = []
    freshness: Optional[Freshness] = "fresh"
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    superseded_at: Optional[datetime] = None
    last_validated_at: Optional[datetime] = None
