# AUTOGENERATED FROM packages/shared-schemas/lineage.schema.json.
# DO NOT EDIT BY HAND. Regenerate with
#   python packages/shared-schemas/scripts/generate_pydantic.py
# generated by datamodel-codegen:
#   filename:  lineage.schema.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, constr


class LineageNodeKind(Enum):
    source = "source"
    claim = "claim"
    methodology = "methodology"
    method_invocation = "method_invocation"
    peer_review = "peer_review"
    revision = "revision"
    drift = "drift"
    calibration = "calibration"
    conclusion = "conclusion"
    publication = "publication"
    citation = "citation"


class LineageNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: constr(min_length=1)
    kind: LineageNodeKind
    label: str
    timestamp: datetime
    summary: Optional[str] = ""
    payload: Optional[Dict[str, Any]] = {}
    public_visible: Optional[bool] = False
    record_url: Optional[str] = ""


class LineageEdge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    src: constr(min_length=1)
    dst: constr(min_length=1)
    relation: constr(min_length=1)


class Lineage(BaseModel):
    """
    Provenance graph for a single Conclusion. Assembled on both sides — noosphere/temporal/lineage.py from the Store; theseus-codex/src/lib/lineage.ts from Prisma rows. The JSON shape must be byte-stable across implementations so the public route can serve either source.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    conclusion_id: constr(min_length=1)
    assembled_at: datetime
    nodes: List[LineageNode]
    edges: List[LineageEdge]
