# AUTOGENERATED FROM packages/shared-schemas/lineage.schema.json.
# DO NOT EDIT BY HAND. Regenerate with
#   python packages/shared-schemas/scripts/generate_pydantic.py
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict, Field


class LineageNodeKind(str, Enum):
    source = "source"
    claim = "claim"
    methodology = "methodology"
    method_invocation = "method_invocation"
    peer_review = "peer_review"
    revision = "revision"
    drift = "drift"
    calibration = "calibration"
    conclusion = "conclusion"
    publication = "publication"
    citation = "citation"


class LineageNode(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    kind: LineageNodeKind
    label: str
    timestamp: datetime
    summary: str = ""
    payload: Dict[str, Any] = Field(default_factory=dict)
    public_visible: bool = False
    record_url: str = ""


class LineageEdge(BaseModel):
    model_config = ConfigDict(extra="forbid")

    src: str
    dst: str
    relation: str


class Lineage(BaseModel):
    """Provenance graph for a single Conclusion."""

    model_config = ConfigDict(extra="forbid")

    conclusion_id: str
    assembled_at: datetime
    nodes: List[LineageNode] = Field(default_factory=list)
    edges: List[LineageEdge] = Field(default_factory=list)
