# AUTOGENERATED FROM packages/shared-schemas/method_track_record.schema.json.
# DO NOT EDIT BY HAND. Regenerate with
#   python packages/shared-schemas/scripts/generate_pydantic.py
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, Optional

from pydantic import BaseModel, ConfigDict, Field


class MethodTrackRecord(BaseModel):
    """Per-(method, version, domain) track-record row."""

    model_config = ConfigDict(extra="forbid")

    organization_id: str
    method_name: str
    method_version: str
    domain: str
    sample_size: int = Field(ge=0)
    weighted_brier: Optional[float] = None
    calibration_slope: Optional[float] = None
    calibration_slope_ci_low: Optional[float] = None
    calibration_slope_ci_high: Optional[float] = None
    severity_pass_rate: Optional[float] = None
    evidence: Dict[str, Any] = Field(default_factory=dict)
    computed_at: datetime
