# AUTOGENERATED FROM packages/shared-schemas/method_track_record.schema.json.
# DO NOT EDIT BY HAND. Regenerate with
#   python packages/shared-schemas/scripts/generate_pydantic.py
# generated by datamodel-codegen:
#   filename:  method_track_record.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, Optional

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr


class MethodTrackRecord(BaseModel):
    """
    One materialized row from `MethodTrackRecord`. The Prisma model is the canonical column shape on the codex side; this schema is the JSON wire-form used by the noosphere aggregator (noosphere/evaluation/method_track_record.py) and by /methods/<name>/<version>/track-record API responses. `nullable` fields collapse to `null` (not absent) so downstream typed clients don't have to discriminate.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    organization_id: constr(min_length=1)
    method_name: constr(min_length=1)
    method_version: constr(min_length=1)
    domain: str = Field(
        ...,
        description="Empty string means 'no domain label'. Never smoothed across domains.",
    )
    sample_size: conint(ge=0)
    weighted_brier: Optional[float] = None
    calibration_slope: Optional[float] = None
    calibration_slope_ci_low: Optional[float] = None
    calibration_slope_ci_high: Optional[float] = None
    severity_pass_rate: Optional[confloat(ge=0.0, le=1.0)] = None
    evidence: Optional[Dict[str, Any]] = {}
    computed_at: datetime
