# AUTOGENERATED FROM packages/shared-schemas/mqs.schema.json.
# DO NOT EDIT BY HAND. Regenerate with
#   python packages/shared-schemas/scripts/generate_pydantic.py
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class SubScore(BaseModel):
    model_config = ConfigDict(extra="forbid")

    score: float = Field(ge=0.0, le=1.0)
    evidence: Dict[str, Any] = Field(default_factory=dict)


class MethodologyQualityScore(BaseModel):
    """MQS payload shared with the codex storage + render layer."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    schema_: Literal["theseus.mqs.v1"] = Field(
        default="theseus.mqs.v1", alias="schema"
    )
    conclusion_id: str
    progressivity: SubScore
    severity: SubScore
    aim_method_fit: SubScore
    compressibility: SubScore
    domain_sensitivity: SubScore
    composite: float = Field(ge=0.0, le=1.0)
    composite_formula: str = (
        "domain_sensitivity * mean(progressivity, severity, aim_method_fit, compressibility)"
    )
    model_name: str = "stub"
    prompt_version: str = "mqs-prompt-v1.0"
    scored_at: Optional[datetime] = None
