# AUTOGENERATED FROM packages/shared-schemas/mqs.schema.json.
# DO NOT EDIT BY HAND. Regenerate with
#   python packages/shared-schemas/scripts/generate_pydantic.py
# generated by datamodel-codegen:
#   filename:  mqs.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, confloat, constr


class SubScore(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    score: confloat(ge=0.0, le=1.0)
    evidence: Optional[Dict[str, Any]] = {}


class MethodologyQualityScore(BaseModel):
    """
    Methodology Quality Score payload. The scorer lives in noosphere/evaluation/mqs.py (Python is canonical for the computation); this schema is the wire-shape that the codex stores and renders. Composite formula and sub-score semantics are documented in docs/methods/MQS_Specification.md.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Literal["theseus.mqs.v1"] = Field(..., alias="schema")
    conclusion_id: constr(min_length=1)
    progressivity: SubScore
    severity: SubScore
    aim_method_fit: SubScore
    compressibility: SubScore
    domain_sensitivity: SubScore
    composite: confloat(ge=0.0, le=1.0)
    composite_formula: Optional[str] = (
        "domain_sensitivity * mean(progressivity, severity, aim_method_fit, compressibility)"
    )
    model_name: Optional[str] = "stub"
    prompt_version: Optional[str] = "mqs-prompt-v1.0"
    scored_at: Optional[datetime] = None
