# AUTOGENERATED FROM packages/shared-schemas/revision_event.schema.json.
# DO NOT EDIT BY HAND. Regenerate with
#   python packages/shared-schemas/scripts/generate_pydantic.py
# generated by datamodel-codegen:
#   filename:  revision_event.schema.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, confloat, conint, constr


class RevisionInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claim_id: constr(min_length=1)
    new_evidence: str
    weight: confloat(ge=-1.0, le=1.0)


class Classification(Enum):
    changed = "changed"
    newly_contradicted = "newly_contradicted"
    newly_supported = "newly_supported"
    stable = "stable"


class ConfidenceShift(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    conclusion_id: constr(min_length=1)
    before: float
    after: float
    delta: Optional[float] = None
    classification: Classification


class RevisionPlan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    plan_id: constr(min_length=1)
    inputs: List[RevisionInput]
    changed: List[ConfidenceShift]
    newly_contradicted: List[ConfidenceShift]
    newly_supported: List[ConfidenceShift]
    stable_count: conint(ge=0)
    consulted_edge_ids: Optional[List[str]] = []
    delta: float
    theta: float


class RevisionEvent(BaseModel):
    """
    Belief-revision payloads shared between noosphere/cascade/revision.py (canonical algorithm) and theseus-codex/src/lib/revisionApi.ts (UI + persistence). The event row in Prisma stores `inputsJson` / `planJson` / `preConfidenceSnapshot` as TEXT — this schema is what those blobs decode to.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: constr(min_length=1)
    plan_id: constr(min_length=1)
    inputs: List[RevisionInput]
    plan: RevisionPlan
    pre_confidence_snapshot: Dict[str, float]
    affected_conclusion_ids: List[str]
    typed_confirmation: bool
    created_at: datetime
    reverted_at: Optional[datetime] = None
