# AUTOGENERATED FROM packages/shared-schemas/revision_event.schema.json.
# DO NOT EDIT BY HAND. Regenerate with
#   python packages/shared-schemas/scripts/generate_pydantic.py
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class ShiftClassification(str, Enum):
    changed = "changed"
    newly_contradicted = "newly_contradicted"
    newly_supported = "newly_supported"
    stable = "stable"


class RevisionInput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    claim_id: str
    new_evidence: str
    weight: float = Field(ge=-1.0, le=1.0)


class ConfidenceShift(BaseModel):
    model_config = ConfigDict(extra="forbid")

    conclusion_id: str
    before: float
    after: float
    delta: Optional[float] = None
    classification: ShiftClassification


class RevisionPlan(BaseModel):
    model_config = ConfigDict(extra="forbid")

    plan_id: str
    inputs: List[RevisionInput]
    changed: List[ConfidenceShift]
    newly_contradicted: List[ConfidenceShift]
    newly_supported: List[ConfidenceShift]
    stable_count: int = Field(ge=0)
    consulted_edge_ids: List[str] = Field(default_factory=list)
    delta: float
    theta: float


class RevisionEvent(BaseModel):
    """Belief-revision event payload."""

    model_config = ConfigDict(extra="forbid")

    event_id: str
    plan_id: str
    inputs: List[RevisionInput]
    plan: RevisionPlan
    pre_confidence_snapshot: Dict[str, float]
    affected_conclusion_ids: List[str]
    typed_confirmation: bool
    created_at: datetime
    reverted_at: Optional[datetime] = None
