"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import AsciiCanvas from "./AsciiCanvas";
import { CELL_H, CELL_W } from "@/lib/ascii/shapeVectors";

/**
 * Render a classical sculpture as a live amber ASCII object.
 *
 * Input: a compact binary mesh generated by `scripts/process-sculptures.ts`
 *   ─ bytes 0-3   : magic "STA1"
 *   ─ bytes 4-7   : triangle count (uint32 LE)
 *   ─ body        : N triangles × 9 float32 vertices (36 bytes each)
 *
 * Pipeline per frame:
 *   1. Compute yaw from elapsed time (+ optional phase offset so multiple
 *      sculptures on the same page don't spin in lockstep).
 *   2. For each triangle: rotate its three vertices, project to 2D,
 *      compute the post-rotation normal via cross product, skip if
 *      back-facing (orientation-agnostic: we try both winding orders
 *      and keep whichever half of the mesh faces forward most often).
 *   3. Painter's algorithm: sort triangles by centroid depth (far first),
 *      fill each with amber at `max(dot(normal, light), 0)` intensity.
 *   4. Feed the 2D canvas into `AsciiCanvas`, which walks its cells with
 *      the 6D shape-vector picker and produces glyphs.
 *
 * Performance: at the typical mesh size (~2500 triangles) this is
 * ~150k triangle fills per second at 60fps, which the 2D canvas handles
 * well on anything modern. We `paused` the component automatically when
 * the mesh isn't loaded so we don't burn frames over a blank scene.
 */

export type SculptureAsciiProps = {
  /** URL of a .mesh.bin file. Relative to `public/`. */
  src: string;
  cols?: number;
  rows?: number;
  /** Revolutions per second of the Y-axis yaw. Default 0.05 = one rotation every 20s. */
  yawSpeed?: number;
  /** Fixed pitch (radians) so the figure is slightly above / below the viewer. */
  pitch?: number;
  /** Phase offset (radians) so peers can be out of sync. */
  phase?: number;
  /** Upfront scale multiplier on the [-1, 1] normalized mesh. */
  scale?: number;
  /** Canvas color override — resolved via AsciiCanvas helpers. */
  color?: string;
  /**
   * Glyph-cell scale (passed through to AsciiCanvas). Values < 1 shrink
   * the glyphs, giving finer detail at the same physical size — useful
   * for large backdrop sculptures where facial features should be
   * legible. Default 1.0.
   */
  cellScale?: number;
  ariaLabel?: string;
};

/** Cache so we don't re-fetch the same mesh across page navigation. */
const meshCache = new Map<string, Float32Array>();

type Vec3 = readonly [number, number, number];

/** Parse the compact binary into a Float32Array of 9-float triangles. */
function parseMesh(buf: ArrayBuffer): Float32Array {
  const view = new DataView(buf);
  const magic = String.fromCharCode(
    view.getUint8(0),
    view.getUint8(1),
    view.getUint8(2),
    view.getUint8(3),
  );
  if (magic !== "STA1") {
    throw new Error(`Expected STA1 magic, got "${magic}"`);
  }
  const count = view.getUint32(4, true);
  // Re-use the underlying buffer's body as a Float32Array (zero-copy).
  return new Float32Array(buf, 8, count * 9);
}

function slugFromSrc(src: string): string {
  const m = src.match(/\/?([^/?]+)\.mesh\.bin(?:\?.*)?$/);
  return m?.[1] ?? "default";
}

function addTri(out: number[], a: Vec3, b: Vec3, c: Vec3): void {
  out.push(a[0], a[1], a[2], b[0], b[1], b[2], c[0], c[1], c[2]);
}

function addSphere(
  out: number[],
  center: Vec3,
  radius: number,
  latSteps = 8,
  lonSteps = 12,
): void {
  const [cx, cy, cz] = center;
  for (let lat = 0; lat < latSteps; lat++) {
    const t0 = (lat / latSteps) * Math.PI;
    const t1 = ((lat + 1) / latSteps) * Math.PI;
    const y0 = Math.cos(t0) * radius;
    const y1 = Math.cos(t1) * radius;
    const r0 = Math.sin(t0) * radius;
    const r1 = Math.sin(t1) * radius;
    for (let lon = 0; lon < lonSteps; lon++) {
      const p0 = (lon / lonSteps) * Math.PI * 2;
      const p1 = ((lon + 1) / lonSteps) * Math.PI * 2;
      const a: Vec3 = [cx + Math.cos(p0) * r0, cy + y0, cz + Math.sin(p0) * r0];
      const b: Vec3 = [cx + Math.cos(p1) * r0, cy + y0, cz + Math.sin(p1) * r0];
      const c: Vec3 = [cx + Math.cos(p0) * r1, cy + y1, cz + Math.sin(p0) * r1];
      const d: Vec3 = [cx + Math.cos(p1) * r1, cy + y1, cz + Math.sin(p1) * r1];
      if (lat === 0) {
        addTri(out, a, c, d);
      } else if (lat === latSteps - 1) {
        addTri(out, a, d, b);
      } else {
        addTri(out, a, c, d);
        addTri(out, a, d, b);
      }
    }
  }
}

function sub(a: Vec3, b: Vec3): Vec3 {
  return [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
}

function add(a: Vec3, b: Vec3): Vec3 {
  return [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
}

function mul(v: Vec3, s: number): Vec3 {
  return [v[0] * s, v[1] * s, v[2] * s];
}

function cross(a: Vec3, b: Vec3): Vec3 {
  return [
    a[1] * b[2] - a[2] * b[1],
    a[2] * b[0] - a[0] * b[2],
    a[0] * b[1] - a[1] * b[0],
  ];
}

function normalize(v: Vec3): Vec3 {
  const len = Math.hypot(v[0], v[1], v[2]);
  if (len < 1e-6) return [0, 1, 0];
  return [v[0] / len, v[1] / len, v[2] / len];
}

function addCapsule(
  out: number[],
  start: Vec3,
  end: Vec3,
  radius: number,
  radialSegments = 10,
): void {
  const axis = sub(end, start);
  const axisLen = Math.hypot(axis[0], axis[1], axis[2]);
  if (axisLen < 1e-5) return;
  const dir = normalize(axis);
  const seed: Vec3 = Math.abs(dir[1]) < 0.9 ? [0, 1, 0] : [1, 0, 0];
  const u = normalize(cross(dir, seed));
  const v = normalize(cross(dir, u));
  for (let i = 0; i < radialSegments; i++) {
    const a0 = (i / radialSegments) * Math.PI * 2;
    const a1 = ((i + 1) / radialSegments) * Math.PI * 2;
    const r0 = add(mul(u, Math.cos(a0) * radius), mul(v, Math.sin(a0) * radius));
    const r1 = add(mul(u, Math.cos(a1) * radius), mul(v, Math.sin(a1) * radius));
    const s0 = add(start, r0);
    const s1 = add(start, r1);
    const e0 = add(end, r0);
    const e1 = add(end, r1);
    addTri(out, s0, e0, e1);
    addTri(out, s0, e1, s1);
  }
  addSphere(out, start, radius, 5, 8);
  addSphere(out, end, radius, 5, 8);
}

type Pose = {
  pelvis: Vec3;
  neck: Vec3;
  head: Vec3;
  leftShoulder: Vec3;
  rightShoulder: Vec3;
  leftElbow: Vec3;
  rightElbow: Vec3;
  leftHand: Vec3;
  rightHand: Vec3;
  leftHip: Vec3;
  rightHip: Vec3;
  leftKnee: Vec3;
  rightKnee: Vec3;
  leftFoot: Vec3;
  rightFoot: Vec3;
};

const BASE_POSE: Pose = {
  pelvis: [0, 0.05, 0],
  neck: [0, 0.58, 0],
  head: [0, 0.82, 0],
  leftShoulder: [-0.2, 0.56, 0],
  rightShoulder: [0.2, 0.56, 0],
  leftElbow: [-0.34, 0.4, 0],
  rightElbow: [0.34, 0.4, 0],
  leftHand: [-0.34, 0.18, 0.04],
  rightHand: [0.34, 0.18, -0.04],
  leftHip: [-0.13, 0.03, 0],
  rightHip: [0.13, 0.03, 0],
  leftKnee: [-0.13, -0.34, 0.02],
  rightKnee: [0.13, -0.34, -0.02],
  leftFoot: [-0.12, -0.76, 0.08],
  rightFoot: [0.12, -0.76, -0.08],
};

const POSE_OVERRIDES: Record<string, Partial<Pose>> = {
  "discobolus-alt": {
    neck: [0.04, 0.58, -0.1],
    head: [0.1, 0.82, -0.14],
    leftShoulder: [-0.15, 0.55, -0.08],
    rightShoulder: [0.22, 0.58, 0.08],
    leftElbow: [-0.45, 0.63, -0.18],
    rightElbow: [0.36, 0.35, 0.22],
    leftHand: [-0.65, 0.5, -0.28],
    rightHand: [0.48, 0.12, 0.34],
    leftKnee: [-0.18, -0.2, 0.25],
    rightKnee: [0.22, -0.33, -0.2],
    leftFoot: [-0.29, -0.62, 0.42],
    rightFoot: [0.2, -0.74, -0.25],
  },
  discobolus: {
    neck: [0.02, 0.58, -0.05],
    head: [0.06, 0.82, -0.08],
    leftElbow: [-0.42, 0.62, -0.08],
    rightElbow: [0.34, 0.32, 0.18],
    leftHand: [-0.58, 0.48, -0.18],
    rightHand: [0.46, 0.14, 0.28],
    leftKnee: [-0.2, -0.23, 0.12],
    rightKnee: [0.18, -0.32, -0.12],
  },
  doryphoros: {
    pelvis: [-0.02, 0.05, 0],
    neck: [0.03, 0.58, 0.01],
    leftShoulder: [-0.2, 0.56, 0.03],
    rightShoulder: [0.2, 0.56, -0.03],
    leftElbow: [-0.24, 0.35, 0.08],
    rightElbow: [0.33, 0.43, -0.08],
    leftHand: [-0.2, 0.1, 0.15],
    rightHand: [0.36, 0.18, -0.16],
    leftHip: [-0.14, 0.03, 0.03],
    rightHip: [0.14, 0.03, -0.03],
    leftKnee: [-0.08, -0.3, 0.05],
    rightKnee: [0.18, -0.34, -0.08],
    leftFoot: [-0.04, -0.76, 0.2],
    rightFoot: [0.2, -0.76, -0.14],
  },
  hercules: {
    head: [0, 0.85, 0],
    leftShoulder: [-0.24, 0.58, 0],
    rightShoulder: [0.24, 0.58, 0],
    leftElbow: [-0.38, 0.45, -0.05],
    rightElbow: [0.4, 0.43, 0.05],
    leftHand: [-0.4, 0.2, -0.08],
    rightHand: [0.42, 0.2, 0.08],
    leftHip: [-0.15, 0.02, 0],
    rightHip: [0.15, 0.02, 0],
  },
  augustus: {
    neck: [0.02, 0.58, 0.02],
    head: [0.03, 0.83, 0.03],
    leftElbow: [-0.28, 0.36, 0.08],
    leftHand: [-0.24, 0.16, 0.12],
    rightElbow: [0.28, 0.52, -0.1],
    rightHand: [0.44, 0.64, -0.18],
    leftKnee: [-0.1, -0.32, 0.08],
    rightKnee: [0.16, -0.34, -0.02],
  },
  "dying-gladiator": {
    pelvis: [0.03, 0.01, 0.08],
    neck: [0.08, 0.47, -0.16],
    head: [0.14, 0.62, -0.26],
    leftShoulder: [-0.12, 0.46, -0.02],
    rightShoulder: [0.26, 0.5, -0.24],
    leftElbow: [-0.28, 0.28, 0.12],
    rightElbow: [0.5, 0.3, -0.44],
    leftHand: [-0.32, 0.04, 0.2],
    rightHand: [0.62, 0.04, -0.52],
    leftHip: [-0.08, 0.01, 0.2],
    rightHip: [0.15, 0.01, -0.02],
    leftKnee: [-0.28, -0.2, 0.44],
    rightKnee: [0.2, -0.3, -0.18],
    leftFoot: [-0.38, -0.58, 0.58],
    rightFoot: [0.14, -0.7, -0.26],
  },
};

function normalizeMesh(verts: Float32Array): Float32Array {
  if (verts.length === 0) return verts;
  let minX = Infinity;
  let minY = Infinity;
  let minZ = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  let maxZ = -Infinity;
  for (let i = 0; i < verts.length; i += 3) {
    const x = verts[i]!;
    const y = verts[i + 1]!;
    const z = verts[i + 2]!;
    if (x < minX) minX = x;
    if (y < minY) minY = y;
    if (z < minZ) minZ = z;
    if (x > maxX) maxX = x;
    if (y > maxY) maxY = y;
    if (z > maxZ) maxZ = z;
  }
  const cx = (minX + maxX) / 2;
  const cy = (minY + maxY) / 2;
  const cz = (minZ + maxZ) / 2;
  const longest = Math.max(maxX - minX, maxY - minY, maxZ - minZ);
  const s = longest > 0 ? 2 / longest : 1;
  const out = new Float32Array(verts.length);
  for (let i = 0; i < verts.length; i += 3) {
    out[i] = (verts[i]! - cx) * s;
    out[i + 1] = (verts[i + 1]! - cy) * s;
    out[i + 2] = (verts[i + 2]! - cz) * s;
  }
  return out;
}

function buildProceduralStatueMesh(slug: string): Float32Array {
  const pose: Pose = { ...BASE_POSE, ...(POSE_OVERRIDES[slug] ?? {}) };
  const tris: number[] = [];

  addCapsule(tris, pose.neck, pose.pelvis, 0.11, 12);
  addCapsule(tris, pose.leftShoulder, pose.rightShoulder, 0.07, 10);
  addCapsule(tris, pose.leftHip, pose.rightHip, 0.08, 10);
  addSphere(tris, pose.head, 0.13, 9, 12);

  addCapsule(tris, pose.leftShoulder, pose.leftElbow, 0.05, 10);
  addCapsule(tris, pose.leftElbow, pose.leftHand, 0.045, 10);
  addCapsule(tris, pose.rightShoulder, pose.rightElbow, 0.05, 10);
  addCapsule(tris, pose.rightElbow, pose.rightHand, 0.045, 10);

  addCapsule(tris, pose.leftHip, pose.leftKnee, 0.058, 10);
  addCapsule(tris, pose.leftKnee, pose.leftFoot, 0.053, 10);
  addCapsule(tris, pose.rightHip, pose.rightKnee, 0.058, 10);
  addCapsule(tris, pose.rightKnee, pose.rightFoot, 0.053, 10);

  // Discobolus variants get a "disc" so the silhouette reads correctly.
  if (slug.includes("discobolus")) {
    const discCenter = pose.leftHand;
    addSphere(tris, [discCenter[0] - 0.1, discCenter[1] + 0.02, discCenter[2]], 0.1, 4, 10);
  }

  return normalizeMesh(new Float32Array(tris));
}

function fallbackMesh(src: string): Float32Array {
  const slug = slugFromSrc(src);
  const cacheKey = `__procedural__${slug}`;
  const cached = meshCache.get(cacheKey);
  if (cached) return cached;
  const mesh = buildProceduralStatueMesh(slug);
  meshCache.set(cacheKey, mesh);
  return mesh;
}

async function loadMesh(src: string): Promise<Float32Array> {
  const cached = meshCache.get(src);
  if (cached) return cached;
  try {
    const res = await fetch(src);
    if (!res.ok) {
      // Common production failure mode: the `.mesh.bin` files were swept up
      // by a `*.bin` rule in the root `.gitignore` and never deployed.
      // We'll fall back to a procedural mesh so the page still renders.
      throw new Error(
        `Failed to fetch ${src}: HTTP ${res.status}. ` +
          (res.status === 404
            ? "Mesh file not deployed — check .gitignore / .vercelignore for `*.bin` patterns."
            : ""),
      );
    }
    const buf = await res.arrayBuffer();
    const parsed = parseMesh(buf);
    meshCache.set(src, parsed);
    return parsed;
  } catch (err) {
    const generated = fallbackMesh(src);
    meshCache.set(src, generated);
    if (typeof window !== "undefined") {
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(
        `[sculpture] ${src} unavailable (${msg}). Using procedural fallback mesh.`,
      );
    }
    return generated;
  }
}

/** Decide which triangle winding faces the camera "correctly". Museum STL
 *  exports are inconsistent about CCW-vs-CW conventions. We sample a
 *  handful of triangles, count how many would be visible with each
 *  winding assumption, and pick whichever gives more forward-facing
 *  triangles. Done once at load time; cheap, deterministic. */
function detectWinding(mesh: Float32Array): 1 | -1 {
  const triCount = mesh.length / 9;
  const sampleStep = Math.max(1, Math.floor(triCount / 500));
  let forwardCW = 0;
  let forwardCCW = 0;
  for (let i = 0; i < triCount; i += sampleStep) {
    const o = i * 9;
    const ax = mesh[o]!;
    const ay = mesh[o + 1]!;
    const az = mesh[o + 2]!;
    const bx = mesh[o + 3]!;
    const by = mesh[o + 4]!;
    const bz = mesh[o + 5]!;
    const cx = mesh[o + 6]!;
    const cy = mesh[o + 7]!;
    const cz = mesh[o + 8]!;
    // Cross product (B-A) × (C-A), z-component.
    const abx = bx - ax;
    const aby = by - ay;
    const acx = cx - ax;
    const acy = cy - ay;
    const abz = bz - az;
    const acz = cz - az;
    // Full cross for normal z:
    const nz = abx * acy - aby * acx;
    if (nz > 0) forwardCCW++;
    else if (nz < 0) forwardCW++;
    // Silence unused noise
    void abz;
    void acz;
  }
  return forwardCCW >= forwardCW ? 1 : -1;
}

export default function SculptureAscii({
  src,
  cols = 50,
  rows = 22,
  yawSpeed = 0.05,
  pitch = -0.12,
  phase = 0,
  scale = 0.85,
  color = "var(--amber)",
  cellScale = 1.0,
  ariaLabel = "Classical sculpture, rotating",
}: SculptureAsciiProps) {
  const [meshState, setMeshState] = useState<{
    mesh: Float32Array;
    winding: 1 | -1;
  } | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    loadMesh(src)
      .then((mesh) => {
        if (cancelled) return;
        setMeshState({ mesh, winding: detectWinding(mesh) });
      })
      .catch((e) => {
        if (!cancelled) {
          setLoadError(e instanceof Error ? e.message : String(e));
        }
      });
    return () => {
      cancelled = true;
    };
  }, [src]);

  // Scratch arrays for the hot path (avoid GC per frame).
  const scratchRef = useRef<{
    projX: Float32Array;
    projY: Float32Array;
    depth: Float32Array;
    shade: Float32Array;
    visible: Uint8Array;
    order: Int32Array;
  } | null>(null);

  useEffect(() => {
    if (!meshState) return;
    const triCount = meshState.mesh.length / 9;
    scratchRef.current = {
      projX: new Float32Array(triCount * 3),
      projY: new Float32Array(triCount * 3),
      depth: new Float32Array(triCount),
      shade: new Float32Array(triCount),
      visible: new Uint8Array(triCount),
      order: new Int32Array(triCount),
    };
  }, [meshState]);

  // The source canvas that AsciiCanvas hands us in the render
  // callback is sized `cols * CELL_W * cellScale` px by
  // `rows * CELL_H * cellScale` px — cellScale is applied to the
  // pixel buffer, not bypassed. Earlier this line read
  //
  //   const width = cols * CELL_W;
  //   const height = rows * CELL_H;
  //
  // which is the "canonical" canvas size BEFORE cellScale. With
  // cellScale = 0.65 (SculptureBackdrop's default), the projection
  // math below ran at 1.54× the pixel buffer's actual dimensions:
  // `cx = width / 2` landed past the right edge, `cy = height * 0.55`
  // landed well past the bottom, and any figure taller than the
  // real canvas lost its legs to clip-off-bottom. For tall meshes
  // like the Atlas-holding-earth scan (2:1 height:width ratio) the
  // visible result was essentially just the globe — the body was
  // drawn outside the canvas entirely.
  //
  // Applying cellScale here aligns the projection with the actual
  // pixel buffer, so figures always render inside the canvas and
  // their silhouettes sit where the `cy = 0.55 * height` bias
  // intends them to.
  const width = cols * CELL_W * cellScale;
  const height = rows * CELL_H * cellScale;

  const render = useCallback(
    (ctx: CanvasRenderingContext2D, timeMs: number) => {
      ctx.clearRect(0, 0, width, height);
      const state = meshState;
      const scratch = scratchRef.current;
      if (!state || !scratch) return;

      const mesh = state.mesh;
      const winding = state.winding;
      const triCount = mesh.length / 9;

      // ── Transform basis ──────────────────────────────────────────────
      const t = timeMs / 1000;
      const yaw = t * Math.PI * 2 * yawSpeed + phase;
      const cosY = Math.cos(yaw);
      const sinY = Math.sin(yaw);
      const cosP = Math.cos(pitch);
      const sinP = Math.sin(pitch);

      // Light direction (pre-rotated, so the highlit side of the figure
      // doesn't itself rotate as the figure spins). Roughly over the
      // viewer's right shoulder.
      const Lx = 0.45;
      const Ly = 0.75;
      const Lz = 0.5;
      const Llen = Math.hypot(Lx, Ly, Lz);
      const lx = Lx / Llen;
      const ly = Ly / Llen;
      const lz = Lz / Llen;

      const cx = width / 2;
      const cy = height * 0.55; // figures have more mass below their centre; shift a touch down
      const s = Math.min(width, height) * 0.48 * scale;

      const { projX, projY, depth, shade, visible, order } = scratch;

      // ── Pass 1: transform, project, shade, cull ──────────────────────
      let visibleCount = 0;
      for (let i = 0; i < triCount; i++) {
        const o = i * 9;
        // Vertex A
        const ax0 = mesh[o]!;
        const ay0 = mesh[o + 1]!;
        const az0 = mesh[o + 2]!;
        // Vertex B
        const bx0 = mesh[o + 3]!;
        const by0 = mesh[o + 4]!;
        const bz0 = mesh[o + 5]!;
        // Vertex C
        const cx0 = mesh[o + 6]!;
        const cy0 = mesh[o + 7]!;
        const cz0 = mesh[o + 8]!;

        // Rotate Y (yaw), then X (pitch). Same math as the other 3D
        // components in the Codex (Hearth, Scroll, etc.).
        const rotY = (x: number, _y: number, z: number) =>
          [x * cosY + z * sinY, -x * sinY + z * cosY] as const;
        const rotX = (y: number, z: number) =>
          [y * cosP - z * sinP, y * sinP + z * cosP] as const;

        const [ax1, az1] = rotY(ax0, ay0, az0);
        const [bx1, bz1] = rotY(bx0, by0, bz0);
        const [cx1, cz1] = rotY(cx0, cy0, cz0);
        const [ay1, az2] = rotX(ay0, az1);
        const [by1, bz2] = rotX(by0, bz1);
        const [cy1, cz2] = rotX(cy0, cz1);

        // Project (orthographic). Small-amount perspective divide would
        // exaggerate foreshortening unhelpfully at our tiny bbox.
        const pax = cx + ax1 * s;
        const pay = cy - ay1 * s;
        const pbx = cx + bx1 * s;
        const pby = cy - by1 * s;
        const pcx = cx + cx1 * s;
        const pcy = cy - cy1 * s;

        projX[i * 3] = pax;
        projY[i * 3] = pay;
        projX[i * 3 + 1] = pbx;
        projY[i * 3 + 1] = pby;
        projX[i * 3 + 2] = pcx;
        projY[i * 3 + 2] = pcy;

        // Centroid depth (post-rotation z), used for painter's sort.
        depth[i] = (az2 + bz2 + cz2) / 3;

        // Screen-space cross product. Positive magnitude + winding sign
        // gives a cheap normal.z check. We account for detected winding
        // so meshes exported with CW order still render correctly.
        const ex = pbx - pax;
        const ey = pby - pay;
        const fx = pcx - pax;
        const fy = pcy - pay;
        const crossZ = ex * fy - ey * fx;
        const facing = crossZ * winding;
        if (facing <= 0) {
          visible[i] = 0;
          continue;
        }

        // Compute world-space normal (post-rotation) for shading. Edges
        // in 3D (post-transform).
        const e1x = bx1 - ax1;
        const e1y = by1 - ay1;
        const e1z = bz2 - az2;
        const e2x = cx1 - ax1;
        const e2y = cy1 - ay1;
        const e2z = cz2 - az2;
        let nxn = e1y * e2z - e1z * e2y;
        let nyn = e1z * e2x - e1x * e2z;
        let nzn = e1x * e2y - e1y * e2x;
        // Normalize. If degenerate, skip.
        const nlen = Math.hypot(nxn, nyn, nzn);
        if (nlen < 1e-8) {
          visible[i] = 0;
          continue;
        }
        nxn /= nlen;
        nyn /= nlen;
        nzn /= nlen;
        if (winding === -1) {
          nxn = -nxn;
          nyn = -nyn;
          nzn = -nzn;
        }
        // Shading: lambertian + rim light so silhouette edges stay readable
        // when facing directly at the viewer.
        const dot = nxn * lx + nyn * ly + nzn * lz;
        const lambert = Math.max(0, dot);
        const rim = Math.pow(1 - Math.max(0, nzn), 2.5) * 0.35;
        const brightness = Math.min(1, lambert * 0.85 + rim + 0.12);
        shade[i] = brightness;
        visible[i] = 1;
        order[visibleCount++] = i;
      }

      // ── Pass 2: sort visible triangles far-to-near ───────────────────
      const orderView = order.subarray(0, visibleCount);
      // Custom sort using depth lookup; ascending depth (z) then reversed
      // at draw time is equivalent to descending depth.
      // In our convention positive Z is toward the viewer after rotation,
      // so "far" = smaller z. We draw smallest z first.
      Array.prototype.sort.call(orderView, (a: number, b: number) =>
        depth[a]! < depth[b]! ? -1 : depth[a]! > depth[b]! ? 1 : 0,
      );

      // ── Pass 3: rasterize. Fill triangles with amber at shade alpha.
      //    The exact RGB doesn't matter for the ASCII picker — it reads R
      //    as brightness — but we pick a warm amber so any fallback canvas
      //    render (e.g. during AsciiCanvas font-load wait) still looks on-
      //    brand rather than grey.
      for (let k = 0; k < visibleCount; k++) {
        const i = orderView[k]!;
        const pax = projX[i * 3]!;
        const pay = projY[i * 3]!;
        const pbx = projX[i * 3 + 1]!;
        const pby = projY[i * 3 + 1]!;
        const pcx = projX[i * 3 + 2]!;
        const pcy = projY[i * 3 + 2]!;
        const a = shade[i]!;
        ctx.fillStyle = `rgba(255, 210, 140, ${a})`;
        ctx.beginPath();
        ctx.moveTo(pax, pay);
        ctx.lineTo(pbx, pby);
        ctx.lineTo(pcx, pcy);
        ctx.closePath();
        ctx.fill();
      }
    },
    [meshState, pitch, phase, scale, width, height, yawSpeed],
  );

  if (loadError) {
    // Log the full error to the console so it's obvious in DevTools even if
    // the visible fallback is deliberately quiet. The console message is
    // stable enough that "grep the site for 'sculpture load failed'" is a
    // viable debugging lead.
    if (typeof window !== "undefined") {
      console.warn(`[sculpture] ${src} failed: ${loadError}`);
    }
    return (
      <div
        aria-label={ariaLabel}
        title={loadError}
        style={{
          width: width,
          height: height,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          fontFamily: "'IBM Plex Mono', monospace",
          fontSize: "0.7rem",
          color: "var(--ember, #c0392b)",
          letterSpacing: "0.1em",
          textAlign: "center",
          padding: "1rem",
          gap: "0.35rem",
          border: "1px dashed var(--ember, #c0392b)",
          borderRadius: "4px",
        }}
      >
        <span>[ sculpture load failed ]</span>
        <span
          style={{
            color: "var(--parchment-dim, #8b7a5a)",
            fontSize: "0.55rem",
            opacity: 0.8,
          }}
        >
          {src}
        </span>
        <span
          style={{
            color: "var(--parchment-dim, #8b7a5a)",
            fontSize: "0.5rem",
            opacity: 0.6,
            maxWidth: "80%",
          }}
        >
          {loadError.slice(0, 120)}
        </span>
      </div>
    );
  }

  // While the mesh is still loading (typically < 100ms), show an empty
  // canvas sized to match the final render. Previously we relied on an
  // outer `dynamic({ ssr: false })` loading state ("Summoning marble…")
  // but that created a suspend/hydrate tangle in production — with the
  // wrapper removed, this inline placeholder serves the same purpose
  // without the nested-bailout hazard.
  return (
    <AsciiCanvas
      cols={cols}
      rows={rows}
      render={render}
      contrast={2.0}
      color={color}
      cellScale={cellScale}
      paused={!meshState}
      ariaLabel={ariaLabel}
      style={{ display: "flex", justifyContent: "center" }}
    />
  );
}
