"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import AsciiCanvas from "./AsciiCanvas";
import { CELL_H, CELL_W } from "@/lib/ascii/shapeVectors";

/**
 * Render a classical sculpture as a live amber ASCII object.
 *
 * Input: a compact binary mesh generated by `scripts/process-sculptures.ts`
 *   ─ bytes 0-3   : magic "STA1"
 *   ─ bytes 4-7   : triangle count (uint32 LE)
 *   ─ body        : N triangles × 9 float32 vertices (36 bytes each)
 *
 * Pipeline per frame:
 *   1. Compute yaw from elapsed time (+ optional phase offset so multiple
 *      sculptures on the same page don't spin in lockstep).
 *   2. For each triangle: rotate its three vertices, project to 2D,
 *      compute the post-rotation normal via cross product, skip if
 *      back-facing (orientation-agnostic: we try both winding orders
 *      and keep whichever half of the mesh faces forward most often).
 *   3. Painter's algorithm: sort triangles by centroid depth (far first),
 *      fill each with amber at `max(dot(normal, light), 0)` intensity.
 *   4. Feed the 2D canvas into `AsciiCanvas`, which walks its cells with
 *      the 6D shape-vector picker and produces glyphs.
 *
 * Performance: at the typical mesh size (~2500 triangles) this is
 * ~150k triangle fills per second at 60fps, which the 2D canvas handles
 * well on anything modern. We `paused` the component automatically when
 * the mesh isn't loaded so we don't burn frames over a blank scene.
 */

export type SculptureAsciiProps = {
  /** URL of a .mesh.bin file. Relative to `public/`. */
  src: string;
  cols?: number;
  rows?: number;
  /** Revolutions per second of the Y-axis yaw. Default 0.05 = one rotation every 20s. */
  yawSpeed?: number;
  /** Fixed pitch (radians) so the figure is slightly above / below the viewer. */
  pitch?: number;
  /** Phase offset (radians) so peers can be out of sync. */
  phase?: number;
  /** Upfront scale multiplier on the [-1, 1] normalized mesh. */
  scale?: number;
  /** Canvas color override — resolved via AsciiCanvas helpers. */
  color?: string;
  ariaLabel?: string;
};

/** Cache so we don't re-fetch the same mesh across page navigation. */
const meshCache = new Map<string, Float32Array>();

/** Parse the compact binary into a Float32Array of 9-float triangles. */
function parseMesh(buf: ArrayBuffer): Float32Array {
  const view = new DataView(buf);
  const magic = String.fromCharCode(
    view.getUint8(0),
    view.getUint8(1),
    view.getUint8(2),
    view.getUint8(3),
  );
  if (magic !== "STA1") {
    throw new Error(`Expected STA1 magic, got "${magic}"`);
  }
  const count = view.getUint32(4, true);
  // Re-use the underlying buffer's body as a Float32Array (zero-copy).
  return new Float32Array(buf, 8, count * 9);
}

async function loadMesh(src: string): Promise<Float32Array> {
  const cached = meshCache.get(src);
  if (cached) return cached;
  const res = await fetch(src);
  if (!res.ok) {
    // Common production failure mode: the `.mesh.bin` files were swept up
    // by a `*.bin` rule in the root `.gitignore` (or similar) and never
    // deployed. Surface the URL + status clearly so diagnosis doesn't
    // require F12 detective work.
    throw new Error(
      `Failed to fetch ${src}: HTTP ${res.status}. ` +
        (res.status === 404
          ? "Mesh file not deployed — check .gitignore / .vercelignore for `*.bin` patterns."
          : ""),
    );
  }
  const buf = await res.arrayBuffer();
  const parsed = parseMesh(buf);
  meshCache.set(src, parsed);
  return parsed;
}

/** Decide which triangle winding faces the camera "correctly". Museum STL
 *  exports are inconsistent about CCW-vs-CW conventions. We sample a
 *  handful of triangles, count how many would be visible with each
 *  winding assumption, and pick whichever gives more forward-facing
 *  triangles. Done once at load time; cheap, deterministic. */
function detectWinding(mesh: Float32Array): 1 | -1 {
  const triCount = mesh.length / 9;
  const sampleStep = Math.max(1, Math.floor(triCount / 500));
  let forwardCW = 0;
  let forwardCCW = 0;
  for (let i = 0; i < triCount; i += sampleStep) {
    const o = i * 9;
    const ax = mesh[o]!;
    const ay = mesh[o + 1]!;
    const az = mesh[o + 2]!;
    const bx = mesh[o + 3]!;
    const by = mesh[o + 4]!;
    const bz = mesh[o + 5]!;
    const cx = mesh[o + 6]!;
    const cy = mesh[o + 7]!;
    const cz = mesh[o + 8]!;
    // Cross product (B-A) × (C-A), z-component.
    const abx = bx - ax;
    const aby = by - ay;
    const acx = cx - ax;
    const acy = cy - ay;
    const abz = bz - az;
    const acz = cz - az;
    // Full cross for normal z:
    const nz = abx * acy - aby * acx;
    if (nz > 0) forwardCCW++;
    else if (nz < 0) forwardCW++;
    // Silence unused noise
    void abz;
    void acz;
  }
  return forwardCCW >= forwardCW ? 1 : -1;
}

export default function SculptureAscii({
  src,
  cols = 50,
  rows = 22,
  yawSpeed = 0.05,
  pitch = -0.12,
  phase = 0,
  scale = 0.85,
  color = "var(--amber)",
  ariaLabel = "Classical sculpture, rotating",
}: SculptureAsciiProps) {
  const [meshState, setMeshState] = useState<{
    mesh: Float32Array;
    winding: 1 | -1;
  } | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    loadMesh(src)
      .then((mesh) => {
        if (cancelled) return;
        setMeshState({ mesh, winding: detectWinding(mesh) });
      })
      .catch((e) => {
        if (!cancelled) {
          setLoadError(e instanceof Error ? e.message : String(e));
        }
      });
    return () => {
      cancelled = true;
    };
  }, [src]);

  // Scratch arrays for the hot path (avoid GC per frame).
  const scratchRef = useRef<{
    projX: Float32Array;
    projY: Float32Array;
    depth: Float32Array;
    shade: Float32Array;
    visible: Uint8Array;
    order: Int32Array;
  } | null>(null);

  useEffect(() => {
    if (!meshState) return;
    const triCount = meshState.mesh.length / 9;
    scratchRef.current = {
      projX: new Float32Array(triCount * 3),
      projY: new Float32Array(triCount * 3),
      depth: new Float32Array(triCount),
      shade: new Float32Array(triCount),
      visible: new Uint8Array(triCount),
      order: new Int32Array(triCount),
    };
  }, [meshState]);

  const width = cols * CELL_W;
  const height = rows * CELL_H;

  const render = useCallback(
    (ctx: CanvasRenderingContext2D, timeMs: number) => {
      ctx.clearRect(0, 0, width, height);
      const state = meshState;
      const scratch = scratchRef.current;
      if (!state || !scratch) return;

      const mesh = state.mesh;
      const winding = state.winding;
      const triCount = mesh.length / 9;

      // ── Transform basis ──────────────────────────────────────────────
      const t = timeMs / 1000;
      const yaw = t * Math.PI * 2 * yawSpeed + phase;
      const cosY = Math.cos(yaw);
      const sinY = Math.sin(yaw);
      const cosP = Math.cos(pitch);
      const sinP = Math.sin(pitch);

      // Light direction (pre-rotated, so the highlit side of the figure
      // doesn't itself rotate as the figure spins). Roughly over the
      // viewer's right shoulder.
      const Lx = 0.45;
      const Ly = 0.75;
      const Lz = 0.5;
      const Llen = Math.hypot(Lx, Ly, Lz);
      const lx = Lx / Llen;
      const ly = Ly / Llen;
      const lz = Lz / Llen;

      const cx = width / 2;
      const cy = height * 0.55; // figures have more mass below their centre; shift a touch down
      const s = Math.min(width, height) * 0.48 * scale;

      const { projX, projY, depth, shade, visible, order } = scratch;

      // ── Pass 1: transform, project, shade, cull ──────────────────────
      let visibleCount = 0;
      for (let i = 0; i < triCount; i++) {
        const o = i * 9;
        // Vertex A
        const ax0 = mesh[o]!;
        const ay0 = mesh[o + 1]!;
        const az0 = mesh[o + 2]!;
        // Vertex B
        const bx0 = mesh[o + 3]!;
        const by0 = mesh[o + 4]!;
        const bz0 = mesh[o + 5]!;
        // Vertex C
        const cx0 = mesh[o + 6]!;
        const cy0 = mesh[o + 7]!;
        const cz0 = mesh[o + 8]!;

        // Rotate Y (yaw), then X (pitch). Same math as the other 3D
        // components in the Codex (Hearth, Scroll, etc.).
        const rotY = (x: number, _y: number, z: number) =>
          [x * cosY + z * sinY, -x * sinY + z * cosY] as const;
        const rotX = (y: number, z: number) =>
          [y * cosP - z * sinP, y * sinP + z * cosP] as const;

        const [ax1, az1] = rotY(ax0, ay0, az0);
        const [bx1, bz1] = rotY(bx0, by0, bz0);
        const [cx1, cz1] = rotY(cx0, cy0, cz0);
        const [ay1, az2] = rotX(ay0, az1);
        const [by1, bz2] = rotX(by0, bz1);
        const [cy1, cz2] = rotX(cy0, cz1);

        // Project (orthographic). Small-amount perspective divide would
        // exaggerate foreshortening unhelpfully at our tiny bbox.
        const pax = cx + ax1 * s;
        const pay = cy - ay1 * s;
        const pbx = cx + bx1 * s;
        const pby = cy - by1 * s;
        const pcx = cx + cx1 * s;
        const pcy = cy - cy1 * s;

        projX[i * 3] = pax;
        projY[i * 3] = pay;
        projX[i * 3 + 1] = pbx;
        projY[i * 3 + 1] = pby;
        projX[i * 3 + 2] = pcx;
        projY[i * 3 + 2] = pcy;

        // Centroid depth (post-rotation z), used for painter's sort.
        depth[i] = (az2 + bz2 + cz2) / 3;

        // Screen-space cross product. Positive magnitude + winding sign
        // gives a cheap normal.z check. We account for detected winding
        // so meshes exported with CW order still render correctly.
        const ex = pbx - pax;
        const ey = pby - pay;
        const fx = pcx - pax;
        const fy = pcy - pay;
        const crossZ = ex * fy - ey * fx;
        const facing = crossZ * winding;
        if (facing <= 0) {
          visible[i] = 0;
          continue;
        }

        // Compute world-space normal (post-rotation) for shading. Edges
        // in 3D (post-transform).
        const e1x = bx1 - ax1;
        const e1y = by1 - ay1;
        const e1z = bz2 - az2;
        const e2x = cx1 - ax1;
        const e2y = cy1 - ay1;
        const e2z = cz2 - az2;
        let nxn = e1y * e2z - e1z * e2y;
        let nyn = e1z * e2x - e1x * e2z;
        let nzn = e1x * e2y - e1y * e2x;
        // Normalize. If degenerate, skip.
        const nlen = Math.hypot(nxn, nyn, nzn);
        if (nlen < 1e-8) {
          visible[i] = 0;
          continue;
        }
        nxn /= nlen;
        nyn /= nlen;
        nzn /= nlen;
        if (winding === -1) {
          nxn = -nxn;
          nyn = -nyn;
          nzn = -nzn;
        }
        // Shading: lambertian + rim light so silhouette edges stay readable
        // when facing directly at the viewer.
        const dot = nxn * lx + nyn * ly + nzn * lz;
        const lambert = Math.max(0, dot);
        const rim = Math.pow(1 - Math.max(0, nzn), 2.5) * 0.35;
        const brightness = Math.min(1, lambert * 0.85 + rim + 0.12);
        shade[i] = brightness;
        visible[i] = 1;
        order[visibleCount++] = i;
      }

      // ── Pass 2: sort visible triangles far-to-near ───────────────────
      const orderView = order.subarray(0, visibleCount);
      // Custom sort using depth lookup; ascending depth (z) then reversed
      // at draw time is equivalent to descending depth.
      // In our convention positive Z is toward the viewer after rotation,
      // so "far" = smaller z. We draw smallest z first.
      Array.prototype.sort.call(orderView, (a: number, b: number) =>
        depth[a]! < depth[b]! ? -1 : depth[a]! > depth[b]! ? 1 : 0,
      );

      // ── Pass 3: rasterize. Fill triangles with amber at shade alpha.
      //    The exact RGB doesn't matter for the ASCII picker — it reads R
      //    as brightness — but we pick a warm amber so any fallback canvas
      //    render (e.g. during AsciiCanvas font-load wait) still looks on-
      //    brand rather than grey.
      for (let k = 0; k < visibleCount; k++) {
        const i = orderView[k]!;
        const pax = projX[i * 3]!;
        const pay = projY[i * 3]!;
        const pbx = projX[i * 3 + 1]!;
        const pby = projY[i * 3 + 1]!;
        const pcx = projX[i * 3 + 2]!;
        const pcy = projY[i * 3 + 2]!;
        const a = shade[i]!;
        ctx.fillStyle = `rgba(255, 210, 140, ${a})`;
        ctx.beginPath();
        ctx.moveTo(pax, pay);
        ctx.lineTo(pbx, pby);
        ctx.lineTo(pcx, pcy);
        ctx.closePath();
        ctx.fill();
      }
    },
    [meshState, pitch, phase, scale, width, height, yawSpeed],
  );

  if (loadError) {
    // Log the full error to the console so it's obvious in DevTools even if
    // the visible fallback is deliberately quiet. The console message is
    // stable enough that "grep the site for 'sculpture load failed'" is a
    // viable debugging lead.
    if (typeof window !== "undefined") {
      console.warn(`[sculpture] ${src} failed: ${loadError}`);
    }
    return (
      <div
        aria-label={ariaLabel}
        title={loadError}
        style={{
          width: width,
          height: height,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          fontFamily: "'IBM Plex Mono', monospace",
          fontSize: "0.55rem",
          color: "var(--ember)",
          letterSpacing: "0.1em",
          textAlign: "center",
          padding: "1rem",
          gap: "0.35rem",
        }}
      >
        <span>[ sculpture load failed ]</span>
        <span style={{ color: "var(--parchment-dim)", fontSize: "0.5rem" }}>
          {src}
        </span>
      </div>
    );
  }

  return (
    <AsciiCanvas
      cols={cols}
      rows={rows}
      render={render}
      contrast={2.0}
      color={color}
      paused={!meshState}
      ariaLabel={ariaLabel}
      style={{ display: "flex", justifyContent: "center" }}
    />
  );
}
