/* AUTOGENERATED by scripts/generate_api_types.py — do not edit.
 *
 * Source: current_events_api FastAPI app response models.
 * Regenerate with: python scripts/generate_api_types.py
 * CI fails on drift; the pre-commit hook regenerates locally.
 */

export interface PublicCitation {
  id: string;
  source_kind: string;
  source_id: string;
  quoted_span: string;
  retrieval_score: number;
  is_revoked?: boolean;
}

export interface PublicCurrentEvent {
  id: string;
  source: string;
  external_id: string;
  author_handle?: string | null;
  text: string;
  url?: string | null;
  captured_at: string;
  observed_at: string;
  topic_hint?: string | null;
}

export interface PublicOpinion {
  id: string;
  organization_id: string;
  event_id: string;
  stance: string;
  confidence: number;
  headline: string;
  body_markdown: string;
  uncertainty_notes: Array<string>;
  topic_hint: string | null;
  model_name: string;
  generated_at: string;
  revoked_at: string | null;
  abstention_reason: string | null;
  revoked_sources_count: number;
  event: PublicCurrentEvent | null;
  citations: Array<PublicCitation>;
}

export interface PublicSource {
  id: string;
  opinion_id: string;
  source_kind: string;
  source_id: string;
  source_text: string;
  quoted_span: string;
  retrieval_score: number;
  is_revoked: boolean;
  revoked_reason: string | null;
  canonical_path?: string | null;
}
