/* AUTOGENERATED by scripts/generate_api_types.py — do not edit.
 *
 * Source: current_events_api FastAPI app response models.
 * Regenerate with: python scripts/generate_api_types.py
 * CI fails on drift; the pre-commit hook regenerates locally.
 */

export interface DecisionTraceResponse {
  kind: "forecast" | "equity";
  position_id: string;
  market_or_instrument_title: string;
  principles: Array<TracePrincipleRow>;
  citations: Array<TraceCitationRow>;
  signal?: TraceSignalRow | null;
  position: TracePositionRow;
  fill?: TraceFillRow | null;
  resolution?: TraceResolutionRow | null;
  gates: Array<TraceGateResult>;
}

export interface TraceCitationRow {
  source_type: string;
  source_id: string;
  quoted_span: string;
  support_label?: string | null;
}

export interface TraceFillRow {
  exit_price?: number | null;
  exit_at?: string | null;
  realized_pnl_usd?: number | null;
}

export interface TraceGateResult {
  gate_name: string;
  passed: boolean;
  reason: string;
}

export interface TracePositionRow {
  id: string;
  mode: string;
  side: string;
  size: number;
  entry_price: number;
  status: string;
  created_at: string;
}

export interface TracePrincipleRow {
  conclusion_id: string;
  snippet: string;
  weight?: number | null;
}

export interface TraceResolutionRow {
  outcome?: string | null;
  resolved_at?: string | null;
  brier_score?: number | null;
  justification?: string | null;
}

export interface TraceSignalRow {
  id: string;
  headline: string;
  direction_or_side: string;
  rationale?: string | null;
  confidence_low?: number | null;
  confidence_high?: number | null;
}
