/* AUTOGENERATED by scripts/generate_api_types.py — do not edit.
 *
 * Source: current_events_api FastAPI app response models.
 * Regenerate with: python scripts/generate_api_types.py
 * CI fails on drift; the pre-commit hook regenerates locally.
 */

export interface PublicFollowupMessage {
  id: string;
  role: string;
  content: string;
  citations: Array<Record<string, unknown>>;
  created_at: string;
}
