/* AUTOGENERATED by scripts/generate_api_types.py — do not edit.
 *
 * Source: current_events_api FastAPI app response models.
 * Regenerate with: python scripts/generate_api_types.py
 * CI fails on drift; the pre-commit hook regenerates locally.
 */

export interface PublicBet {
  id: string;
  prediction_id: string;
  mode: string;
  exchange: string;
  side: string;
  stake_usd: number;
  entry_price: number;
  exit_price?: number | null;
  status: string;
  settlement_pnl_usd?: number | null;
  created_at: string;
  settled_at?: string | null;
}

export interface PublicForecast {
  id: string;
  market_id: string;
  organization_id: string;
  probability_yes?: number | null;
  confidence_low?: number | null;
  confidence_high?: number | null;
  headline: string;
  reasoning: string;
  status: string;
  abstention_reason?: string | null;
  topic_hint?: string | null;
  model_name: string;
  live_authorized_at?: string | null;
  created_at: string;
  updated_at: string;
  revoked_sources_count: number;
  market?: PublicMarket | null;
  citations: Array<PublicForecastCitation>;
  resolution?: PublicResolution | null;
}

export interface PublicForecastCitation {
  id: string;
  prediction_id: string;
  source_type: string;
  source_id: string;
  quoted_span: string;
  support_label: string;
  retrieval_score?: number | null;
  is_revoked?: boolean;
}

export interface PublicForecastSource {
  id: string;
  prediction_id: string;
  source_type: string;
  source_id: string;
  source_text: string;
  quoted_span: string;
  support_label: string;
  retrieval_score?: number | null;
  is_revoked: boolean;
  revoked_reason?: string | null;
  canonical_path?: string | null;
}

export interface PublicMarket {
  id: string;
  organization_id: string;
  source: string;
  external_id: string;
  title: string;
  description?: string | null;
  resolution_criteria?: string | null;
  category?: string | null;
  current_yes_price?: number | null;
  current_no_price?: number | null;
  volume?: number | null;
  open_time?: string | null;
  close_time?: string | null;
  resolved_at?: string | null;
  resolved_outcome?: string | null;
  raw_payload: Record<string, unknown>;
  status: string;
  created_at: string;
  updated_at: string;
}

export interface PublicResolution {
  id: string;
  prediction_id: string;
  market_outcome: string;
  brier_score?: number | null;
  log_loss?: number | null;
  calibration_bucket?: number | null;
  resolved_at: string;
  justification: string;
  created_at: string;
}
