/* AUTOGENERATED by scripts/generate_api_types.py — do not edit.
 *
 * Source: current_events_api FastAPI app response models.
 * Regenerate with: python scripts/generate_api_types.py
 * CI fails on drift; the pre-commit hook regenerates locally.
 */

export interface OracleAnswer {
  question: string;
  sources: Array<OracleSource>;
  active_provenance_kinds: Array<string>;
  active_weights: Record<string, number>;
  total_sources_considered: number;
}

export interface OracleSource {
  id: string;
  title: string;
  provenance: string;
  weight: number;
}

export interface ProvenanceCount {
  provenance: string;
  count: number;
}
