/* AUTOGENERATED by scripts/generate_api_types.py — do not edit.
 *
 * Source: current_events_api FastAPI app response models.
 * Regenerate with: python scripts/generate_api_types.py
 * CI fails on drift; the pre-commit hook regenerates locally.
 */

export interface EquityCurvePoint {
  ts: string;
  paper_pnl_usd: number;
}

export interface EquityOpenPosition {
  position_id: string;
  signal_id: string;
  instrument_symbol: string;
  instrument_name?: string | null;
  side: string;
  qty: number;
  entry_price: number;
  entry_at: string;
  unrealized_pnl_usd?: number | null;
  horizon_days?: number | null;
  direction: string;
  last_updated: string;
}

export interface EquityPortfolioSurface {
  organization_id: string;
  paper_balance_usd: number;
  totals: TrackTotals;
  live_status: LiveStatusPills;
  kill_switch_engaged: boolean;
  kill_switch_reason?: string | null;
  open_positions: Array<EquityOpenPosition>;
  recent_signals: Array<EquityRecentSignal>;
  paper_pnl_curve: Array<EquityCurvePoint>;
  target_price_mape: Array<MapeBucket>;
}

export interface EquityRecentSignal {
  signal_id: string;
  instrument_symbol: string;
  direction: string;
  headline: string;
  confidence_low: number;
  confidence_high: number;
  target_price_low?: number | null;
  target_price_high?: number | null;
  horizon_days: number;
  status: string;
  created_at: string;
}

export interface LiveStatusPills {
  forecasts: string;
  equities: string;
}

export interface MapeBucket {
  horizon_label: string;
  n: number;
  mean_absolute_pct_error?: number | null;
}

export interface TrackTotals {
  open_positions: number;
  realized_paper_pnl_usd: number;
  unrealized_paper_pnl_usd: number;
}
