/* AUTOGENERATED by scripts/generate_api_types.py — do not edit.
 *
 * Source: current_events_api FastAPI app response models.
 * Regenerate with: python scripts/generate_api_types.py
 * CI fails on drift; the pre-commit hook regenerates locally.
 */

export interface ActivePrinciple {
  conclusion_id: string;
  snippet: string;
  weight: number;
  position_count: number;
}

export interface CalibrationBucket {
  bucket: number;
  prediction_count: number;
  resolved_count: number;
  mean_probability_yes?: number | null;
  empirical_yes_rate?: number | null;
  mean_brier?: number | null;
}

export interface GateBannerState {
  mode: string;
  live_trading_enabled: boolean;
  failed_gates: Array<TraceGateResult>;
}

export interface LiveStatusPills {
  forecasts: string;
  equities: string;
}

export interface PipelineCandidate {
  market_id: string;
  market_title: string;
  market_url?: string | null;
  source: string;
  category?: string | null;
  driving_principles: Array<TracePrinciple>;
  gate_results: Array<TraceGateResult>;
  gate_state: string;
  last_updated: string;
}

export interface PortfolioPoint {
  ts: string;
  paper_balance_usd: number;
  paper_pnl_usd: number;
}

export interface PortfolioPosition {
  bet_id: string;
  prediction_id: string;
  mode: string;
  market_title: string;
  market_url?: string | null;
  side: string;
  size_usd: number;
  avg_price: number;
  current_implied_prob?: number | null;
  driving_principles: Array<TracePrinciple>;
  gate_results: Array<TraceGateResult>;
  last_updated: string;
}

export interface PortfolioSummary {
  organization_id: string;
  paper_balance_usd: number;
  paper_pnl_curve: Array<PortfolioPoint>;
  calibration: Array<CalibrationBucket>;
  mean_brier_90d?: number | null;
  total_bets: number;
  kill_switch_engaged: boolean;
  kill_switch_reason?: string | null;
  updated_at?: string | null;
}

export interface PortfolioSurface {
  summary: PortfolioSummary;
  gate_banner: GateBannerState;
  open_positions: Array<PortfolioPosition>;
  recently_resolved: Array<ResolvedPortfolioPosition>;
  pipeline: Array<PipelineCandidate>;
  watching: WatchingSummary;
}

export interface PublicBet {
  id: string;
  prediction_id: string;
  mode: string;
  exchange: string;
  side: string;
  stake_usd: number;
  entry_price: number;
  exit_price?: number | null;
  status: string;
  settlement_pnl_usd?: number | null;
  created_at: string;
  settled_at?: string | null;
}

export interface PublicWatchedMarket {
  id: string;
  source: string;
  url: string;
  external_id?: string | null;
  status: string;
  created_at: string;
  last_considered_at?: string | null;
}

export interface ResolvedPortfolioPosition {
  bet_id: string;
  prediction_id: string;
  market_title: string;
  market_url?: string | null;
  outcome: string;
  our_side: string;
  pnl_usd?: number | null;
  reasoning_href: string;
  resolved_at?: string | null;
}

export interface TraceGateResult {
  gate_name: string;
  passed: boolean;
  reason: string;
}

export interface TracePrinciple {
  conclusion_id: string;
  weight: number;
  snippet: string;
}

export interface TrackTotals {
  open_positions: number;
  realized_paper_pnl_usd: number;
  unrealized_paper_pnl_usd: number;
}

export interface UnifiedPortfolioOverview {
  organization_id: string;
  paper_balance_usd: number;
  paper_pnl_curve: Array<PortfolioPoint>;
  calibration: Array<CalibrationBucket>;
  mean_brier_90d?: number | null;
  total_bets: number;
  kill_switch_engaged: boolean;
  kill_switch_reason?: string | null;
  updated_at?: string | null;
  net_paper_pnl_usd: number;
  net_paper_pnl_curve: Array<PortfolioPoint>;
  forecasts: TrackTotals;
  equities: TrackTotals;
  live_status: LiveStatusPills;
  active_principles: Array<ActivePrinciple>;
}

export interface WatchingSummary {
  polymarket_categories: Array<string>;
  kalshi_categories: Array<string>;
  watched_markets: Array<PublicWatchedMarket>;
  scanned_this_week: number;
}
