"""Tests for the public calibration scorecard.

Tolerance contract for the binned plot: when the synthetic outcomes are
generated by drawing each ``y_i ~ Bernoulli(p_i)`` from the same
``p_i`` we feed into the bins, the per-bin observed frequency must
agree with ``mean_predicted`` within ``BIN_TOLERANCE`` for every bin
that has at least ``SPARSE_BIN_THRESHOLD`` samples. Sparse bins are
exempt because the page surfaces them as such.
"""

from __future__ import annotations

import json
import math
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

from noosphere.coherence.calibration import (
    SPARSE_BIN_THRESHOLD,
    binned_reliability_curve,
)
from noosphere.evaluation.public_calibration import (
    PUBLIC_CALIBRATION_SCHEMA,
    PUBLIC_CALIBRATION_SCHEMA_VERSION,
    CalibrationFilter,
    ResolvedForecastRow,
    build_manifest,
    canonicalize_resolution_set,
    decile_extremes,
    hash_resolution_set,
    manifest_to_json,
    publish_manifest,
)


BIN_TOLERANCE = 0.10  # absolute, on per-bin observed frequency vs mean_predicted
BIG_N = 4_000  # enough samples per bin to make the bootstrap mean tight


def _synthetic_rows(
    *,
    n: int,
    seed: int,
    domain: str = "forecasting",
    method: tuple[str, str] | None = ("six_layer_coherence", "v1"),
    base_time: datetime | None = None,
    binary: bool = True,
    perfect: bool = True,
) -> list[ResolvedForecastRow]:
    """Generate ``n`` resolved forecasts with known calibration.

    ``perfect=True`` draws ``y_i ~ Bernoulli(p_i)`` so the binned plot
    converges on the diagonal. ``perfect=False`` deliberately mis-calibrates
    by always answering YES at probability 0.7, so the bottom-decile test
    has obvious losers.
    """
    rng = random.Random(seed)
    base_time = base_time or datetime(2026, 1, 1, tzinfo=timezone.utc)
    rows: list[ResolvedForecastRow] = []
    for i in range(n):
        p = rng.random()
        if perfect:
            outcome = "YES" if rng.random() < p else "NO"
        else:
            p = 0.7
            outcome = "NO" if i % 2 == 0 else "YES"  # 50% accurate vs claimed 70%
        y = 1.0 if outcome == "YES" else 0.0
        brier = (p - y) ** 2
        log_loss = -(
            y * math.log(max(p, 1e-9)) + (1.0 - y) * math.log(max(1.0 - p, 1e-9))
        )
        method_name, method_version = method or (None, None)
        published_at = base_time - timedelta(days=rng.randint(1, 200))
        resolved_at = published_at + timedelta(days=rng.randint(1, 30))
        rows.append(
            ResolvedForecastRow(
                prediction_id=f"pred_{i:06d}_{seed}",
                market_id=f"mkt_{i:06d}",
                headline=f"Headline {i}",
                market_title=f"Market {i}",
                market_url=None,
                domain=domain,
                method_name=method_name,
                method_version=method_version,
                probability_yes=p,
                outcome=outcome,
                brier=brier,
                log_loss=log_loss,
                resolved_at=resolved_at,
                published_at=published_at,
                status="PUBLISHED",
                revoked=False,
                is_continuous=not binary,
            )
        )
    return rows


def test_binned_plot_matches_known_calibration_within_tolerance() -> None:
    rows = _synthetic_rows(n=BIG_N, seed=11)
    bins = binned_reliability_curve(
        [float(r.probability_yes) for r in rows],  # type: ignore[arg-type]
        [1.0 if r.outcome == "YES" else 0.0 for r in rows],
        n_bins=10,
        bootstrap_iters=100,
        seed=42,
    )
    measured: list[tuple[float, float, int]] = []
    for b in bins:
        if b.n >= SPARSE_BIN_THRESHOLD and b.observed_frequency is not None and b.mean_predicted is not None:
            measured.append((b.mean_predicted, b.observed_frequency, b.n))
            assert abs(b.observed_frequency - b.mean_predicted) <= BIN_TOLERANCE, (
                f"bin [{b.lo:.2f}, {b.hi:.2f}] off-diagonal: "
                f"predicted={b.mean_predicted:.3f} observed={b.observed_frequency:.3f}"
            )
    assert len(measured) >= 7, "expected most bins populated at n=4000"


def test_sparse_bins_have_no_ci_and_are_flagged() -> None:
    # Pile most samples on the high end so the low bins are sparse.
    rng = random.Random(7)
    rows = []
    base = datetime(2026, 1, 1, tzinfo=timezone.utc)
    for i in range(50):
        p = 0.85 + rng.random() * 0.15
        outcome = "YES" if rng.random() < p else "NO"
        rows.append(
            ResolvedForecastRow(
                prediction_id=f"p{i}",
                market_id=f"m{i}",
                headline="h",
                market_title="m",
                market_url=None,
                domain="d",
                method_name=None,
                method_version=None,
                probability_yes=p,
                outcome=outcome,
                brier=(p - (1.0 if outcome == "YES" else 0.0)) ** 2,
                log_loss=None,
                resolved_at=base,
                published_at=base - timedelta(days=10),
                status="PUBLISHED",
                revoked=False,
            )
        )
    # Add a single low-probability call so the lowest bin is non-empty but sparse.
    rows.append(
        ResolvedForecastRow(
            prediction_id="lone",
            market_id="m_lone",
            headline="h",
            market_title="m",
            market_url=None,
            domain="d",
            method_name=None,
            method_version=None,
            probability_yes=0.05,
            outcome="NO",
            brier=0.0025,
            log_loss=None,
            resolved_at=base,
            published_at=base - timedelta(days=10),
            status="PUBLISHED",
            revoked=False,
        )
    )
    manifest = build_manifest(rows, now=base + timedelta(days=1))
    sparse_bins = [b for b in manifest.calibration_curve if b["n"] > 0 and b["sparse"]]
    assert sparse_bins, "expected at least one sparse, non-empty bin"
    for b in sparse_bins:
        assert b["ci_low"] is None and b["ci_high"] is None
    assert any("sparse" in note for note in manifest.notes)


def test_resolution_set_hash_is_stable_and_changes_with_data() -> None:
    rows = _synthetic_rows(n=20, seed=3)
    h1 = hash_resolution_set(rows)
    h2 = hash_resolution_set(list(reversed(rows)))  # canonical sort makes order irrelevant
    assert h1 == h2
    canon1 = canonicalize_resolution_set(rows)
    assert isinstance(canon1, str) and canon1.startswith("[")

    # Mutate one prediction and the hash must change.
    mutated = list(rows)
    bad = mutated[0]
    mutated[0] = ResolvedForecastRow(
        prediction_id=bad.prediction_id,
        market_id=bad.market_id,
        headline=bad.headline,
        market_title=bad.market_title,
        market_url=bad.market_url,
        domain=bad.domain,
        method_name=bad.method_name,
        method_version=bad.method_version,
        probability_yes=0.999 if (bad.probability_yes or 0) < 0.999 else 0.001,
        outcome=bad.outcome,
        brier=bad.brier,
        log_loss=bad.log_loss,
        resolved_at=bad.resolved_at,
        published_at=bad.published_at,
        status=bad.status,
        revoked=bad.revoked,
    )
    h3 = hash_resolution_set(mutated)
    assert h3 != h1


def test_withdrawn_excluded_from_metrics_but_counted_in_rate() -> None:
    rows = _synthetic_rows(n=100, seed=5)
    # Mark 10 of the rows as withdrawn (revoked at the conclusion level).
    for i in range(10):
        bad = rows[i]
        rows[i] = ResolvedForecastRow(
            prediction_id=bad.prediction_id,
            market_id=bad.market_id,
            headline=bad.headline,
            market_title=bad.market_title,
            market_url=bad.market_url,
            domain=bad.domain,
            method_name=bad.method_name,
            method_version=bad.method_version,
            probability_yes=bad.probability_yes,
            outcome=bad.outcome,
            brier=bad.brier,
            log_loss=bad.log_loss,
            resolved_at=bad.resolved_at,
            published_at=bad.published_at,
            status=bad.status,
            revoked=True,
        )
    manifest = build_manifest(rows, now=datetime(2026, 6, 1, tzinfo=timezone.utc))
    assert manifest.counts["withdrawn"] == 10
    assert manifest.counts["resolved_binary"] == 90
    assert manifest.withdrawn_rate is not None
    assert abs(manifest.withdrawn_rate - 0.10) < 1e-9
    # Withdrawn rows are excluded from the integrity hash by construction.
    assert all(r.prediction_id not in canonicalize_resolution_set(rows[:10]) for r in rows[:10])


def test_stale_unresolved_are_flagged_not_dropped() -> None:
    base = datetime(2026, 6, 1, tzinfo=timezone.utc)
    rows = _synthetic_rows(n=10, seed=9, base_time=base)
    # Add an unresolved prediction published 30 days ago.
    rows.append(
        ResolvedForecastRow(
            prediction_id="pred_stale",
            market_id="mkt_stale",
            headline="Stale call",
            market_title="Stale",
            market_url=None,
            domain="forecasting",
            method_name=None,
            method_version=None,
            probability_yes=0.5,
            outcome=None,
            brier=None,
            log_loss=None,
            resolved_at=None,
            published_at=base - timedelta(days=30),
            status="PUBLISHED",
            revoked=False,
        )
    )
    manifest = build_manifest(rows, now=base)
    assert manifest.counts["stale_unresolved"] == 1
    assert manifest.counts["resolved_binary"] == 10
    assert any("stale" in note for note in manifest.notes)


def test_decile_extremes_pull_from_binary_resolved_only() -> None:
    rows = _synthetic_rows(n=120, seed=2, perfect=False)
    best, worst = decile_extremes(rows, k=5)
    assert len(best) == 5 and len(worst) == 5
    # Worst Brier >= best Brier for any pair.
    assert worst[0].brier >= best[0].brier
    # Top-decile entries strictly resolved + binary.
    for entry in best + worst:
        assert entry.outcome in {"YES", "NO"}


def test_filter_method_and_domain_drives_per_method_drilldown() -> None:
    rows = _synthetic_rows(n=80, seed=4, method=("six_layer_coherence", "v1"))
    rows += _synthetic_rows(
        n=80,
        seed=44,
        method=("contradiction_probe", "v2"),
        domain="policy",
    )
    full = build_manifest(rows, now=datetime(2026, 6, 1, tzinfo=timezone.utc))
    assert {(m["name"], m["version"]) for m in full.methods} == {
        ("six_layer_coherence", "v1"),
        ("contradiction_probe", "v2"),
    }
    drill = build_manifest(
        rows,
        now=datetime(2026, 6, 1, tzinfo=timezone.utc),
        filt=CalibrationFilter(method_name="contradiction_probe", method_version="v2"),
    )
    assert drill.counts["resolved_binary"] == 80
    # The drill-down hash differs from the unfiltered one.
    assert drill.resolution_set_hash != full.resolution_set_hash


def test_publish_manifest_is_idempotent(tmp_path: Path) -> None:
    rows = _synthetic_rows(n=40, seed=8)
    now = datetime(2026, 6, 1, tzinfo=timezone.utc)
    m1 = build_manifest(rows, now=now)
    out = tmp_path / "manifest.json"
    p1 = publish_manifest(m1, path=out)
    bytes1 = p1.read_bytes()
    # Re-running with the same rows must produce identical bytes when
    # ``generated_at`` is held fixed (we hold it via the ``now`` argument).
    p2 = publish_manifest(m1, path=out)
    bytes2 = p2.read_bytes()
    assert bytes1 == bytes2
    parsed = json.loads(bytes1.decode("utf-8"))
    assert parsed["schema"] == PUBLIC_CALIBRATION_SCHEMA
    assert parsed["schema_version"] == PUBLIC_CALIBRATION_SCHEMA_VERSION
    assert parsed["resolution_set_hash"] == m1.resolution_set_hash


def test_continuous_market_uses_quadratic_loss_not_brier() -> None:
    binary = _synthetic_rows(n=20, seed=1, binary=True)
    cont = _synthetic_rows(n=20, seed=2, binary=False)
    # Override Brier on continuous rows to a known constant so the test can
    # assert the alternative metric is the one being averaged.
    cont = [
        ResolvedForecastRow(**{**r.__dict__, "brier": 0.25, "is_continuous": True})
        for r in cont
    ]
    manifest = build_manifest(binary + cont, now=datetime(2026, 6, 1, tzinfo=timezone.utc))
    assert manifest.continuous_quadratic_loss is not None
    assert abs(manifest.continuous_quadratic_loss - 0.25) < 1e-9
    assert manifest.continuous_metric_name == "quadratic_loss"


def test_manifest_json_is_canonical() -> None:
    rows = _synthetic_rows(n=8, seed=12)
    m = build_manifest(rows, now=datetime(2026, 6, 1, tzinfo=timezone.utc))
    text = manifest_to_json(m)
    parsed = json.loads(text)
    # No whitespace and stable key order — important for hashing the manifest itself.
    assert "  " not in text
    assert ", " not in text
    assert parsed["schema"] == PUBLIC_CALIBRATION_SCHEMA
