"""Type-contract tests for the cross-language shared schemas.

For each shared concept the test:

  1. Loads the golden fixture from
     ``packages/shared-schemas/fixtures/golden.json``.
  2. Validates the payload against its JSON Schema (the source of truth
     for what the wire-form must look like).
  3. Parses the payload through the generated Pydantic model.
  4. Round-trips it through ``.model_dump()`` and confirms the output
     re-validates against the same schema.

The companion test on the codex side
(``theseus-codex/src/__tests__/type-contracts.test.ts``) consumes the
same fixture so the two sides cannot drift independently.

`jsonschema` is a transitive dependency via several deps already in the
repo; this test will skip rather than fail if neither it nor a pure
attribute check is available, so the contract is enforced wherever the
toolchain is fully installed (CI workflow installs both extras).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_DIR = REPO_ROOT / "packages" / "shared-schemas"
FIXTURE = SCHEMA_DIR / "fixtures" / "golden.json"

# Import the generated Pydantic models. We import lazily inside helpers so a
# missing `_generated/` tree fails one test rather than collection.


def _load_golden() -> dict[str, Any]:
    return json.loads(FIXTURE.read_text())


def _load_schema(stem: str) -> dict[str, Any]:
    return json.loads((SCHEMA_DIR / f"{stem}.schema.json").read_text())


def _validate(stem: str, payload: dict[str, Any]) -> None:
    """Validate payload against the JSON Schema, skipping the test if the
    `jsonschema` package is not installed in the test environment."""
    try:
        import jsonschema  # type: ignore[import-not-found]
    except ImportError:  # pragma: no cover — handled via skip
        pytest.skip("jsonschema not installed")
    jsonschema.validate(payload, _load_schema(stem))


def test_conclusion_contract() -> None:
    from noosphere._generated import Conclusion

    payload = _load_golden()["conclusion"]
    _validate("conclusion", payload)
    model = Conclusion.model_validate(payload)
    assert model.id == "conc_01"
    assert 0.0 <= model.confidence <= 1.0
    # Round-trip back to JSON and re-validate.
    _validate("conclusion", model.model_dump(mode="json", exclude_none=False))


def test_mqs_contract() -> None:
    from noosphere._generated import Mqs

    payload = _load_golden()["mqs"]
    _validate("mqs", payload)
    model = Mqs.model_validate(payload)
    assert model.conclusion_id == "conc_01"
    assert 0.0 <= model.composite <= 1.0
    _validate(
        "mqs",
        model.model_dump(mode="json", by_alias=True, exclude_none=False),
    )


def test_method_track_record_contract() -> None:
    from noosphere._generated import MethodTrackRecord

    payload = _load_golden()["method_track_record"]
    _validate("method_track_record", payload)
    model = MethodTrackRecord.model_validate(payload)
    assert model.sample_size >= 0
    assert model.domain == "macro"
    _validate(
        "method_track_record",
        model.model_dump(mode="json", exclude_none=False),
    )


def test_revision_event_contract() -> None:
    from noosphere._generated import RevisionEvent

    payload = _load_golden()["revision_event"]
    _validate("revision_event", payload)
    model = RevisionEvent.model_validate(payload)
    assert model.event_id == "rev_evt_42"
    for inp in model.inputs:
        assert -1.0 <= inp.weight <= 1.0
    _validate(
        "revision_event",
        model.model_dump(mode="json", exclude_none=False),
    )


def test_citation_verdict_contract() -> None:
    from noosphere._generated import CitationVerdict

    payload = _load_golden()["citation_verdict"]
    _validate("citation_verdict", payload)
    model = CitationVerdict.model_validate(payload)
    assert model.relation_holds.value == "entails"
    _validate(
        "citation_verdict",
        model.model_dump(mode="json", exclude_none=False),
    )


def test_lineage_contract() -> None:
    from noosphere._generated import Lineage

    payload = _load_golden()["lineage"]
    _validate("lineage", payload)
    model = Lineage.model_validate(payload)
    node_ids = {n.id for n in model.nodes}
    for edge in model.edges:
        assert edge.src in node_ids
        assert edge.dst in node_ids
    _validate(
        "lineage",
        model.model_dump(mode="json", exclude_none=False),
    )


def test_generated_tree_carries_autogen_banner() -> None:
    """Spot-check that every file under noosphere/_generated/ marks itself
    autogenerated. The CI workflow enforces this more strictly; this is
    the cheap in-process version."""
    gen_dir = REPO_ROOT / "noosphere" / "noosphere" / "_generated"
    for path in gen_dir.glob("*.py"):
        if path.name == "__init__.py":
            continue
        assert "AUTOGENERATED" in path.read_text(), path
