import type { CSSProperties, ReactNode } from "react";

export const metadata = { title: "Current events — Theseus" };

const containerStyle: CSSProperties = {
  maxWidth: "1040px",
  margin: "0 auto",
  paddingLeft: "1.25rem",
  paddingRight: "1.25rem",
};

export default function CurrentsLayout({ children }: { children: ReactNode }) {
  return (
    <div
      style={{
        background: "var(--currents-bg)",
        minHeight: "100vh",
        color: "var(--currents-parchment)",
        paddingBottom: "4rem",
      }}
    >
      <header
        style={{
          padding: "2rem 0 1rem",
          borderBottom: "1px solid var(--currents-border)",
        }}
      >
        <div style={containerStyle}>
          <div
            style={{
              fontSize: "0.75rem",
              letterSpacing: "0.16em",
              textTransform: "uppercase",
              color: "var(--currents-amber)",
            }}
          >
            Theseus · live
          </div>
          <h1
            style={{
              fontFamily: "'EB Garamond', serif",
              fontSize: "1.85rem",
              margin: "0.4rem 0 0.2rem",
            }}
          >
            Current events, source-grounded.
          </h1>
          <p
            style={{
              color: "var(--currents-parchment-dim)",
              maxWidth: "60ch",
              margin: 0,
              fontSize: "0.95rem",
            }}
          >
            The firm reads the news and opines from its published Noosphere.
            Every claim links back to a verbatim source. When the sources don't
            support a position, the firm abstains.
          </p>
        </div>
      </header>
      <div style={{ ...containerStyle, paddingTop: "1.6rem" }}>
        {children}
        <footer
          style={{
            marginTop: "3rem",
            paddingTop: "1.1rem",
            borderTop: "1px solid var(--currents-border)",
            fontSize: "0.78rem",
            lineHeight: 1.6,
            color: "var(--currents-parchment-dim)",
            fontStyle: "italic",
          }}
        >
          <p style={{ margin: 0, maxWidth: "52em" }}>
            Opinions on this page are generated by Claude Haiku 4.5 from the firm's
            published Noosphere of conclusions and claims. They are not editorial
            commentary, not legal or financial advice, and not an exhaustive survey
            of the firm's thinking. The firm abstains from opining when its sources
            do not support a position; an abstention is not agreement with the
            observed event. Citations link to verbatim source passages; when a
            source is revoked, dependent opinions are marked accordingly. Follow-up
            answers re-retrieve from the Noosphere on each question — the assistant
            does not answer from memory.
          </p>
        </footer>
      </div>
    </div>
  );
}
