/**
 * Type-contract tests for the cross-language shared schemas.
 *
 * Each test loads the golden fixture from `packages/shared-schemas/fixtures/`,
 * asserts that the JSON payload is structurally assignable to the generated
 * TS type for that schema, and round-trips it through JSON.parse/stringify
 * to confirm the wire-form survives unchanged. The companion test on the
 * Python side (`noosphere/tests/test_type_contracts.py`) reads the same
 * fixture and verifies the Pydantic side accepts identical bytes.
 *
 * If either side stops accepting the fixture, the fix is to update the JSON
 * schema and regenerate both targets — never edit one type by hand.
 */

import { readFileSync } from "node:fs";
import * as path from "node:path";

import { describe, expect, it } from "vitest";

import type {
  CitationVerdict,
  Conclusion,
  Lineage,
  MethodTrackRecord,
  MethodologyQualityScore,
  RevisionEvent,
} from "@/lib/_generated";

const FIXTURE_PATH = path.resolve(
  __dirname,
  "..",
  "..",
  "..",
  "packages",
  "shared-schemas",
  "fixtures",
  "golden.json",
);

interface Golden {
  conclusion: Conclusion;
  mqs: MethodologyQualityScore;
  method_track_record: MethodTrackRecord;
  revision_event: RevisionEvent;
  citation_verdict: CitationVerdict;
  lineage: Lineage;
}

function loadGolden(): Golden {
  return JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Golden;
}

describe("shared-schemas type contracts", () => {
  const golden = loadGolden();

  it("Conclusion fixture matches the generated TS shape", () => {
    const c: Conclusion = golden.conclusion;
    expect(c.id).toBe("conc_01");
    expect(c.confidence).toBeGreaterThanOrEqual(0);
    expect(c.confidence).toBeLessThanOrEqual(1);
    expect(c.kind).toBe("firm");
    // Round-trip through JSON to confirm there are no parser-only fields.
    expect(JSON.parse(JSON.stringify(c))).toEqual(c);
  });

  it("MQS fixture matches the generated TS shape", () => {
    const m: MethodologyQualityScore = golden.mqs;
    expect(m.schema).toBe("theseus.mqs.v1");
    expect(m.progressivity.score).toBeGreaterThanOrEqual(0);
    expect(m.composite).toBeLessThanOrEqual(1);
    expect(JSON.parse(JSON.stringify(m))).toEqual(m);
  });

  it("MethodTrackRecord fixture matches the generated TS shape", () => {
    const r: MethodTrackRecord = golden.method_track_record;
    expect(r.sample_size).toBeGreaterThanOrEqual(0);
    expect(r.domain).toBe("macro");
    // Nullable fields collapse to null, not undefined.
    expect(r.weighted_brier).not.toBeUndefined();
    expect(JSON.parse(JSON.stringify(r))).toEqual(r);
  });

  it("RevisionEvent fixture matches the generated TS shape", () => {
    const e: RevisionEvent = golden.revision_event;
    expect(e.plan.plan_id).toBe(e.plan_id);
    expect(e.affected_conclusion_ids).toContain("conc_01");
    for (const inp of e.inputs) {
      expect(inp.weight).toBeGreaterThanOrEqual(-1);
      expect(inp.weight).toBeLessThanOrEqual(1);
    }
    expect(JSON.parse(JSON.stringify(e))).toEqual(e);
  });

  it("CitationVerdict fixture matches the generated TS shape", () => {
    const v: CitationVerdict = golden.citation_verdict;
    expect(v.relation_holds).toBe("entails");
    expect(v.cascade_weight).toBeGreaterThanOrEqual(0);
    expect(v.cascade_weight).toBeLessThanOrEqual(1);
    expect(JSON.parse(JSON.stringify(v))).toEqual(v);
  });

  it("Lineage fixture matches the generated TS shape", () => {
    const l: Lineage = golden.lineage;
    expect(l.nodes.length).toBeGreaterThan(0);
    const ids = new Set(l.nodes.map((n) => n.id));
    for (const e of l.edges) {
      expect(ids.has(e.src)).toBe(true);
      expect(ids.has(e.dst)).toBe(true);
    }
    expect(JSON.parse(JSON.stringify(l))).toEqual(l);
  });

  it("Generated _generated/ tree must not be edited by hand", () => {
    // Spot-check: every file in _generated should carry the autogen banner.
    // We don't enumerate at runtime in vitest (no fs walk required), but a
    // single banner check on the index keeps the contract honest.
    const indexSrc = readFileSync(
      path.resolve(__dirname, "..", "lib", "_generated", "index.ts"),
      "utf8",
    );
    expect(indexSrc).toMatch(/AUTOGENERATED/);
  });
});
