import { db } from "@/lib/db";
import type { CalibrationTriageRow } from "@/components/algorithms/CalibrationTriagePanel";

/**
 * Round 19 prompt 05 — Calibration triage queue surface.
 *
 * The Python calibration tick (noosphere/algorithms/calibration.py)
 * lays down PENDING `AlgorithmTriageRecommendation` rows when a
 * retirement / promotion trigger fires. This module is the operator
 * UI's read + accept / reject / defer surface.
 *
 * The agent NEVER auto-acts on a recommendation. ACCEPT-RETIRE sets
 * the algorithm to RETIRED with the agent narrative captured;
 * ACCEPT-PROMOTE bumps weighting_multiplier to the recommended
 * value; REJECT requires a >= 20-char operator note.
 */

type TriageDbRow = {
  id: string;
  algorithmId: string;
  recommendedAt: Date;
  recommendedAction: "NONE" | "RETIRE" | "PROMOTE";
  triggerReasonsJson: string;
  recommendedMultiplier: number;
  narrative: string;
  status: "PENDING" | "ACCEPTED" | "REJECTED" | "DEFERRED";
  algorithm: { id: string; name: string } | null;
};

function parseReasons(raw: string | null | undefined): string[] {
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.map(String) : [];
  } catch {
    return [];
  }
}

function rowToTriage(row: TriageDbRow): CalibrationTriageRow {
  return {
    id: row.id,
    algorithmId: row.algorithmId,
    algorithmName: row.algorithm?.name ?? row.algorithmId,
    recommendedAt: row.recommendedAt,
    recommendedAction: row.recommendedAction,
    triggerReasons: parseReasons(row.triggerReasonsJson),
    recommendedMultiplier: Number(row.recommendedMultiplier ?? 1.0),
    narrative: row.narrative ?? "",
  };
}

export async function listPendingTriageRecommendations(
  organizationId: string,
): Promise<CalibrationTriageRow[]> {
  // The `algorithmTriageRecommendation` Prisma model is generated by
  // the 20260516120000_algorithm_calibration migration; guard against
  // older deployments where the table doesn't yet exist.
  const client = (
    db as unknown as {
      algorithmTriageRecommendation?: {
        findMany: (args: unknown) => Promise<TriageDbRow[]>;
      };
    }
  ).algorithmTriageRecommendation;
  if (!client) return [];
  const rows = await client.findMany({
    where: {
      organizationId,
      status: "PENDING",
    },
    orderBy: { recommendedAt: "desc" },
    include: { algorithm: { select: { id: true, name: true } } },
  });
  return rows.map(rowToTriage);
}

type ResolveArgs = { actor: string; note?: string };

export async function acceptTriageRecommendation(
  organizationId: string,
  recommendationId: string,
  args: ResolveArgs,
): Promise<void> {
  const client = (
    db as unknown as {
      algorithmTriageRecommendation?: {
        findFirst: (args: unknown) => Promise<TriageDbRow | null>;
        update: (args: unknown) => Promise<unknown>;
      };
      logicalAlgorithm?: {
        update: (args: unknown) => Promise<unknown>;
      };
    }
  ).algorithmTriageRecommendation;
  if (!client) return;
  const row = await client.findFirst({
    where: { id: recommendationId, organizationId, status: "PENDING" },
    include: { algorithm: { select: { id: true, name: true } } },
  });
  if (!row) return;

  if (row.recommendedAction === "RETIRE") {
    const reason =
      row.narrative.trim().length > 0
        ? `Calibration triage accepted: ${row.narrative.slice(0, 350)}`
        : "Calibration triage accepted: retirement recommendation";
    await (
      db as unknown as {
        logicalAlgorithm: {
          update: (args: unknown) => Promise<unknown>;
        };
      }
    ).logicalAlgorithm.update({
      where: { id: row.algorithmId },
      data: { status: "RETIRED", retiredReason: reason },
    });
  } else if (row.recommendedAction === "PROMOTE") {
    const bounded = Math.max(
      0,
      Math.min(2, Number(row.recommendedMultiplier ?? 1.0)),
    );
    await (
      db as unknown as {
        logicalAlgorithm: {
          update: (args: unknown) => Promise<unknown>;
        };
      }
    ).logicalAlgorithm.update({
      where: { id: row.algorithmId },
      data: { weightingMultiplier: bounded },
    });
  }

  await client.update({
    where: { id: recommendationId },
    data: {
      status: "ACCEPTED",
      resolvedBy: args.actor,
      resolvedAt: new Date(),
      resolutionNote: args.note ?? null,
    },
  });
}

export async function rejectTriageRecommendation(
  organizationId: string,
  recommendationId: string,
  args: ResolveArgs,
): Promise<void> {
  const note = (args.note ?? "").trim();
  if (note.length < 20) {
    throw new Error(
      "REJECT requires a resolution_note of at least 20 characters",
    );
  }
  const client = (
    db as unknown as {
      algorithmTriageRecommendation?: {
        updateMany: (args: unknown) => Promise<{ count: number }>;
      };
    }
  ).algorithmTriageRecommendation;
  if (!client) return;
  await client.updateMany({
    where: { id: recommendationId, organizationId, status: "PENDING" },
    data: {
      status: "REJECTED",
      resolvedBy: args.actor,
      resolvedAt: new Date(),
      resolutionNote: note,
    },
  });
}

export async function deferTriageRecommendation(
  organizationId: string,
  recommendationId: string,
  args: ResolveArgs,
): Promise<void> {
  const client = (
    db as unknown as {
      algorithmTriageRecommendation?: {
        updateMany: (args: unknown) => Promise<{ count: number }>;
      };
    }
  ).algorithmTriageRecommendation;
  if (!client) return;
  await client.updateMany({
    where: { id: recommendationId, organizationId, status: "PENDING" },
    data: {
      status: "DEFERRED",
      resolvedBy: args.actor,
      resolvedAt: new Date(),
      resolutionNote: args.note ?? null,
    },
  });
}

export type CalibrationSnapshotRow = {
  snapshotAt: Date;
  accuracy: number | null;
  meanBrier: number | null;
  meanHorizonError: number | null;
  directionalAccuracy: number | null;
  confidenceCalibrationDrift: number | null;
  last30dAccuracy: number | null;
  totalInvocations: number;
  resolvedInvocations: number;
};

export async function listCalibrationSnapshots(
  algorithmId: string,
  limit = 200,
): Promise<CalibrationSnapshotRow[]> {
  const client = (
    db as unknown as {
      algorithmCalibrationSnapshot?: {
        findMany: (args: unknown) => Promise<CalibrationSnapshotRow[]>;
      };
    }
  ).algorithmCalibrationSnapshot;
  if (!client) return [];
  const rows = await client.findMany({
    where: { algorithmId },
    orderBy: { snapshotAt: "asc" },
    take: limit,
  });
  return rows;
}

export async function latestCalibrationSnapshot(
  algorithmId: string,
): Promise<CalibrationSnapshotRow | null> {
  const client = (
    db as unknown as {
      algorithmCalibrationSnapshot?: {
        findFirst: (args: unknown) => Promise<CalibrationSnapshotRow | null>;
      };
    }
  ).algorithmCalibrationSnapshot;
  if (!client) return null;
  return client.findFirst({
    where: { algorithmId },
    orderBy: { snapshotAt: "desc" },
  });
}
