import type { Metadata } from "next";
import "./currents.css";

export const metadata: Metadata = {
  title: { default: "Current events — Theseus", template: "%s — Theseus currents" },
  description:
    "Live commentary on unfolding events, sourced strictly from Theseus's published Noosphere.",
};

export default function CurrentsLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="currents-shell">
      <div style={{ maxWidth: "1080px", margin: "0 auto", padding: "2.25rem 1.5rem 3rem" }}>
        <header
          style={{
            display: "flex",
            alignItems: "baseline",
            justifyContent: "space-between",
            gap: "1rem",
            flexWrap: "wrap",
            paddingBottom: "1.25rem",
            borderBottom: "1px solid var(--currents-border)",
          }}
        >
          <div>
            <div
              style={{
                fontSize: "0.72rem",
                letterSpacing: "0.18em",
                textTransform: "uppercase",
                color: "var(--currents-parchment-dim)",
              }}
            >
              Theseus · live
            </div>
            <h1
              style={{
                margin: "0.15rem 0 0",
                fontFamily: "'Cinzel', 'EB Garamond', serif",
                fontSize: "1.45rem",
                color: "var(--currents-gold)",
                letterSpacing: "0.04em",
              }}
            >
              Current events
            </h1>
          </div>
          <p
            style={{
              margin: 0,
              maxWidth: "42em",
              fontStyle: "italic",
              fontSize: "0.88rem",
              lineHeight: 1.5,
              color: "var(--currents-parchment-dim)",
            }}
          >
            Every opinion below is generated by Claude Haiku from the firm&apos;s published
            Noosphere. No editorial voice, no unsourced commentary — the firm abstains
            when its knowledge base does not support a position.
          </p>
        </header>
        {children}
        <footer
          style={{
            marginTop: "3rem",
            paddingTop: "1.1rem",
            borderTop: "1px solid var(--currents-border)",
            fontSize: "0.78rem",
            lineHeight: 1.6,
            color: "var(--currents-parchment-dim)",
            fontStyle: "italic",
          }}
        >
          <p style={{ margin: 0, maxWidth: "52em" }}>
            Opinions on this page are generated by Claude Haiku 4.5 from the firm&apos;s
            published Noosphere of conclusions and claims. They are not editorial
            commentary, not legal or financial advice, and not an exhaustive survey
            of the firm&apos;s thinking. The firm abstains from opining when its sources
            do not support a position; an abstention is not agreement with the
            observed event. Citations link to verbatim source passages; when a
            source is revoked, dependent opinions are marked accordingly. Follow-up
            answers re-retrieve from the Noosphere on each question — the assistant
            does not answer from memory.
          </p>
        </footer>
      </div>
    </div>
  );
}
