/* AUTOGENERATED FROM packages/shared-schemas/citation_verdict.schema.json.
 * DO NOT EDIT BY HAND. Regenerate with
 *   tsx packages/shared-schemas/scripts/generate_typescript.ts
 */

export type CitationKind = "opinion" | "forecast" | "conclusion_source";

export type CitationRelation =
  | "supports"
  | "contradicts"
  | "qualifies"
  | "mentions";

export type VerdictLabel =
  | "entails"
  | "contradicts"
  | "neutral"
  | "ambiguous";

export interface CitationVerdict {
  citation_kind: CitationKind;
  citation_id: string;
  source_id: string;
  relation: CitationRelation;
  relation_holds: VerdictLabel;
  confidence: number;
  excerpt_used: string;
  stated_claim: string;
  cascade_weight: number;
  model_version: string;
  computed_at: string;
  overridden_by?: string | null;
  override_reason?: string | null;
}
