/* AUTOGENERATED FROM packages/shared-schemas/citation_verdict.schema.json.
 * DO NOT EDIT BY HAND. Regenerate with
 *   tsx packages/shared-schemas/scripts/generate_typescript.ts
 */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Citation-chain verdict ledger row. The Python NLI judge in noosphere/literature/citation_chain.py is canonical for the verdict label; this schema is the wire-shape the codex reads back into VerdictPill rendering and stores in the CitationVerdict table.
 */
export interface CitationVerdict {
  citation_kind: "opinion" | "forecast" | "conclusion_source";
  citation_id: string;
  source_id: string;
  relation: "supports" | "contradicts" | "qualifies" | "mentions";
  relation_holds: "entails" | "contradicts" | "neutral" | "ambiguous";
  confidence: number;
  excerpt_used: string;
  stated_claim: string;
  cascade_weight: number;
  model_version: string;
  computed_at: string;
  overridden_by?: string | null;
  override_reason?: string | null;
}
