/* AUTOGENERATED FROM packages/shared-schemas/conclusion.schema.json.
 * DO NOT EDIT BY HAND. Regenerate with
 *   tsx packages/shared-schemas/scripts/generate_typescript.ts
 */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Cross-language payload shape for a Conclusion record. Database-backed (Prisma owns the canonical TS row type via `Prisma.Conclusion`); this schema describes the JSON wire-form shipped between noosphere and codex (e.g. CLI exports, store sync) and is what runtime validators check on either side. Field names are snake_case to match the Pydantic side; the TS adapters translate to/from camelCase at the Prisma boundary.
 */
export interface Conclusion {
  id: string;
  text: string;
  reasoning?: string;
  rationale?: string;
  kind?: "firm" | "tentative" | "exploratory" | "retracted";
  confidence_tier?: "high" | "moderate" | "low" | "speculative";
  principles_used?: string[];
  claims_used?: string[];
  supporting_principle_ids?: string[];
  evidence_chain_claim_ids?: string[];
  dissent_claim_ids?: string[];
  confidence: number;
  disciplines?: string[];
  freshness?: "fresh" | "aging" | "stale";
  created_at?: string;
  updated_at?: string;
  superseded_at?: string | null;
  last_validated_at?: string | null;
}
