/* AUTOGENERATED FROM packages/shared-schemas/conclusion.schema.json.
 * DO NOT EDIT BY HAND. Regenerate with
 *   tsx packages/shared-schemas/scripts/generate_typescript.ts
 */

export type ConclusionKind =
  | "firm"
  | "tentative"
  | "exploratory"
  | "retracted";

export type ConfidenceTier =
  | "high"
  | "moderate"
  | "low"
  | "speculative";

export type Freshness = "fresh" | "aging" | "stale";

export interface Conclusion {
  id: string;
  text: string;
  reasoning?: string;
  rationale?: string;
  kind?: ConclusionKind;
  confidence_tier?: ConfidenceTier;
  principles_used?: string[];
  claims_used?: string[];
  supporting_principle_ids?: string[];
  evidence_chain_claim_ids?: string[];
  dissent_claim_ids?: string[];
  confidence: number;
  disciplines?: string[];
  freshness?: Freshness;
  created_at?: string;
  updated_at?: string;
  superseded_at?: string | null;
  last_validated_at?: string | null;
}
