/* AUTOGENERATED — do not edit.
 * Re-exports the generated TS types so callers can import them as
 *   import type { Conclusion } from "@/lib/_generated";
 * rather than reaching into the per-schema module files.
 */
export type { Conclusion } from "./conclusion";
export type { MethodologyQualityScore } from "./mqs";
export type { MethodTrackRecord } from "./method_track_record";
export type { RevisionEvent } from "./revision_event";
export type { CitationVerdict } from "./citation_verdict";
export type { Lineage } from "./lineage";
