/* AUTOGENERATED FROM packages/shared-schemas/lineage.schema.json.
 * DO NOT EDIT BY HAND. Regenerate with
 *   tsx packages/shared-schemas/scripts/generate_typescript.ts
 */

export type LineageNodeKind =
  | "source"
  | "claim"
  | "methodology"
  | "method_invocation"
  | "peer_review"
  | "revision"
  | "drift"
  | "calibration"
  | "conclusion"
  | "publication"
  | "citation";

export interface LineageNode {
  id: string;
  kind: LineageNodeKind;
  label: string;
  timestamp: string;
  summary?: string;
  payload?: { [k: string]: unknown };
  public_visible?: boolean;
  record_url?: string;
}

export interface LineageEdge {
  src: string;
  dst: string;
  relation: string;
}

export interface Lineage {
  conclusion_id: string;
  assembled_at: string;
  nodes: LineageNode[];
  edges: LineageEdge[];
}
