/* AUTOGENERATED FROM packages/shared-schemas/lineage.schema.json.
 * DO NOT EDIT BY HAND. Regenerate with
 *   tsx packages/shared-schemas/scripts/generate_typescript.ts
 */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `Lineage`'s JSON-Schema
 * via the `definition` "LineageNodeKind".
 */
export type LineageNodeKind =
  | "source"
  | "claim"
  | "methodology"
  | "method_invocation"
  | "peer_review"
  | "revision"
  | "drift"
  | "calibration"
  | "conclusion"
  | "publication"
  | "citation";

/**
 * Provenance graph for a single Conclusion. Assembled on both sides — noosphere/temporal/lineage.py from the Store; theseus-codex/src/lib/lineage.ts from Prisma rows. The JSON shape must be byte-stable across implementations so the public route can serve either source.
 */
export interface Lineage {
  conclusion_id: string;
  assembled_at: string;
  nodes: LineageNode[];
  edges: LineageEdge[];
}
/**
 * This interface was referenced by `Lineage`'s JSON-Schema
 * via the `definition` "LineageNode".
 */
export interface LineageNode {
  id: string;
  kind: LineageNodeKind;
  label: string;
  timestamp: string;
  summary?: string;
  payload?: {
    [k: string]: unknown;
  };
  public_visible?: boolean;
  record_url?: string;
}
/**
 * This interface was referenced by `Lineage`'s JSON-Schema
 * via the `definition` "LineageEdge".
 */
export interface LineageEdge {
  src: string;
  dst: string;
  relation: string;
}
