/* AUTOGENERATED FROM packages/shared-schemas/method_track_record.schema.json.
 * DO NOT EDIT BY HAND. Regenerate with
 *   tsx packages/shared-schemas/scripts/generate_typescript.ts
 */

export interface MethodTrackRecord {
  organization_id: string;
  method_name: string;
  method_version: string;
  domain: string;
  sample_size: number;
  weighted_brier?: number | null;
  calibration_slope?: number | null;
  calibration_slope_ci_low?: number | null;
  calibration_slope_ci_high?: number | null;
  severity_pass_rate?: number | null;
  evidence?: { [k: string]: unknown };
  computed_at: string;
}
