/* AUTOGENERATED FROM packages/shared-schemas/method_track_record.schema.json.
 * DO NOT EDIT BY HAND. Regenerate with
 *   tsx packages/shared-schemas/scripts/generate_typescript.ts
 */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * One materialized row from `MethodTrackRecord`. The Prisma model is the canonical column shape on the codex side; this schema is the JSON wire-form used by the noosphere aggregator (noosphere/evaluation/method_track_record.py) and by /methods/<name>/<version>/track-record API responses. `nullable` fields collapse to `null` (not absent) so downstream typed clients don't have to discriminate.
 */
export interface MethodTrackRecord {
  organization_id: string;
  method_name: string;
  method_version: string;
  /**
   * Empty string means 'no domain label'. Never smoothed across domains.
   */
  domain: string;
  sample_size: number;
  weighted_brier?: number | null;
  calibration_slope?: number | null;
  calibration_slope_ci_low?: number | null;
  calibration_slope_ci_high?: number | null;
  severity_pass_rate?: number | null;
  evidence?: {
    [k: string]: unknown;
  };
  computed_at: string;
}
