/* AUTOGENERATED FROM packages/shared-schemas/mqs.schema.json.
 * DO NOT EDIT BY HAND. Regenerate with
 *   tsx packages/shared-schemas/scripts/generate_typescript.ts
 */

export interface SubScore {
  score: number;
  evidence?: { [k: string]: unknown };
}

export interface MethodologyQualityScore {
  schema: "theseus.mqs.v1";
  conclusion_id: string;
  progressivity: SubScore;
  severity: SubScore;
  aim_method_fit: SubScore;
  compressibility: SubScore;
  domain_sensitivity: SubScore;
  composite: number;
  composite_formula?: string;
  model_name?: string;
  prompt_version?: string;
  scored_at?: string;
}
