/* AUTOGENERATED FROM packages/shared-schemas/mqs.schema.json.
 * DO NOT EDIT BY HAND. Regenerate with
 *   tsx packages/shared-schemas/scripts/generate_typescript.ts
 */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Methodology Quality Score payload. The scorer lives in noosphere/evaluation/mqs.py (Python is canonical for the computation); this schema is the wire-shape that the codex stores and renders. Composite formula and sub-score semantics are documented in docs/methods/MQS_Specification.md.
 */
export interface MethodologyQualityScore {
  schema: "theseus.mqs.v1";
  conclusion_id: string;
  progressivity: SubScore;
  severity: SubScore;
  aim_method_fit: SubScore;
  compressibility: SubScore;
  domain_sensitivity: SubScore;
  composite: number;
  composite_formula?: string;
  model_name?: string;
  prompt_version?: string;
  scored_at?: string;
}
/**
 * This interface was referenced by `MethodologyQualityScore`'s JSON-Schema
 * via the `definition` "SubScore".
 */
export interface SubScore {
  score: number;
  evidence?: {
    [k: string]: unknown;
  };
}
