/* AUTOGENERATED FROM packages/shared-schemas/revision_event.schema.json.
 * DO NOT EDIT BY HAND. Regenerate with
 *   tsx packages/shared-schemas/scripts/generate_typescript.ts
 */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Belief-revision payloads shared between noosphere/cascade/revision.py (canonical algorithm) and theseus-codex/src/lib/revisionApi.ts (UI + persistence). The event row in Prisma stores `inputsJson` / `planJson` / `preConfidenceSnapshot` as TEXT — this schema is what those blobs decode to.
 */
export interface RevisionEvent {
  event_id: string;
  plan_id: string;
  inputs: RevisionInput[];
  plan: RevisionPlan;
  pre_confidence_snapshot: {
    [k: string]: number;
  };
  affected_conclusion_ids: string[];
  typed_confirmation: boolean;
  created_at: string;
  reverted_at?: string | null;
}
/**
 * This interface was referenced by `RevisionEvent`'s JSON-Schema
 * via the `definition` "RevisionInput".
 */
export interface RevisionInput {
  claim_id: string;
  new_evidence: string;
  weight: number;
}
/**
 * This interface was referenced by `RevisionEvent`'s JSON-Schema
 * via the `definition` "RevisionPlan".
 */
export interface RevisionPlan {
  plan_id: string;
  inputs: RevisionInput[];
  changed: ConfidenceShift[];
  newly_contradicted: ConfidenceShift[];
  newly_supported: ConfidenceShift[];
  stable_count: number;
  consulted_edge_ids?: string[];
  delta: number;
  theta: number;
}
/**
 * This interface was referenced by `RevisionEvent`'s JSON-Schema
 * via the `definition` "ConfidenceShift".
 */
export interface ConfidenceShift {
  conclusion_id: string;
  before: number;
  after: number;
  delta?: number;
  classification: "changed" | "newly_contradicted" | "newly_supported" | "stable";
}
