/* AUTOGENERATED FROM packages/shared-schemas/revision_event.schema.json.
 * DO NOT EDIT BY HAND. Regenerate with
 *   tsx packages/shared-schemas/scripts/generate_typescript.ts
 */

export type ShiftClassification =
  | "changed"
  | "newly_contradicted"
  | "newly_supported"
  | "stable";

export interface RevisionInput {
  claim_id: string;
  new_evidence: string;
  weight: number;
}

export interface ConfidenceShift {
  conclusion_id: string;
  before: number;
  after: number;
  delta?: number;
  classification: ShiftClassification;
}

export interface RevisionPlan {
  plan_id: string;
  inputs: RevisionInput[];
  changed: ConfidenceShift[];
  newly_contradicted: ConfidenceShift[];
  newly_supported: ConfidenceShift[];
  stable_count: number;
  consulted_edge_ids?: string[];
  delta: number;
  theta: number;
}

export interface RevisionEvent {
  event_id: string;
  plan_id: string;
  inputs: RevisionInput[];
  plan: RevisionPlan;
  pre_confidence_snapshot: { [k: string]: number };
  affected_conclusion_ids: string[];
  typed_confirmation: boolean;
  created_at: string;
  reverted_at?: string | null;
}
