#!/usr/bin/env bash
# Schedule the firm's next Methodology Review Week.
#
# The firm holds a quarterly Methodology Review Week — five working
# days, mid-quarter, where the team turns its methods on itself: drift
# events on day 1, failure-mode catalog on day 2, domain bounds on day
# 3, retirement candidates on day 4, and the seasonal-review
# methodology section on day 5.
#
# This script produces the schedule on disk: for the requested quarter
# (or the next upcoming one) it writes a `schedule.json` describing the
# five days and a Markdown placeholder for each day's queue page. The
# script does not flip anything in the Codex database — opt-in per
# founder; the founder confirms the week in the web app.
#
# Usage:
#   ./schedule_methodology_review_week.sh
#       [--year YYYY] [--quarter N]
#       [--start YYYY-MM-DD]
#       [--out-root DIR]
#       [--year-ahead]
#
#   --year/--quarter   Target a specific quarter. Defaults: the next
#                      review week whose start is on or after today.
#   --start            Override the default mid-quarter Monday (must be
#                      a Monday). Used when the founder postpones.
#   --out-root         Where the slug dir + JSON land. Default
#                      docs/methodology_review_week.
#   --year-ahead       Emit all four quarters of the next year at once.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
export PYTHONPATH="${ROOT}/noosphere:${PYTHONPATH:-}"

PY="${PYTHON:-python3}"
YEAR=""
QUARTER=""
START=""
OUT_ROOT="$ROOT/docs/methodology_review_week"
YEAR_AHEAD="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --year) YEAR="$2"; shift 2;;
    --quarter) QUARTER="$2"; shift 2;;
    --start) START="$2"; shift 2;;
    --out-root) OUT_ROOT="$2"; shift 2;;
    --year-ahead) YEAR_AHEAD="1"; shift;;
    -h|--help) sed -n '2,30p' "$0"; exit 0;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

mkdir -p "$OUT_ROOT"

echo "=== Methodology Review Week scheduler ==="
echo "  root       : $ROOT"
echo "  out root   : $OUT_ROOT"
[[ -n "$YEAR" ]] && echo "  year       : $YEAR"
[[ -n "$QUARTER" ]] && echo "  quarter    : Q$QUARTER"
[[ -n "$START" ]] && echo "  start      : $START"
[[ "$YEAR_AHEAD" == "1" ]] && echo "  mode       : full year"
echo

MRW_YEAR="$YEAR" \
MRW_QUARTER="$QUARTER" \
MRW_START="$START" \
MRW_OUT_ROOT="$OUT_ROOT" \
MRW_YEAR_AHEAD="$YEAR_AHEAD" \
"$PY" - <<'PYEOF'
import json
import os
from datetime import date
from pathlib import Path

from noosphere.inquiry.methodology_review_week import (
    DAY_LABELS,
    DEFAULT_REVIEW_WEEK_ROOT,
    next_review_week_after,
    schedule_for_quarter,
    schedule_for_year,
    week_dir,
)

OUT_ROOT = Path(os.environ["MRW_OUT_ROOT"])
year_env = os.environ.get("MRW_YEAR") or ""
quarter_env = os.environ.get("MRW_QUARTER") or ""
start_env = os.environ.get("MRW_START") or ""
year_ahead = os.environ.get("MRW_YEAR_AHEAD") == "1"

today = date.today()

if year_ahead:
    weeks = list(schedule_for_year(today.year + 1))
elif year_env and quarter_env:
    start = date.fromisoformat(start_env) if start_env else None
    weeks = [schedule_for_quarter(int(year_env), int(quarter_env), start=start)]
else:
    weeks = [next_review_week_after(today)]

for week in weeks:
    target = OUT_ROOT / week.slug
    target.mkdir(parents=True, exist_ok=True)
    schedule_path = target / "schedule.json"
    schedule_path.write_text(
        json.dumps(week.to_dict(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"  wrote {schedule_path}")
    for d in week.days:
        placeholder = target / f"day_{d.day_index}.README.md"
        if placeholder.is_file():
            continue
        placeholder.write_text(
            "\n".join(
                [
                    f"# {DAY_LABELS[d.focus]}",
                    "",
                    f"Date: {d.on.isoformat()}",
                    f"Focus: {d.focus}",
                    "",
                    "The founder writes the day's summary at "
                    f"`day_{d.day_index}.json` (sibling of this file). Drafts "
                    "generated by the agent live in the web app; the founder's "
                    "submitted body is signed and immutable.",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        print(f"  wrote {placeholder}")

print()
print(f"=== schedule_methodology_review_week.sh done ===")
print(f"  scheduled: {', '.join(w.slug for w in weeks)}")
PYEOF
