#!/usr/bin/env tsx
/**
 * Generate TypeScript types from `packages/shared-schemas/*.schema.json`.
 *
 * Output is written under `theseus-codex/src/lib/_generated/`. The directory
 * is treated as build-output: every regeneration replaces the contents, and
 * the files carry a `DO NOT EDIT` banner enforced by the CI lint in
 * `.github/workflows/type-contracts.yml`.
 *
 * Generation uses `json-schema-to-typescript`, which the codex package
 * pulls in as a devDependency. The CLI is invoked once per schema so
 * failures are attributed to a specific file in CI logs.
 *
 * Usage:
 *
 *     tsx packages/shared-schemas/scripts/generate_typescript.ts [--check]
 *
 * `--check` regenerates into a temp dir and exits non-zero if the diff
 * against the committed `_generated/` tree is non-empty. CI uses this to
 * fail the build when a schema edit is committed without rerunning the
 * generator.
 */

import { execSync } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

const REPO_ROOT = path.resolve(__dirname, "..", "..", "..");
const SCHEMA_DIR = path.join(REPO_ROOT, "packages", "shared-schemas");
const OUT_DIR = path.join(
  REPO_ROOT,
  "theseus-codex",
  "src",
  "lib",
  "_generated",
);

const BANNER = (schema: string) =>
  `/* AUTOGENERATED FROM packages/shared-schemas/${schema}.\n` +
  ` * DO NOT EDIT BY HAND. Regenerate with\n` +
  ` *   tsx packages/shared-schemas/scripts/generate_typescript.ts\n` +
  ` */\n`;

// (schema-stem, exported root type)
const SCHEMAS: ReadonlyArray<{ stem: string; rootType: string }> = [
  { stem: "conclusion", rootType: "Conclusion" },
  { stem: "mqs", rootType: "MethodologyQualityScore" },
  { stem: "method_track_record", rootType: "MethodTrackRecord" },
  { stem: "revision_event", rootType: "RevisionEvent" },
  { stem: "citation_verdict", rootType: "CitationVerdict" },
  { stem: "lineage", rootType: "Lineage" },
];

function runJsonSchemaToTs(input: string, output: string): void {
  // Resolve the CLI via the codex node_modules so the script doesn't depend
  // on the binary being on $PATH.
  const cliCandidates = [
    path.join(
      REPO_ROOT,
      "theseus-codex",
      "node_modules",
      ".bin",
      "json2ts",
    ),
    path.join(
      REPO_ROOT,
      "node_modules",
      ".bin",
      "json2ts",
    ),
    "json2ts",
  ];
  const cli =
    cliCandidates.find((p) => p === "json2ts" || fs.existsSync(p)) ?? "json2ts";
  execSync(
    [
      JSON.stringify(cli),
      "--input",
      JSON.stringify(input),
      "--output",
      JSON.stringify(output),
      "--style.singleQuote",
      "false",
      "--no-additionalProperties",
      "--unreachableDefinitions",
    ].join(" "),
    { stdio: "inherit" },
  );
}

function generateOne(stem: string): string {
  const inputPath = path.join(SCHEMA_DIR, `${stem}.schema.json`);
  const outPath = path.join(OUT_DIR, `${stem}.ts`);
  runJsonSchemaToTs(inputPath, outPath);
  const original = fs.readFileSync(outPath, "utf8");
  fs.writeFileSync(outPath, BANNER(`${stem}.schema.json`) + original);
  return outPath;
}

function writeIndex(target: string): void {
  const exports = SCHEMAS.map(
    ({ stem, rootType }) =>
      `export type { ${rootType} } from "./${stem}";`,
  );
  const header = [
    "/* AUTOGENERATED — do not edit.",
    " * Re-exports the generated TS types so callers can import them as",
    " *   import type { Conclusion } from \"@/lib/_generated\";",
    " * rather than reaching into the per-schema module files.",
    " */",
    "",
  ].join("\n");
  fs.writeFileSync(
    path.join(target, "index.ts"),
    header + exports.join("\n") + "\n",
  );
}

function generate(target: string): void {
  fs.mkdirSync(target, { recursive: true });
  for (const { stem } of SCHEMAS) {
    const out = path.join(target, `${stem}.ts`);
    runJsonSchemaToTs(
      path.join(SCHEMA_DIR, `${stem}.schema.json`),
      out,
    );
    const original = fs.readFileSync(out, "utf8");
    fs.writeFileSync(out, BANNER(`${stem}.schema.json`) + original);
  }
  writeIndex(target);
}

function listFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((n) => n.endsWith(".ts"))
    .sort();
}

function diffTrees(a: string, b: string): string[] {
  const aFiles = new Set(listFiles(a));
  const bFiles = new Set(listFiles(b));
  const diffs: string[] = [];
  for (const f of aFiles) if (!bFiles.has(f)) diffs.push(`only in ${a}: ${f}`);
  for (const f of bFiles) if (!aFiles.has(f)) diffs.push(`only in ${b}: ${f}`);
  for (const f of aFiles) {
    if (!bFiles.has(f)) continue;
    const aBuf = fs.readFileSync(path.join(a, f));
    const bBuf = fs.readFileSync(path.join(b, f));
    if (!aBuf.equals(bBuf)) diffs.push(`differs: ${f}`);
  }
  return diffs;
}

function main(): number {
  const check = process.argv.includes("--check");
  if (check) {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "shared-schemas-"));
    try {
      generate(tmp);
      // Generated tree also includes the index.ts; ensure it is part of the diff.
      const diffs = diffTrees(tmp, OUT_DIR);
      // Also compare index.ts explicitly (different file extension matched above).
      if (diffs.length) {
        console.log("Generated TS types differ from committed tree:");
        for (const d of diffs) console.log(`  ${d}`);
        console.log(
          "Run `tsx packages/shared-schemas/scripts/generate_typescript.ts` and commit.",
        );
        return 1;
      }
      return 0;
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
  }
  if (fs.existsSync(OUT_DIR)) {
    fs.rmSync(OUT_DIR, { recursive: true, force: true });
  }
  generate(OUT_DIR);
  console.log(`Wrote TS types to ${OUT_DIR}`);
  return 0;
}

process.exit(main());
