#!/usr/bin/env python3
"""Generate Pydantic models from `packages/shared-schemas/*.schema.json`.

Output is written under `noosphere/noosphere/_generated/`. The directory is
treated as build-output: every regeneration replaces the contents, and the
files carry a `DO NOT EDIT` banner enforced by the CI lint in
`.github/workflows/type-contracts.yml`.

Generation uses `datamodel-code-generator` (installed via the `dev` extras of
the root `pyproject.toml`). The CLI is invoked once per schema so failures
are attributed to a specific file in CI logs.

Usage::

    python packages/shared-schemas/scripts/generate_pydantic.py [--check]

`--check` regenerates into a temp dir and exits non-zero if the diff against
the committed `_generated/` tree is non-empty. CI uses this to fail the
build when a schema edit is committed without rerunning the generator.
"""

from __future__ import annotations

import argparse
import filecmp
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
SCHEMA_DIR = REPO_ROOT / "packages" / "shared-schemas"
OUT_DIR = REPO_ROOT / "noosphere" / "noosphere" / "_generated"

BANNER = (
    "# AUTOGENERATED FROM packages/shared-schemas/{schema}.\n"
    "# DO NOT EDIT BY HAND. Regenerate with\n"
    "#   python packages/shared-schemas/scripts/generate_pydantic.py\n"
)

# (schema-stem, output-module-name)
SCHEMAS: list[tuple[str, str]] = [
    ("conclusion", "conclusion"),
    ("mqs", "mqs"),
    ("method_track_record", "method_track_record"),
    ("revision_event", "revision_event"),
    ("citation_verdict", "citation_verdict"),
    ("lineage", "lineage"),
]


def _datamodel_codegen_available() -> bool:
    try:
        subprocess.run(
            [sys.executable, "-m", "datamodel_code_generator", "--version"],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def _generate_one(schema_path: Path, out_path: Path) -> None:
    """Run `datamodel-codegen` on a single schema file."""
    cmd = [
        sys.executable,
        "-m",
        "datamodel_code_generator",
        "--input",
        str(schema_path),
        "--input-file-type",
        "jsonschema",
        "--output",
        str(out_path),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.11",
        "--use-schema-description",
        "--use-double-quotes",
        "--disable-timestamp",
        "--collapse-root-models",
    ]
    subprocess.run(cmd, check=True)
    # Prepend banner. datamodel-codegen does not let us inject one.
    original = out_path.read_text()
    out_path.write_text(BANNER.format(schema=schema_path.name) + original)


def _write_init(out_dir: Path) -> None:
    """Write a package __init__.py re-exporting every generated module."""
    lines: list[str] = [
        "# AUTOGENERATED — do not edit.",
        "# Re-exports the generated Pydantic models so callers can import them as",
        "#   from noosphere._generated import Conclusion",
        "# rather than reaching into the per-schema module files.",
        "",
        "from .conclusion import Conclusion",
        "from .mqs import MethodologyQualityScore as Mqs",
        "from .method_track_record import MethodTrackRecord",
        "from .revision_event import RevisionEvent",
        "from .citation_verdict import CitationVerdict",
        "from .lineage import Lineage",
        "",
        "__all__ = [",
        "    \"Conclusion\",",
        "    \"Mqs\",",
        "    \"MethodTrackRecord\",",
        "    \"RevisionEvent\",",
        "    \"CitationVerdict\",",
        "    \"Lineage\",",
        "]",
        "",
    ]
    (out_dir / "__init__.py").write_text("\n".join(lines))


def generate(target: Path) -> None:
    target.mkdir(parents=True, exist_ok=True)
    for stem, _module in SCHEMAS:
        schema_path = SCHEMA_DIR / f"{stem}.schema.json"
        out_path = target / f"{stem}.py"
        _generate_one(schema_path, out_path)
    _write_init(target)


def _diff_trees(a: Path, b: Path) -> list[str]:
    cmp = filecmp.dircmp(a, b)
    diffs: list[str] = []
    diffs.extend(f"only in {a}: {n}" for n in cmp.left_only)
    diffs.extend(f"only in {b}: {n}" for n in cmp.right_only)
    diffs.extend(f"differs: {n}" for n in cmp.diff_files)
    return diffs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Generate into a temp dir and fail if the result differs from the committed tree.",
    )
    args = parser.parse_args()

    if not _datamodel_codegen_available():
        print(
            "datamodel-code-generator is not installed. Install with\n"
            "    pip install -e .[dev]\n"
            "or add `datamodel-code-generator` to your environment.",
            file=sys.stderr,
        )
        return 2

    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp) / "_generated"
            generate(target)
            diffs = _diff_trees(target, OUT_DIR)
            if diffs:
                print("Generated Pydantic models differ from committed tree:")
                for d in diffs:
                    print(f"  {d}")
                print(
                    "Run `python packages/shared-schemas/scripts/generate_pydantic.py` and commit."
                )
                return 1
            return 0

    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    generate(OUT_DIR)
    print(f"Wrote Pydantic models to {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
