# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Dialectic.

Build:
    pyinstaller dialectic.spec

Output:
    macOS    -> dist/Dialectic.app
    Windows  -> dist/Dialectic/Dialectic.exe  (one-dir, NOT one-file: torch is too
                large to extract reliably under --onefile)
    Linux    -> dist/Dialectic/Dialectic

Platform-specific icon files (.icns / .ico) are generated by the build scripts
(see prompt 05). The PNG referenced here is a fallback suitable for Linux.
"""

import sys
from pathlib import Path

block_cipher = None
ROOT = Path(SPECPATH)

hiddenimports = [
    # Qt stack
    "PyQt6",
    "PyQt6.QtCore",
    "PyQt6.QtGui",
    "PyQt6.QtWidgets",
    "PyQt6.sip",
    "pyqtgraph",
    "qasync",
    # Audio
    "sounddevice",
    "_sounddevice",
    # Transcription
    "faster_whisper",
    "ctranslate2",
    # Embeddings / NLI
    "sentence_transformers",
    "torch",
    "numpy",
    "scipy",
    "scipy.special",
    "scipy.signal",
    "sklearn",
    "sklearn.cluster",
    "sklearn.metrics",
    "sklearn.utils._typedefs",
    "sklearn.utils._heap",
    "sklearn.utils._sorting",
    "sklearn.utils._vector_sentinel",
    "sklearn.neighbors._partition_nodes",
    # LLM
    "anthropic",
]

excludes = [
    "tensorflow",
    "tensorboard",
    "jupyter",
    "IPython",
    "ipykernel",
    "notebook",
    "matplotlib",
    "pytest",
    "pytest_asyncio",
    "tkinter",
    "PyQt5",
    "PySide2",
    "PySide6",
]

a = Analysis(
    [str(ROOT / "run.py")],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[(str(ROOT / "assets"), "assets")],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Dialectic",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ROOT / "assets" / "icon.png"),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="Dialectic",
)

if sys.platform == "darwin":
    app = BUNDLE(
        coll,
        name="Dialectic.app",
        icon=str(ROOT / "assets" / "icon.png"),
        bundle_identifier="com.theseus.dialectic",
        info_plist={
            "CFBundleName": "Dialectic",
            "CFBundleDisplayName": "Dialectic",
            "CFBundleShortVersionString": "0.1.0",
            "CFBundleVersion": "0.1.0",
            "NSHighResolutionCapable": True,
            "NSMicrophoneUsageDescription": "Dialectic transcribes live conversation audio from your selected input device.",
            "LSMinimumSystemVersion": "11.0",
        },
    )
