from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Optional

from noosphere.models import Conclusion, ReviewReport
from noosphere.peer_review.providers import ObjectionResult, ProviderAdapter


@dataclass
class BiasProfile:
    name: str
    prior: str
    known_blindspots: list[str] = field(default_factory=list)


class Reviewer(ABC):
    name: str
    bias_profile: BiasProfile

    @abstractmethod
    def review(self, conclusion: Conclusion, context: dict[str, Any]) -> ReviewReport:
        ...


class LLMProviderReviewer(Reviewer):
    """A reviewer that delegates objection generation to a provider adapter.

    This is the seam the multi-provider swarm uses: the same reviewer
    class is instantiated once per available provider so the orchestra
    of objections is architecturally diverse rather than just
    prompt-diverse.
    """

    def __init__(
        self,
        *,
        adapter: ProviderAdapter,
        bias_profile: Optional[BiasProfile] = None,
        max_tokens: int = 512,
        temperature: float = 0.2,
        seed: Optional[int] = None,
    ) -> None:
        self.adapter = adapter
        self.name = f"provider:{adapter.name}"
        self.max_tokens = max_tokens
        self.temperature = temperature
        self.seed = seed
        self.bias_profile = bias_profile or BiasProfile(
            name=adapter.name,
            prior=(
                f"Adversarial objection generated by {adapter.name} "
                f"({adapter.model}); failure modes are those of the "
                f"underlying provider's training and post-training."
            ),
            known_blindspots=[
                "Inherits the underlying model's instruction-tuning biases.",
                "Single-call objection: cannot iterate against rebuttals.",
            ],
        )

    def produce_objection(
        self, conclusion: Conclusion, context: dict[str, Any]
    ) -> ObjectionResult:
        methodology = _methodology_summary(context)
        return self.adapter.produce_objection(
            claim=conclusion.text,
            methodology=methodology,
            context=_lean_context(context),
            max_tokens=self.max_tokens,
            temperature=self.temperature,
            seed=self.seed,
        )

    def review(
        self, conclusion: Conclusion, context: dict[str, Any]
    ) -> ReviewReport:
        # The swarm orchestrator drives ``produce_objection`` directly so
        # it can apply cost governance and disagreement detection across
        # providers. ``review`` is provided for symmetry with the rest
        # of the reviewer registry: it runs the same objection through
        # a non-budgeted single-shot path.
        from datetime import datetime, timezone

        from noosphere.models import Finding

        result = self.produce_objection(conclusion, context)
        if not result.ok:
            findings = [
                Finding(
                    severity="info",
                    category="provider_error",
                    detail=(
                        f"Provider {result.provider} produced no "
                        f"objection: {result.error or 'empty response'}"
                    ),
                    evidence=[
                        f"provider={result.provider}",
                        f"model={result.model}",
                    ],
                    suggested_action=(
                        "Re-run with the provider available, or accept "
                        "the swarm result as a partial review."
                    ),
                )
            ]
            verdict = "accept"
            confidence = 0.5
        else:
            from noosphere.peer_review.severity import (
                score_objection as _score_severity,
            )
            from noosphere.peer_review.swarm import severity_inputs_from_context

            sev = _score_severity(severity_inputs_from_context(conclusion, context))
            result.extra["severity"] = sev.to_dict()
            label_to_finding = {"low": "minor", "medium": "major", "high": "blocker"}
            finding_severity = label_to_finding.get(sev.label, "major")
            evidence = [
                f"provider={result.provider}",
                f"model={result.model}",
                f"cost_usd={result.cost_usd:.6f}",
                f"latency_ms={result.latency_ms:.1f}",
                f"severity={sev.label}:{sev.value:.4f}",
            ]
            if sev.judge_capped:
                evidence.append("severity_judge_capped=true")
            findings = [
                Finding(
                    severity=finding_severity,
                    category="adversarial_objection",
                    detail=result.text,
                    evidence=evidence,
                    suggested_action=(
                        "Address the objection in a rebuttal or revise "
                        "the methodology."
                    ),
                )
            ]
            verdict = "revise" if finding_severity != "blocker" else "reject"
            confidence = 0.7

        return ReviewReport(
            report_id=f"{self.name}-{conclusion.id}",
            reviewer=self.name,
            conclusion_id=conclusion.id,
            findings=findings,
            overall_verdict=verdict,
            confidence=confidence,
            completed_at=datetime.now(timezone.utc),
            method_invocation_ids=[],
        )


def _methodology_summary(context: dict[str, Any]) -> str:
    methods_used = context.get("methods_used") or []
    if not methods_used:
        return "(unspecified)"
    parts: list[str] = []
    for m in methods_used:
        name = m.get("name") if isinstance(m, dict) else getattr(m, "name", "")
        version = (
            m.get("version") if isinstance(m, dict) else getattr(m, "version", "")
        )
        parts.append(f"{name}@{version}" if version else str(name))
    return ", ".join(p for p in parts if p)


def _lean_context(context: dict[str, Any]) -> dict[str, Any]:
    """Drop heavyweight objects so they don't drown the prompt."""
    skip = {"method_registry", "store"}
    out: dict[str, Any] = {}
    for k, v in context.items():
        if k in skip:
            continue
        if isinstance(v, (str, int, float, bool)) or v is None:
            out[k] = v
    return out
