#!/usr/bin/env python3
"""Generate the README "Surface map" section from the Next.js app tree.

OPT-IN — operators run this manually when the surface changes. The
output is a markdown bullet list, one bullet per route, with a one-
line purpose pulled from a comment at the top of each ``page.tsx``.

Convention for the page-level comment::

    // surface: <one-line purpose>
    export default function Page() { ... }

Or::

    /* surface: <one-line purpose> */

Routes without a ``surface:`` comment render with a placeholder
``(unannotated)`` so the gap is visible.

Usage
-----

    python scripts/generate_surface_map.py            # prints to stdout
    python scripts/generate_surface_map.py --write    # rewrites README.md

The "--write" path replaces the content between the markers::

    <!-- BEGIN SURFACE MAP -->
    ...
    <!-- END SURFACE MAP -->

If the markers are absent the script refuses to touch the file.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
APP_ROOT = REPO_ROOT / "theseus-codex" / "src" / "app"
README = REPO_ROOT / "README.md"

BEGIN_MARK = "<!-- BEGIN SURFACE MAP -->"
END_MARK = "<!-- END SURFACE MAP -->"

SURFACE_COMMENT_RE = re.compile(
    r"(?://|/\*+|\*)\s*surface:\s*(.+?)\s*(?:\*/)?\s*$",
    re.MULTILINE,
)


def _route_from_path(page: pathlib.Path) -> str:
    """Convert ``theseus-codex/src/app/(authed)/foo/[id]/page.tsx``
    into ``/foo/[id]``.

    Route-group parentheses are URL-transparent and dropped.
    """
    rel = page.relative_to(APP_ROOT).parent
    parts: list[str] = []
    for p in rel.parts:
        if p.startswith("(") and p.endswith(")"):
            continue
        parts.append(p)
    return "/" + "/".join(parts) if parts else "/"


def _surface_purpose(page: pathlib.Path, max_head_chars: int = 2048) -> str | None:
    try:
        head = page.read_text(errors="replace")[:max_head_chars]
    except OSError:
        return None
    m = SURFACE_COMMENT_RE.search(head)
    return m.group(1).strip() if m else None


def collect_routes() -> list[tuple[str, str | None, pathlib.Path]]:
    if not APP_ROOT.is_dir():
        return []
    out: list[tuple[str, str | None, pathlib.Path]] = []
    for page in APP_ROOT.rglob("page.tsx"):
        # Skip backup / scratch files.
        if any(p.startswith(".") for p in page.relative_to(APP_ROOT).parts):
            continue
        route = _route_from_path(page)
        purpose = _surface_purpose(page)
        out.append((route, purpose, page))
    out.sort(key=lambda x: x[0])
    return out


def render_markdown(routes: list[tuple[str, str | None, pathlib.Path]]) -> str:
    lines = [
        BEGIN_MARK,
        "",
        "## Surface map",
        "",
        "_Generated by `scripts/generate_surface_map.py`. Re-run when "
        "routes are added or removed; the doc-freshness check enforces "
        "sync between this list and the Next.js app tree._",
        "",
    ]
    for route, purpose, _page in routes:
        label = purpose if purpose else "_(unannotated — add `// surface: ...` at top of page.tsx)_"
        lines.append(f"- `{route}` — {label}")
    lines.append("")
    lines.append(END_MARK)
    return "\n".join(lines)


def _rewrite_readme(readme: pathlib.Path, block: str) -> bool:
    text = readme.read_text()
    if BEGIN_MARK not in text or END_MARK not in text:
        return False
    pattern = re.compile(
        re.escape(BEGIN_MARK) + r".*?" + re.escape(END_MARK),
        re.DOTALL,
    )
    new_text = pattern.sub(block, text, count=1)
    readme.write_text(new_text)
    return True


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--write",
        action="store_true",
        help="Rewrite README.md between the SURFACE MAP markers in place.",
    )
    p.add_argument(
        "--readme",
        default=str(README),
        help="Path to README.md (default: repo-root README).",
    )
    args = p.parse_args(argv)

    if not APP_ROOT.is_dir():
        print(
            f"App tree not found at {APP_ROOT}; nothing to generate.",
            file=sys.stderr,
        )
        return 0

    routes = collect_routes()
    block = render_markdown(routes)

    if not args.write:
        print(block)
        return 0

    readme = pathlib.Path(args.readme)
    if not readme.is_file():
        print(f"README not found at {readme}.", file=sys.stderr)
        return 2
    if not _rewrite_readme(readme, block):
        print(
            f"{readme} is missing {BEGIN_MARK} / {END_MARK} markers. "
            "Add the markers manually (and a 'Surface map' heading "
            "between them), then re-run.",
            file=sys.stderr,
        )
        return 2
    print(f"Wrote surface map block to {readme}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
