#!/usr/bin/env python3
"""Generate TypeScript types from the FastAPI app's response models.

Walks the ``current_events_api`` FastAPI app, enumerates every route
that declares a Pydantic ``response_model``, groups them by the Python
module the endpoint lives in, and writes one ``<module>.ts`` file per
group into ``theseus-codex/src/lib/_generated/api/``. An ``index.ts``
re-exports every type so callers can write::

    import type { OracleAnswer } from "@/lib/_generated/api";

The generator emits deterministic, byte-stable output — every model is
visited in alphabetical order, every property is emitted in declared
order, and the output carries an AUTOGENERATED banner so the lint in
``.github/workflows/type-contracts.yml`` can refuse hand-edits.

Routes whose ``response_model`` is a bare ``dict``/``list``/``Any``
(no Pydantic root) are skipped — there's nothing static to emit.
They are recorded in a comment at the top of the file so the missing
contract is visible at review time.

Usage::

    python scripts/generate_api_types.py             # write
    python scripts/generate_api_types.py --check     # exit 1 on drift
    python scripts/generate_api_types.py --out PATH  # custom out dir

The script is invoked from the pre-commit hook and the
``type-contracts`` CI workflow. It is exercised by
``tests/static/test_api_types_in_sync.py``.
"""

from __future__ import annotations

import argparse
import difflib
import importlib
import json
import os
import pathlib
import sys
from typing import Any, Iterable

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_OUT = (
    REPO_ROOT / "theseus-codex" / "src" / "lib" / "_generated" / "api"
)
GENERATED_BANNER = (
    "/* AUTOGENERATED by scripts/generate_api_types.py — do not edit.\n"
    " *\n"
    " * Source: current_events_api FastAPI app response models.\n"
    " * Regenerate with: python scripts/generate_api_types.py\n"
    " * CI fails on drift; the pre-commit hook regenerates locally.\n"
    " */\n"
)


# ── App loading ─────────────────────────────────────────────────────────────


def _ensure_paths() -> None:
    """Make ``current_events_api`` and ``noosphere`` importable.

    The generator is intentionally a standalone script — it doesn't
    require the API to be installed as a package, so we manipulate
    ``sys.path`` ourselves rather than relying on editable installs.
    """
    for sub in ("current_events_api", "noosphere"):
        p = str(REPO_ROOT / sub)
        if p not in sys.path:
            sys.path.insert(0, p)


def load_app() -> Any:
    _ensure_paths()
    # Importing the package side-effects environment variables. Set
    # safe defaults so an unconfigured environment doesn't trip the
    # app's lifespan or rate-limiter init.
    os.environ.setdefault("CURRENTS_CORS_ORIGINS", "")
    os.environ.setdefault("NOOSPHERE_DATA_DIR", str(REPO_ROOT / "noosphere_data"))
    main = importlib.import_module("current_events_api.main")
    return main.app


# ── Pydantic model collection ───────────────────────────────────────────────


def _is_pydantic_model(obj: Any) -> bool:
    try:
        from pydantic import BaseModel
    except ImportError:  # pragma: no cover — should always be present
        return False
    return isinstance(obj, type) and issubclass(obj, BaseModel)


def _walk_type(t: Any, sink: list[Any]) -> None:
    """Recursively collect Pydantic models reachable from a type annotation."""
    from typing import get_args, get_origin

    if t is None or t is type(None):
        return
    if _is_pydantic_model(t):
        if t not in sink:
            sink.append(t)
        return
    origin = get_origin(t)
    if origin is not None:
        for arg in get_args(t):
            _walk_type(arg, sink)
    # Bare typing constructs (Any, dict, list) yield nothing.


def collect_route_models(app: Any) -> dict[str, list[Any]]:
    """Group response-model Pydantic classes by route-module short name.

    Returns ``{module_basename: [BaseModel-subclass, ...]}`` with each
    list deduplicated and sorted by class name for stable output.
    Module-basename is the last segment of ``endpoint.__module__`` so
    e.g. ``current_events_api.routes.oracle`` collapses to ``oracle``.
    """
    grouped: dict[str, list[Any]] = {}
    skipped: dict[str, list[str]] = {}
    for route in app.routes:
        rm = getattr(route, "response_model", None)
        endpoint = getattr(route, "endpoint", None)
        if endpoint is None:
            continue
        module = endpoint.__module__.rsplit(".", 1)[-1]
        if rm is None:
            continue
        models: list[Any] = []
        _walk_type(rm, models)
        if not models:
            skipped.setdefault(module, []).append(route.path)
            continue
        bucket = grouped.setdefault(module, [])
        for m in models:
            if m not in bucket:
                bucket.append(m)
    # Sort each bucket by class name for byte-stable output.
    return {k: sorted(v, key=lambda c: c.__name__) for k, v in sorted(grouped.items())}


# ── JSON schema → TypeScript emission ───────────────────────────────────────


_TS_PRIMITIVE = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


def _ts_type(schema: dict[str, Any], defs: dict[str, dict[str, Any]]) -> str:
    """Translate a JSON schema fragment to a TypeScript type expression.

    Handles the cases Pydantic v2 produces in practice: primitives,
    arrays, objects with explicit ``properties``, ``additionalProperties``,
    enums, ``$ref`` into ``$defs``, ``anyOf``/``oneOf`` unions, and
    ``const`` literals. Anything we don't recognise falls back to
    ``unknown`` so the generated file stays valid TypeScript.
    """
    if not schema:
        return "unknown"
    if "const" in schema:
        v = schema["const"]
        return json.dumps(v) if isinstance(v, str) else str(v).lower() if isinstance(v, bool) else json.dumps(v)
    if "$ref" in schema:
        return _ref_name(schema["$ref"])
    if "enum" in schema:
        return " | ".join(
            json.dumps(v) if isinstance(v, str) else json.dumps(v)
            for v in schema["enum"]
        )
    for combiner in ("anyOf", "oneOf"):
        if combiner in schema:
            parts = [_ts_type(s, defs) for s in schema[combiner]]
            # Dedupe while preserving order.
            seen: dict[str, None] = {}
            for p in parts:
                seen.setdefault(p, None)
            return " | ".join(seen.keys()) or "unknown"
    if "allOf" in schema and len(schema["allOf"]) == 1:
        return _ts_type(schema["allOf"][0], defs)

    t = schema.get("type")
    if isinstance(t, list):
        # ``type: ["string", "null"]`` → ``string | null``.
        parts = [_TS_PRIMITIVE.get(x, "unknown") for x in t]
        return " | ".join(parts)
    if t in _TS_PRIMITIVE:
        return _TS_PRIMITIVE[t]
    if t == "array":
        items = schema.get("items", {})
        if isinstance(items, list):  # tuple-form arrays
            inner = " | ".join(_ts_type(s, defs) for s in items)
        else:
            inner = _ts_type(items, defs)
        return f"Array<{inner}>"
    if t == "object" or "properties" in schema or "additionalProperties" in schema:
        if "properties" in schema:
            # Inline object — emit as `{ a: T; b: U }`. Used for nested
            # anonymous shapes (rare; named ones come through $defs).
            req = set(schema.get("required", []))
            fields = []
            for name, sub in schema["properties"].items():
                opt = "" if name in req else "?"
                fields.append(f"{json.dumps(name)}{opt}: {_ts_type(sub, defs)}")
            return "{ " + "; ".join(fields) + " }"
        ap = schema.get("additionalProperties")
        if ap is True or ap is None:
            return "Record<string, unknown>"
        if isinstance(ap, dict):
            return f"Record<string, {_ts_type(ap, defs)}>"
        return "Record<string, never>"
    return "unknown"


def _ref_name(ref: str) -> str:
    # ``#/$defs/Foo`` → ``Foo``.
    return ref.rsplit("/", 1)[-1]


def _emit_interface(name: str, schema: dict[str, Any], defs: dict[str, dict[str, Any]]) -> str:
    """Emit a single ``export interface Name { … }`` block.

    Properties are emitted in their declared order (Pydantic preserves
    field-declaration order in the schema), keeping the diff readable
    when a model is reordered upstream.
    """
    if schema.get("enum"):
        # String enums become a union type alias.
        rhs = " | ".join(
            json.dumps(v) if isinstance(v, str) else json.dumps(v)
            for v in schema["enum"]
        )
        return f"export type {name} = {rhs};\n"
    if schema.get("type") and schema["type"] != "object" and "properties" not in schema:
        # Aliased primitive / array — uncommon but valid.
        return f"export type {name} = {_ts_type(schema, defs)};\n"
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for prop_name, prop_schema in props.items():
        opt = "" if prop_name in required else "?"
        ts = _ts_type(prop_schema, defs)
        # Quote keys that aren't valid JS identifiers.
        if prop_name.isidentifier():
            key = prop_name
        else:
            key = json.dumps(prop_name)
        lines.append(f"  {key}{opt}: {ts};")
    if not props:
        # Object with no properties (e.g. an empty model) — emit as
        # ``Record<string, never>`` alias so consumers can still
        # reference the name.
        return f"export type {name} = Record<string, never>;\n"
    lines.append("}\n")
    return "\n".join(lines)


def _gather_defs(model: Any) -> tuple[str, dict[str, dict[str, Any]]]:
    """Return ``(root_name, {name: schema})`` for a Pydantic model.

    Pydantic v2 emits the root model under its own key inside
    ``$defs`` plus the top-level schema. We normalise so the root and
    every transitive sub-model appear in one ``defs`` dict keyed by
    class name.
    """
    schema = model.model_json_schema(ref_template="#/$defs/{model}")
    defs = dict(schema.get("$defs", {}))
    root_name = schema.get("title") or model.__name__
    # The root schema itself is not under $defs by default — splice it in.
    root_schema = {k: v for k, v in schema.items() if k != "$defs"}
    defs.setdefault(root_name, root_schema)
    return root_name, defs


# ── File-level emission ─────────────────────────────────────────────────────


def render_module_file(module: str, models: Iterable[Any]) -> str:
    all_defs: dict[str, dict[str, Any]] = {}
    root_names: list[str] = []
    for m in models:
        root, defs = _gather_defs(m)
        if root not in root_names:
            root_names.append(root)
        for name, sch in defs.items():
            # First write wins — Pydantic emits the same shape for the
            # same class name regardless of which root pulled it in.
            all_defs.setdefault(name, sch)

    body_parts = [GENERATED_BANNER]
    # Stable order: all interfaces alphabetised. Root names appear in
    # the same alphabetical pass so we don't special-case them.
    for name in sorted(all_defs):
        body_parts.append(_emit_interface(name, all_defs[name], all_defs))
    return "\n".join(body_parts).rstrip("\n") + "\n"


def render_index_file(grouped: dict[str, list[Any]]) -> str:
    lines = [GENERATED_BANNER.rstrip("\n"), ""]
    # First pass: collect every def name per module so the re-export
    # order is fully sorted within a module (not dependent on which
    # root model pulled in which sub-model).
    by_module: dict[str, set[str]] = {}
    for module, models in grouped.items():
        names: set[str] = set()
        for m in models:
            _root, defs = _gather_defs(m)
            names.update(defs.keys())
        by_module[module] = names
    # Second pass: emit re-exports. A name re-exported from an earlier
    # module is skipped from later ones so the index can be wildcarded
    # without TS complaining about duplicate symbols.
    seen: set[str] = set()
    for module in sorted(by_module):
        unique = sorted(n for n in by_module[module] if n not in seen)
        if not unique:
            continue
        seen.update(unique)
        joined = ", ".join(unique)
        lines.append(f'export type {{ {joined} }} from "./{module}";')
    lines.append("")
    return "\n".join(lines)


# ── Top-level driver ────────────────────────────────────────────────────────


def generate(out_dir: pathlib.Path) -> dict[str, str]:
    app = load_app()
    grouped = collect_route_models(app)
    files: dict[str, str] = {}
    for module, models in grouped.items():
        files[f"{module}.ts"] = render_module_file(module, models)
    files["index.ts"] = render_index_file(grouped)
    # Preserve the .gitkeep — the static checker writes it explicitly.
    return files


def write(out_dir: pathlib.Path, files: dict[str, str]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    # Remove stale .ts files that are no longer generated (but never
    # the .gitkeep — that's an unconditional sentinel).
    keep = set(files) | {".gitkeep"}
    for existing in out_dir.glob("*.ts"):
        if existing.name not in keep:
            existing.unlink()
    for name, content in files.items():
        (out_dir / name).write_text(content, encoding="utf-8")


def check(out_dir: pathlib.Path, files: dict[str, str]) -> int:
    """Compare files against on-disk contents; return 0 if in sync."""
    drift: list[str] = []
    on_disk_files = {p.name for p in out_dir.glob("*.ts")}
    expected_files = set(files)
    missing = expected_files - on_disk_files
    extra = on_disk_files - expected_files
    for name in sorted(missing):
        drift.append(f"  + (missing) {name}")
    for name in sorted(extra):
        drift.append(f"  - (stale)   {name}")
    for name, content in files.items():
        path = out_dir / name
        if not path.is_file():
            continue
        existing = path.read_text(encoding="utf-8")
        if existing != content:
            diff = "\n".join(
                difflib.unified_diff(
                    existing.splitlines(),
                    content.splitlines(),
                    fromfile=f"a/{name}",
                    tofile=f"b/{name}",
                    lineterm="",
                )
            )
            drift.append(f"--- drift in {name} ---\n{diff}")
    if drift:
        print(
            "scripts/generate_api_types.py: generated TS types are out of "
            "sync with the FastAPI response models.\n"
            "Run `python scripts/generate_api_types.py` and commit the diff.\n",
            file=sys.stderr,
        )
        print("\n".join(drift), file=sys.stderr)
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail on drift")
    parser.add_argument(
        "--out",
        type=pathlib.Path,
        default=DEFAULT_OUT,
        help="output directory (default: theseus-codex/src/lib/_generated/api)",
    )
    args = parser.parse_args(argv)
    files = generate(args.out)
    if args.check:
        return check(args.out, files)
    write(args.out, files)
    try:
        display = args.out.relative_to(REPO_ROOT)
    except ValueError:
        display = args.out
    print(f"generate_api_types: wrote {len(files)} files to {display}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main(sys.argv[1:]))
