#!/usr/bin/env bash
# run_dead_code_survey.sh
#
# Regenerates docs/architecture/Dead_Code_Survey.md from a fresh ts-prune /
# vulture sweep. The committed survey document records, per candidate:
#
#     file, symbol, last commit, decision (remove | keep | follow-up)
#
# This script overwrites only the auto-generated "## Raw findings" section
# of the document. Human-curated rows above that marker are preserved so
# triage decisions survive a re-run.
#
# Usage:
#   ./scripts/run_dead_code_survey.sh           # rewrite survey doc
#   ./scripts/run_dead_code_survey.sh --raw     # print raw scan only, do
#                                                 not touch the doc
#
# Exit codes:
#   0  scans completed
#   1  a required tool was unreachable
#
# Tools:
#   ts-prune  — fetched via `npx -y ts-prune@0.10.3` if not on PATH.
#   vulture   — fetched via `python3 -m vulture`; if missing, the script
#               falls back to `python3 -m pip install --user vulture` once.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DOC="${REPO_ROOT}/docs/architecture/Dead_Code_Survey.md"
TC_DIR="${REPO_ROOT}/theseus-codex"
NOOSPHERE_DIR="${REPO_ROOT}/noosphere"

RAW_ONLY=0
if [ "${1:-}" = "--raw" ]; then
  RAW_ONLY=1
fi

have_node() { command -v node >/dev/null 2>&1; }
have_python() { command -v python3 >/dev/null 2>&1; }

if ! have_node; then
  echo "run_dead_code_survey: 'node' not found — install Node 20+." >&2
  exit 1
fi
if ! have_python; then
  echo "run_dead_code_survey: 'python3' not found." >&2
  exit 1
fi

if ! python3 -m vulture --version >/dev/null 2>&1; then
  echo "run_dead_code_survey: installing vulture (one-off, --user)..." >&2
  python3 -m pip install --user --quiet vulture >/dev/null 2>&1 || {
    echo "run_dead_code_survey: failed to install vulture." >&2
    exit 1
  }
fi

TMP_TS_RAW="$(mktemp)"
TMP_TS="$(mktemp)"
TMP_PY="$(mktemp)"
TMP_NEXT_PARENT=""

cleanup() {
  if [ -n "$TMP_NEXT_PARENT" ] && [ -d "$TMP_NEXT_PARENT/.next" ] && [ ! -e "$TC_DIR/.next" ]; then
    mv "$TMP_NEXT_PARENT/.next" "$TC_DIR/.next"
  fi
  rm -f "$TMP_TS_RAW" "$TMP_TS" "$TMP_PY"
  if [ -n "$TMP_NEXT_PARENT" ]; then
    rmdir "$TMP_NEXT_PARENT" 2>/dev/null || true
  fi
}
trap cleanup EXIT

# Next.js generated type files make app/page route exports look "used" on
# machines that have run `next build`, while CI runs this survey from a fresh
# checkout. Hide `.next` during the scan so local and CI baselines match.
if [ -d "$TC_DIR/.next" ]; then
  TMP_NEXT_PARENT="$(mktemp -d)"
  mv "$TC_DIR/.next" "$TMP_NEXT_PARENT/.next"
fi

filter_tracked_ts_prune_rows() {
  while IFS= read -r line; do
    file="${line%%:*}"
    case "$file" in
      .next/*) continue ;;
    esac
    if git -C "$TC_DIR" ls-files --error-unmatch -- "$file" >/dev/null 2>&1; then
      printf '%s\n' "$line"
    fi
  done
}

echo "==> ts-prune over theseus-codex/" >&2
(
  cd "$TC_DIR"
  npx -y ts-prune@0.10.3 -p tsconfig.json 2>/dev/null \
    > "$TMP_TS_RAW" || true
  filter_tracked_ts_prune_rows < "$TMP_TS_RAW" \
    | grep -v '(used in module)$' \
    > "$TMP_TS" || true
)

echo "==> vulture over noosphere/ (min-confidence 70)" >&2
(
  cd "$REPO_ROOT"
  python3 -m vulture noosphere/ --min-confidence 70 > "$TMP_PY" 2>/dev/null || true
)

TS_COUNT="$(wc -l < "$TMP_TS" | tr -d ' ')"
PY_COUNT="$(wc -l < "$TMP_PY" | tr -d ' ')"
echo "ts-prune candidates: ${TS_COUNT}" >&2
echo "vulture  candidates: ${PY_COUNT}" >&2

if [ "$RAW_ONLY" = "1" ]; then
  echo "===== ts-prune ====="
  cat "$TMP_TS"
  echo
  echo "===== vulture ====="
  cat "$TMP_PY"
  exit 0
fi

MARKER="<!-- BEGIN AUTOGENERATED -->"
END_MARKER="<!-- END AUTOGENERATED -->"

if [ ! -f "$DOC" ]; then
  echo "run_dead_code_survey: $DOC missing — create it first." >&2
  exit 1
fi
if ! grep -q "$MARKER" "$DOC"; then
  echo "run_dead_code_survey: marker '$MARKER' not in $DOC." >&2
  exit 1
fi

HEAD_BLOCK="$(awk -v m="$MARKER" 'BEGIN{p=1} {if(index($0,m))p=0} p' "$DOC")"

TS_TABLE="$(awk -F'[: -]+' '
  {
    file=$1; line=$2; sym=""
    # The line we got is "file:line - symbol"; split on " - "
    idx=index($0, " - ")
    if (idx==0) next
    pre=substr($0,1,idx-1)
    sym=substr($0,idx+3)
    n=split(pre, p, ":")
    file=p[1]; line=p[2]
    printf("| `%s` | `%s` | L%s | follow-up |\n", file, sym, line)
  }
' "$TMP_TS")"

PY_TABLE="$(awk -F: '
  {
    file=$1; line=$2
    rest=$3
    for(i=4;i<=NF;i++) rest=rest ":" $i
    sub(/^[ \t]+/,"",rest)
    printf("| `%s` | `%s` | L%s | follow-up |\n", file, rest, line)
  }
' "$TMP_PY")"

{
  printf '%s\n' "$HEAD_BLOCK"
  printf '%s\n\n' "$MARKER"
  printf '_Regenerated by `scripts/run_dead_code_survey.sh`._\n\n'
  printf '### TypeScript candidates (ts-prune, %s rows)\n\n' "$TS_COUNT"
  printf '| File | Symbol | Line | Decision |\n'
  printf '|------|--------|------|----------|\n'
  if [ -n "$TS_TABLE" ]; then printf '%s\n' "$TS_TABLE"; fi
  printf '\n### Python candidates (vulture --min-confidence 70, %s rows)\n\n' "$PY_COUNT"
  printf '| File | Symbol | Line | Decision |\n'
  printf '|------|--------|------|----------|\n'
  if [ -n "$PY_TABLE" ]; then printf '%s\n' "$PY_TABLE"; fi
  printf '\n%s\n' "$END_MARKER"
} > "$DOC.tmp"

mv "$DOC.tmp" "$DOC"
echo "Updated $DOC" >&2
