"""API type-contract gate.

Round 19 introduced ``theseus-codex/src/lib/_generated/api/`` — a
committed bundle of TypeScript types derived from the FastAPI app's
Pydantic ``response_model`` declarations. This test pins the two
failure modes that bundle is meant to prevent:

1. **Drift between Pydantic and TS.** If a developer changes a
   response model and forgets to regenerate the TS bundle, the
   frontend keeps reading the old shape until production traffic
   surfaces a 5xx. The ``test_committed_types_are_in_sync`` case
   re-runs the generator into a temp directory and asserts byte-for-
   byte equality with the committed bundle.

2. **Generator silently degrades.** If the generator stops emitting
   a model (because the response_model was changed to ``dict``,
   say), drift becomes invisible. The
   ``test_drift_fixture_is_detected`` case plants a synthetic model
   with a renamed field and asserts the generator emits a diff against
   the baseline ``synthetic_drift_fixture.ts``.

Both cases shell out to ``scripts/generate_api_types.py`` so the
exact same code path runs in tests, pre-commit, and CI.
"""

from __future__ import annotations

import pathlib
import subprocess
import sys
import tempfile

import pytest

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
GENERATOR = REPO_ROOT / "scripts" / "generate_api_types.py"
COMMITTED = REPO_ROOT / "theseus-codex" / "src" / "lib" / "_generated" / "api"
DRIFT_FIXTURE_DIR = REPO_ROOT / "tests" / "static" / "fixtures" / "synthetic_drift"
DRIFT_FIXTURE_BASELINE = DRIFT_FIXTURE_DIR / "synthetic_drift_fixture.ts"


def test_committed_types_are_in_sync() -> None:
    """``generate_api_types.py --check`` must exit 0 on the committed tree.

    The check command re-runs the generator in memory and diffs the
    output against on-disk. A non-zero exit means a developer renamed
    a field, added a model, or removed a route without regenerating —
    fix by running ``python scripts/generate_api_types.py`` and
    committing the diff (this is intentional friction; the diff is the
    review surface for the change).
    """
    proc = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, (
        "API type bundle is out of sync.\n\n"
        f"stdout:\n{proc.stdout}\n\nstderr:\n{proc.stderr}\n\n"
        "Run: python scripts/generate_api_types.py"
    )


def test_drift_fixture_is_detected() -> None:
    """Plant a drift on a fixture model and assert the emitter sees it.

    We don't shell out to the generator (that walks the *real* FastAPI
    app); instead we exercise the public ``render_module_file`` /
    ``_emit_interface`` helpers with the drifted Pydantic model and
    confirm the rendered output differs from the committed baseline.
    """
    sys.path.insert(0, str(REPO_ROOT))
    try:
        from scripts.generate_api_types import render_module_file
        from tests.static.fixtures.synthetic_drift import (
            FixtureModel,
            FixtureModelDrifted,
        )
    finally:
        try:
            sys.path.remove(str(REPO_ROOT))
        except ValueError:
            pass

    baseline = render_module_file("synthetic_drift_fixture", [FixtureModel])
    assert DRIFT_FIXTURE_BASELINE.is_file(), (
        f"missing baseline: {DRIFT_FIXTURE_BASELINE} — regenerate the fixture"
    )
    on_disk = DRIFT_FIXTURE_BASELINE.read_text(encoding="utf-8")
    assert baseline == on_disk, (
        "Baseline TS for the drift fixture is out of sync with the emitter — "
        "regenerate `tests/static/fixtures/synthetic_drift/synthetic_drift_fixture.ts`."
    )

    drifted = render_module_file("synthetic_drift_fixture", [FixtureModelDrifted])
    assert drifted != baseline, (
        "The drifted fixture model produced *identical* TS — the emitter is "
        "no longer reflecting Pydantic field changes. This is a silent-drift "
        "regression."
    )
    # The new field must appear in the drifted output.
    assert "new_field" in drifted, (
        "Drift detected but the new field is missing from TS output:\n" + drifted
    )


def test_generator_writes_index_file() -> None:
    """Smoke test the writer in a scratch directory."""
    with tempfile.TemporaryDirectory() as tmp:
        out = pathlib.Path(tmp) / "api"
        proc = subprocess.run(
            [sys.executable, str(GENERATOR), "--out", str(out)],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
        )
        assert proc.returncode == 0, proc.stderr
        index = out / "index.ts"
        assert index.is_file(), "generator did not write index.ts"
        body = index.read_text(encoding="utf-8")
        assert "AUTOGENERATED" in body
        # Must re-export at least one known root model from the real
        # FastAPI app.
        assert "OracleAnswer" in body or "PortfolioSurface" in body, (
            "index.ts does not look like it covers the FastAPI app"
        )


@pytest.mark.parametrize(
    "fname",
    [
        "index.ts",
        "oracle.ts",
        "portfolio.ts",
    ],
)
def test_committed_files_carry_autogenerated_banner(fname: str) -> None:
    """Every committed file must declare AUTOGENERATED at the top.

    CI lint refuses files without this banner so hand-edits are loud.
    """
    path = COMMITTED / fname
    assert path.is_file(), f"missing {path}"
    head = path.read_text(encoding="utf-8")[:512]
    assert "AUTOGENERATED" in head, f"{fname} is missing the AUTOGENERATED banner"
